### ISSUE TITLE
Error renaming file. Invalid cross-device link

### ISSUE THREAD

**Issue by nicolas-raoul** [geany/geany#1010]
Every time I create a new file (CTRL+n) and rename it, I get this error:

![geany](https://cloud.githubusercontent.com/assets/99590/14814716/7a304e0e-0be2-11e6-805e-15235046bfeb.png)

The file gets correctly renamed, though. No trouble beyond this surprising popup.

Ubuntu 2015.10 and its Geany 1.25, with Save Actions plugin enabled. Encrypted home.

**Comment by elextr** [comment]
What are your save-actions plugin settings and what are your save settings (Various preferences use_atomic_file_saving, use_gio_unsafe_file_saving and gio_unsafe_save_backup)?

**Comment by nicolas-raoul** [comment]
![conf1](https://cloud.githubusercontent.com/assets/99590/14817386/fc12111e-0bf1-11e6-8cac-7485b51ea2fb.png)
![conf2](https://cloud.githubusercontent.com/assets/99590/14817385/fc10c1a6-0bf1-11e6-8754-bed6f6dc46f8.png)
![conf3](https://cloud.githubusercontent.com/assets/99590/14817387/fc2258b2-0bf1-11e6-86f6-5965fd07d05c.png)
Thanks!

**Comment by elextr** [comment]
In future please don't paste images, just say what the settings are.

What is happening is that because you have "Instant Save" enabled, the new file is saved in /tmp with a temporary filename.  You then try to rename it to somewhere else which is on a different filesystem.  But you cannot rename between filesystems.  However you are saved because then the Save As saves the file to the new location anyway.  You will probably find the original temp files are still in /tmp but thats no problem since they will go away at next reboot.

So just do Save As, not rename.
