### ISSUE TITLE
C++ template parameters

### ISSUE THREAD

**Issue by misopeth** [geany/geany#1084]
It would be useful if template parameters appearance could be personalised, like it can be done on types.

**Comment by elextr** [comment]
Do you mean highlighted?

Highlighting is a syntactic construct, but names being parameters or types or variables or whatever is a semantic construct.  

The type highlighting works for for C where type names do not overlap with other names, but in C++ you will find all occurrences of the name are type coloured, even if they are not a type in the specific context.  This is because the syntactic highlighting has no concept of the semantics.

So it is not possible with the current system design.

**Comment by misopeth** [comment]
I meant something like this: 
![eclipse](https://cloud.githubusercontent.com/assets/8974735/16250618/21f7b4c0-381f-11e6-8f3f-abb815a617b7.png)
However this is not really important.

**Comment by elextr** [comment]
Yes, that fact that `T` is a template parameter in the scope of the struct is semantic information, not pure syntax.  But syntax is all highlighting can be based on.

**Comment by codebrainz** [comment]
@elextr it would be no more broken/less useful than current (broken) typename highlighting. All it would require is that CTags to tag them

**Comment by elextr** [comment]
Don't know about the new ctags C++ parser, but the current one skips over the content of `<>`s and does not parse them.

**Comment by codebrainz** [comment]
I'm not at all familiar with it, but it looks like at least some progress has been made in UCTags:

https://github.com/universal-ctags/ctags/blob/master/parsers/cxx/cxx_parser_template.c
