### ISSUE TITLE
Text in the search dialog or the toolbar search field becomes invisible

### ISSUE THREAD

**Issue by f2404** [geany/geany#1135]
Sometimes the text I'm searching for becomes invisible in the input field. I can see that it's there if I select it (press Ctrl+A); otherwise, I cannot see it.
Presumably, it's happening if geany cannot find the text entered.

My system is: Arch Linux; geany 1.28 (built against gtk2); gtk2 2.24.30; gtk3 3.20.6; glib 2.48.1; Cinnamon 3.0.5.

Could be the same issue as #1101 or a different one.

**Comment by f2404** [comment]
Thanks!

**Comment by pwil3058** [comment]
It's very similar and if I'd found this when I checked for bugs I would not have created a new bug report.  After reading the above, I did some tests and  reproduced the reported problems.  The text is there (just not visible or editable) and if I put some text in the file being edited that matches the search it gets found OK and, magically, the text reappears in the "Search for::" field and is editable again.

I also should have mentioned that the problem is independent of whether the "Cancel" of "Find" option is selected in the failed search pop up.

My relevant packages are: gtk2-2.24.30, gtk3-3.20.9, glib-1.2.10, glibc-2.23.1 and cinnamon-3.0.7 so similar to but not exactly the same.
