### ISSUE TITLE
Message noticed on Geany shutdown ...

### ISSUE THREAD

**Issue by elextr** [geany/geany#1157]
```
###!!! [Parent][OnMaybeDequeueOne] Error: Channel closing: too late to send/recv, messages will be lost
```

Geany Git 5d8e291c, GTK 3.18.9 Glib 2.48.1 Plugins addons and splitwindow.

No document was open.  Not repeatable so message was probably from something done before shutdown, but not noticed until later.

**Comment by b4n** [comment]
looks like a message from Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1139596, first link from a search engine).  you probably have Firefox configured as your browser, and somehow triggered opening it from Geany (showing help or alike).

**Comment by elextr** [comment]
Ahhh, yeah, probably opening help.  Why doesn't Geany use xdg-open or such by default so it will use my already running chrome, not start firevermin?

**Comment by b4n** [comment]
Geany uses the configured browser command, which indeed [defaults to `firefox`](/geany/geany/tree/master/src/keyfile.c#L90).  Some time ago when the setting had hard-coded fallbacks, `xdg-open` was added as the first alternative in 0d4cbd60a15a7d2bc8b45cb43633705584fdde98.  Since then the setting has no hard-coded fallback and asks the user to revise the setting when it doesn't work.

Maybe using `xdg-open` as default could be sensible on non-Mac non-Windows, but I don't know the implications.

**Comment by elextr** [comment]
Myeh, probably not worth the effort, I assume once its configured it will stay in the config for most people. Its only people like us who keep creating new Geanys who keep getting new configs, just have to remember to configure it.
