### ISSUE TITLE
Problem installing due to missing 'aclocal-1.14'

### ISSUE THREAD

**Issue by mmphego** [geany/geany#1205]
Hi, 
I had an issue installing the latest geany pull. Error received:
`home/mmphego/Apts/geany-plugins/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:573: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
`

The fix is a one liner:
`autoreconf -fi`

**Comment by elextr** [comment]
Yes, you have upgraded your autotools.  That happened to me when my distro upgraded.  Either your solution or re-running `autogen.sh` or anything else to regenerate the build tools will work.

**Comment by elextr** [comment]
I should add that IIUC its not anything to do with Geany, its the tools, and nothing we can do to fix it.

**Comment by b4n** [comment]
Yep, it's simply Autotools not liking to use a different version of one of its tools to update an existing build system (likely because they know they often show slight incompatibilities that can lead to more serious breakage in some more exotic use of them).

The only solution I know of is to manually re-generating the build system with the new version as you and @elextr did, either with `autogen.sh` or directly with `autoreconf`.
