### ISSUE TITLE
Parentheses matching not working in makefile

### ISSUE THREAD

**Issue by elextr** [geany/geany#1207]
For the line:

```
ME = $(abspath $(lastname ($MAKE_LIST)))
```

the outer parentheses don't highlight, irrespective of where the cursor is placed, the nested parentheses highlight as expected.

The same line in another filetype (say C++) the outer parentheses highlight with the cursor either side of the first `(` and after the last `)`

**Comment by codebrainz** [comment]
I think Make lexer uses `$(` and `)` for brace-matching. If you write your example normally like `ME = $(abspath $(lastname $(MAKE_LIST)))` it matches the parenthesis normally.

**Comment by elextr** [comment]
Yes there is and error in the given expression, but the point is I didn't think parentheses matching needed correct syntax to work?  The only syntax I thought it should take into account was to skip comments and strings.  

As the example above shows, if you have made a typo, its is no longer helpful to you.

**Comment by codebrainz** [comment]
It's helpful in that it shows you made a typo :)

**Comment by elextr** [comment]
On 4 September 2016 at 16:37, Matthew Brush <notifications@github.com>
wrote:

> It's helpful in that it shows you made a typo :)
>

​Yeah, but it doesn't help me find it :)​

**Comment by b4n** [comment]
The brace matching requires both open and close braces to be in the same style AFAIR, and that's how it knows it's not a string/command/whatever else is different.   In your example, the last closing parenthesis has style 0 instead of 3 (because it's not part of a valid variable expression).

IMO this is invalid, because it's basically the same as having the brace in a comment or a string, etc. and there you would see what's wrong.  IMO, if anything, change the styling for style 3 (`identifier`) to some different color so you discriminate it from style 0 (`default`).
