### ISSUE TITLE
Small inconsistency with property files (*.ini)

### ISSUE THREAD

**Issue by Heihon** [geany/geany#1220]
Geany 1.28 Release (Windows and Linux) and Geany 1.29 and I think also Geany 1.27 and before

Lines that start with ';' are syntax highlighted as comment.
Lines that start with '#' are syntax highlighted as comment.
An entry "key=value" in a line starting with ';' is shown in the symbols list.
An entry "key=value" in a line starting with '#' is not shown in the symbols list.

I attached a small test file test.ini, but I had to rename it to test.ini.txt because github refused to upload test.ini
[test.ini.txt](https://github.com/geany/geany/files/464268/test.ini.txt)

**Comment by codebrainz** [comment]
With the default settings, `;` shouldn't be highlighted as a comment (we even [tell it to use `#` as the comment start](https://github.com/geany/geany/blob/1.28.0/data/filedefs/filetypes.conf#L24)). I guess the syntax highlighter must have it hard-coded inside to always support Windows-style `;` comments.

**Comment by elextr** [comment]
The highlighting of comments is the Scintilla lexer, which highlights several similar versions of properties files and is hard coded to use `#`, `!` and `;` for comments.  There is not way to change that without changing Scintilla, which is a separate project from Geany, you can raise a request [here](https://sourceforge.net/p/scintilla/feature-requests/).  But since all such properties files tend to use the extensions `.ini`, `.conf` etc interchangably its hard to tell them apart and  I suggest it should remain general despite the fact that an occasional error may occur in highlighting.

The symbol parser is hard coded to use `#` and `//` as comments.  There is no way of changing that without changing the ctags parser.  The parsers mostly come from the [universal-ctags](https://github.com/universal-ctags/ctags/) project.  The Geany one is the parent of the [uctags](https://github.com/universal-ctags/ctags/blob/master/parsers/iniconf.c) one, but that has been changed to look for `;` as well.  There is an ongoing exercise to align Geany's parsers with uctags.  @techee, maybe this should be added to the TODO list if it isn't already.

**Comment by techee** [comment]
Seems to be fixed with the updated parser.
