### ISSUE TITLE
fails to open Microsoft UTF-16LE file (MSO Word CUSTOM.DIC dictionary file)

### ISSUE THREAD

**Issue by zenaan** [geany/geany#1238]
Microsoft office/ MS Word (all versions) saves its custom dictionary spelling word lists in a text encoding that Microsoft Windows calls UTF16 or UTF-16, but which is more specifically described as UTF-16LE or "little endian", as distinct from UTF-16BE or "big endian".

Geany 1.28 for Windows "(built on or after Jul 10 2016)", running on Windows 10, fails to open this file type (right click menu, or start Geany, and "Open").

I've tried choosing both File Encoding "UTF-16LE" and "UTF-16BE", as well as "auto detect", and tried "Set file type" to "detect from file" and "none".

In all cases I've tried, Geany fails. With UTF-16LE, the failure manifests in the error:

12:40:12: The file "C:\tmp\CUSTOM.dic" is not valid UTF-16LE.

and in the case of choosing UTF-16BE, the failure manifests as improper display/loading of the file - instead of a word per line, there is an endless series of long thin square rectangles on a single line.

So I go back to using Notepad++ or Akelpad... at least for the time being.

I suspect that the problem is Microsoft inserting BOM or "Unicode byte order mark" character into the file, and even though I manually specify file encoding and file type, Geany does some sort of auto detection thing, which it should NOT do when I manually choose the settings - even a bad rendering of a file (with my "bad" encoding choices") would be better than Geany completely FAILING to open the file at all!

Geany should have an option to "preserve BOM character" (in fact, should do this automatically), and should also have an option to "load file with my chosen encoding and filetype, even if Geany detects something not quite right"!!

Don't treat all users as stupid idiots! It makes your software look like a self conceited prig.

**Comment by elextr** [comment]
>  even a bad rendering of a file (with my "bad" encoding choices") would be better than Geany completely FAILING to open the file at all!

The Geany buffer is UTF-8, so Geany will not open the file if the conversion fails or the result does not validate as UTF-8 since it would risk undefined behaviour.  Any error from the conversion is shown in `menu->help->debug messages`.

> Geany should have an option to "preserve BOM character" (in fact, should do this automatically),

The bom is removed from the buffer as it is undisplayable and saved to be put back when the buffer is saved as a file.

> should also have an option to "load file with my chosen encoding and filetype, even if Geany detects something not quite right"!!

As noted above that would risk undefined behaviour if the result was not valid UTF-8.

> Don't treat all users as stupid idiots! It makes your software look like a self conceited prig.

It is understandable that you are unhappy, but Geany is developed by volunteers, they do not have to help you, and being rude gives them no incentive to do so.

**Comment by zenaan** [comment]
I should certainly know better - thank you for reminding me that harsh
wording can be taking in non constructive ways.

Thanks for replying btw.

Hopefully geany can one day recognize this particular file format
properly. One way or another, it is not being recognized. NP++ and
Akelpad both recognize the format ok.

Thanks again,

**Comment by b4n** [comment]
Could you provide a sample file showing the issue?  UTF-16LE (with or without BOM) certainly seems to work fine here, so there must be something wrong either with the Windows version we ship or with a specificity of this file.

**Comment by elextr** [comment]
Any error from the conversion is shown in menu->help->debug messages. Please post it.

**Comment by zenaan** [comment]
On Mon, Sep 19, 2016 at 01:06:47AM -0700, elextr wrote:
> Any error from the conversion is shown in menu->help->debug messages. Please post it.

This is the error message:

18:54:54: Geany INFO    : Couldn't convert from UTF-16LE to UTF-8
   (Invalid byte sequence in conversion input).

Attached is the file.

**Comment by b4n** [comment]
> Attached is the file.

Unfortunately apparently GitHub drops attachments to email replies.  Could you upload it through the web UI, or somewhere else online?

**Comment by zenaan** [comment]
[CUSTOM-utf16le-2016.dic.zip](https://github.com/geany/geany/files/479602/CUSTOM-utf16le-2016.dic.zip)
Take 4, finally - hope it works :)

**Comment by b4n** [comment]
```
$ iconv -f UTF-16LE -t UTF-8 < CUSTOM-utf16le-2016.dic > CUSTOM-utf16le-2016.dic_utf8
iconv: illegal input sequence at position 34076
```

Apparently that file has bytes `\xca \xde` near the end, and that doesn't seem to be a sequence accepted by iconv (so I'd guess it really is invalid).
And trying and reading how UTF-16 works, it indeed seems invalid: there is the sequence `0xD7B8 0xDECA` in the input: `0xD7B8` is [HANGUL JUNGSEONG YU-O](http://www.charbase.com/d7b8-unicode-hangul-jungseong-yu-o), which is encoded on a single word (below `U+FFFD`, and not in the range `U+D800 - U+DFFF`). Next word is `0xDECA`, which, as being in the range `0xDC00 - 0xDFFF`, should be the second word of a two-word pair.  It is not (the previous word not being in the `0xD800 - 0xDBFF` range), so it is invalid.

I tested other editors, like GEdit and `vim`, and they both exhibit the same issue failing to properly open the file.  GEdit opens it almost correctly, but only up to the invalid sequence, warning that the file might be truncated and that saving it could result in data loss.  Vim shows plain garbage.

All I can imagine is that the file is broken, and the other editors you try either truncate it, or are more forgiving and leaving the invalid bytes as-is.  As @elextr explained, we can't really do that because we need UTF-8 encoding in the buffer, so need be able to convert to and from it.  With invalid sequences, it wouldn't be possible to restore it.

I'm actually fairly curious as to what the editors you see it working with actually do with those byte, and if they really don't break the file.

Also, there are fairly odd things even in the part fully valid UTF-16.  Is the file really supposed to contain things like `B風e-de-mer` on line 194, `C岡r` on line 326`, `d诡rtement` on line 453, or `Ŵolian` on line 1737 (penultimate line, and the last before the invalid sequence)?

**Comment by b4n** [comment]
Actually I tested SciTE, which is kind enough to open the file without problem, and simply showing plain bytes for the invalid ones, making line 1738 (last one) look like this:
![l1738](https://cloud.githubusercontent.com/assets/793526/18629100/cbc62c9a-7e63-11e6-867e-cc052e495886.png)

It's pretty messy but fair enough.  However, we probably won't do that, because being able to have a fixed encoding in the data we load means that we have to handle encoding conversion in a single place, instead of everywhere something touches the data -- and there are a lot of code that does that, it's and editor after all.
Also, as UTF-8 can represent virtually any textual data (anything inside Unicode), it would only help with invalid input (like here) or binary data (which probably would better be handled with a hex filter).  So I'm afraid it won't happen.
If someone has a nice solution though, I'd love to be proven wrong.

**Comment by zenaan** [comment]
On Mon, Sep 19, 2016 at 03:11:22AM -0700, Colomban Wendling wrote:
> All I can imagine is that the file is broken, and the other editors
> you try either truncate it, or are more forgiving and leaving the
> invalid bytes as-is.

To be fair, the only program I've used to edit this file (from memory)
is MS Word. But it is interesting as you point out. Perhaps there was an
edit some years ago in an editor which did not have encoding awareness.

> As @elextr explained, we can't really do that
> because we need UTF-8 encoding in the buffer, so need be able to
> convert to and from it.  With invalid sequences, it wouldn't be
> possible to restore it.

Very sensible.

Perhaps an editing mode that somehow shows all invalid sequences,
in-situ, and making it clear to the user that the file may already be
corrupted or something, and therefore allowing the user to try to fix
the file. As it is, I'll go to either MS Word on Windows, or Vim on
Linux.

> I'm actually fairly curious as to what the editors you see it working
> with actually do with those byte, and if they really don't break the
> file.

Only opened it. Checking now...

OK:

- Notepad++ shows the invalid sequences as black rectangles with
  numbers, but stops at one line after "Wolian" and does not allow me to
  copy that last line.

- MSO Word has a dozen or so extra entries after that line "Wolian", and
  seems to somehow display most entries correctly, except for the very
  last entry.

- Akelpad also stops at the infamous "Ŵolian" line

- Microsoft Wordpad also stops at "wolian" line


So it seems that either:
- the encoding of this file is something other than the
  proclaimed UTF-16LE

- or the file is simply corrupted and Word does a better job
  of displaying the errors

- or what is proclaimed as UTF-16LE is a bastardized version of
  UTF-16LE,
  - or some other Word-specific encoding pretending to be UTF-16LE

I don't really know what to do now, except to purge all the
"interesting" entries, and go from there. And that will be adequate...


> Also, there are fairly odd things even in the part fully valid UTF-16.
> Is the file really supposed to contain things like `B風e-de-mer` on
> line 194, `C岡r` on line 326`, `d诡rtement` on line 453, or `Ŵolian`
> on line 1737 (penultimate line, and the last before the invalid
> sequence)?

I'm going to assume corruption.

Thank you for your patience and interest.

**Comment by zenaan** [comment]
On Mon, Sep 19, 2016 at 03:30:09AM -0700, Colomban Wendling wrote:
> It's pretty messy but fair enough.  However, we probably won't do
> that, because being able to have a fixed encoding in the data we load
> means that we have to handle encoding conversion in a single place,
> instead of everywhere something touches the data -- and there are a
> lot of code that does that, it's and editor after all.

> Also, as UTF-8 can represent virtually any textual data (anything
> inside Unicode), it would only help with invalid input (like here) or
> binary data (which probably would better be handled with a hex
> filter).  So I'm afraid it won't happen.

> If someone has a nice solution though, I'd love to be proven wrong.

Well, thinking about it, if it was a wanted feature, I would do this as
follows:

- have the raw valid text as a UTF-8 (of course) "linear array"
  (might be a window onto disk for large files, etc)

- indexing layers above this, to quickly identify graphemes, word
  boundaries, line boundaries and any other points of interest, such as:

- "invalid bytes insertion points" along with the corresponding invalid
  byte sequences
  - this way, those parts of the program (most of them) that don't want
    or need to handle invalid bytes, don't have to
  - and you have an easy index to re-insert the invalid sequences on
    saving, or some display/view onto the file that can represent
    invalid bytes
  - and you can offer easy options to the user such as "save without
    invalid bytes" "encode invalid bytes according to some format" etc

Should be easy, and should also be how the program is implemented.

At least, that's how a superior programmer would implement it ;)

See for reference:
https://zenaan.github.io/zen/javadoc/zen/lang/string.html

Regards, and thanks again,

**Comment by elextr** [comment]
> Should be easy, and should also be how the program is implemented.

and how do you keep all this updated and in sync with changes to the buffer as its edited?

> At least, that's how a superior programmer would implement it ;)

Most of the features you describe are handled by the Scintilla editing component which is a separate project at www.scintilla.org and I am sure they would be delighted to hear how a "superior" programmer would re-implement their library. :)

**Comment by zenaan** [comment]
On Mon, Sep 19, 2016 at 04:18:14AM -0700, elextr wrote:
> > Should be easy, and should also be how the program is implemented.
> 
> and how do you keep all this updated and in sync with changes to the
> buffer as its edited?

The layered model - the bottom layer is the text/ raw utf8 stream.

The next layers are the indexing layers for various purposes as and when
needed.

An index is not just an array of "locations" of course since when the
underlying text stream is inserted into or deleted from (in terms of
bytes, not graphemes), then of course the corresponding index in the
upper layer also needs to be updated.

Now because when an index point gets updated it is that all subsequent
index points also need to be updated, a tree structure for the indexes
is required.

And because the underlying layer can change, even it needs to be
represented by a tree structure (various blocks of text are the leaves
of the tree).

This is basic Comp Sci - thus the "easy" bit. The text editor data
structure is really the simplest useful program, and the data structures
needed to handle "large" (anything other than trivial sized) text files,
are well understood, well studied, and highly optimized.


> > At least, that's how a superior programmer would implement it ;)
> 
> Most of the features you describe are handled by the Scintilla editing
> component which is a separate project at www.scintilla.org and I am
> sure they would be delighted to hear how a "superior" programmer would
> re-implement their library. :)

Ah ok. An external dependency.

Well :)

Guess who needs to advise them their data structures are inferior then
hey? :D

Enjoy the ride, and to ease your communications with your upstream
dependency, I suggest being exceptionally blunt with your "inferior
structures" communications, and to top it off, don't stop at the code
but go on to point large accusatory fingers at the personal life choices
of the programmers involved.

That should speed up the re-implementation.

**Comment by b4n** [comment]
Reading the Wikipedia articles make me wonder about so-called "WTF-8", so I played with it and wrote that: https://github.com/b4n/wtf8tools

Converting the file here to WTF-8 makes Geany able to open it just fine (like SciTE does), and it's convertible back to the original UTF-16.
I'm not sure why we accept invalid UTF-8 (well, it's structurally valid, but contains reserved code points), but probably because the tools we use are happy so long as it's structurally valid or something.  Or we don't use the same thing for UTF-8 (GLib) than UTF-16 (iconv through GLib), and GLib is more forgiving.

**Comment by elextr** [comment]
> I'm not sure why we accept invalid UTF-8 (well, it's structurally valid, but contains reserved code points),

From pickyweedia "Not decoding surrogate halves makes it impossible to store invalid UTF-16, such as Windows filenames, as UTF-8. Therefore, detecting these as errors is often not implemented and there are attempts to define this behavior formally (see WTF-8 and CESU below)."

And Glib needs to round trip Windows filenames to/from UTF-8 so its reasonable that it doesn't object.

>  Or we don't use the same thing for UTF-8 (GLib) than UTF-16 (iconv through GLib), and GLib is more forgiving.

Well, for files that Geany thinks are UTF-8 (or is told by the user are UTF-8) we don't do a conversion, just validate, so its different in that way.

**Comment by elextr** [comment]
@b4n, checking the encoding is valid allows premature optimisers to use evil unchecked decoders like [this](https://gist.github.com/elextr/994dcf61b7f009297e229aba7f46f93d) :smile:
