### ISSUE TITLE
Goto column number

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1253]
Please tell me ijf there is an easy way to go to a line at a specific column?  I have read the help regarding ctrl-L but it does not mention such a useful possibility? Thanks!

**Comment by elextr** [comment]
There is not such a thing, probably because, as has been explained before, nobody can agree on what a "column" is, bytes, code points, glyphs, pixels?  The Scintilla definition used for the status bar is "code points, except for tabs. which can be multiple columns to reach a multiple of the tab width".

But that may not match the definition of "column" from another tool, so its only useful for ASCII or non-combining characters Unicode, and then only when the width of tabs is also agreed.
