### ISSUE TITLE
python 3.5.2 Anaconda 4.1.1

### ISSUE THREAD

**Issue by Godsownboy** [geany/geany#1333]
I use geany 2.9 as editor for python 3.5.2 Anaconda 4.1.1 build
Unfortunately, quotation marks are not recognized(both single and double). Therefore I cannot type a string.
I also tested with geany 2.8 but had same issue.
I use windows 7 64

**Comment by elextr** [comment]
There is no Geany version 2.8 or 2.9, assume you mean 1.28 and 1.29.

I suspect your problem is likely the same as #1036?

**Comment by Godsownboy** [comment]
My error (1.28 and 1.29 is correct)
Yes the problem is same as in #1036. I will check it out thanks.
However, geany works perfectly in my other PC (but am not running Anaconda build on this particular PC)

**Comment by Godsownboy** [comment]
Note: my other PC is windows 10 (German keyboard)

**Comment by elextr** [comment]
The Python build has nothing to do with characters you type, as I read #1036 the problem is that if the keyboard mapping doesn't match your locale Windows does not generate the right characters.  Thats nothing we can fix, as #1036 says the problem appears to exist in many applications, even pure microsoft ones.

**Comment by Godsownboy** [comment]
Yes, this is very correct... the windows 7 didn't come with the PC originally.
