### ISSUE TITLE
Geany is not save project state by disable linux or by crash or by "killall -9 geany". 

### ISSUE THREAD

**Issue by runya-v** [geany/geany#1334]
Add saving project state by changed, please.

**Comment by erickpaquin** [comment]
I'm not seeing an "auto-save" feature in the preferences. That would probably help in case crash situations.

**Comment by elextr** [comment]
@erickpaquin autosave plugin?

**Comment by erickpaquin** [comment]
Thanks @elextr , I didn't even think of that. I personally believe this plugin is good enough to handle the situation in this PR. I would close it but that's just me.

**Comment by elextr** [comment]
Actually reading it better, its the session data that the OP is asking about, not necessarily the files themselves.  

Autosave does not save the session, just the files.  

Recently the settings and the session have been split, and settings are definitely saved every change (since that should be only occasionally) but sessions are still only saved at the end IIUC since otherwise every file open and close would also need a write of the session file.  

Autosave cannot save the session on a timer since the capability to save the session is not in the plugin API.

Probably the best solution would be to allow plugins to save session, and have autosave save it along with the files.

**Comment by erickpaquin** [comment]
Sounds good @elextr !

**Comment by eht16** [comment]
Actually we have even more: https://github.com/geany/geany/pull/2114 saves the session when files are opened and closed, merged in 2019 and released with 1.37.

This is probably pretty close to what the OP might have requested (it's hard to guess from the description...).

**Comment by elextr** [comment]
ahh, disconnected spooky action at a distance by goto signals (and similar criticisms of the signal mechanism ;-)

I missed the hookup to the signal to save session, so yeah saves session (only) when files are opened/closed but has an option to turn off IIRC.

So agree it is completed, closed.
