### ISSUE TITLE
Odd coloring for some CSS identifiers

### ISSUE THREAD

**Issue by programmin1** [geany/geany#1342]
When I have some css editing in Geany, and I have some lines that start out:
box-sizing:...
box-shadow: ...
src: ...

those identifiers are colored differently than the other identifiers like margin:, padding:, width: etc. It's like it thinks they are somehow a different type of identifier, or it hasn't been updated to know about the latest CSS features for years.

**Comment by elextr** [comment]
>  or it hasn't been updated to know about the latest CSS features for years.

More likely the latter, see filetypes.css for the lists of keywords, pull requests are welcome.

**Comment by b4n** [comment]
There are different set of keywords: CSS1, CSS2, CSS3, pseudo-classes and pseudo-elements.  In current Geany, `box-sizing` and friends are listed in CSS3 keywords.  They have a different highlighting than CSS1 and 2 keywords, but I guess we did that on purpose.

**Comment by LarsGit223** [comment]
```box-sizing``` is in the list of CSS3 properties and the others mentioned like ```margin```, ```padding``` are CSS1 properties.

CSS1 and CSS2 properties by intention have a different color than CSS3 properties, see this example:

![geany-css-example](https://user-images.githubusercontent.com/9009011/37566353-30ceca78-2ab8-11e8-83a6-6966b62830a9.png)

So the question is answered and the behaviour is as implemented. IMHO this should be closed.

**Comment by chrisgraham** [comment]
I realize this is not a bug, but to me it does deserve some attention for a couple of reasons:
1) A lot of time has passed since the different coloring was implemented, and browsers all support the newer "CSS3" properties. There's no reason to distinguish them and it is unnecessary cognitive noise / confusion.
2) There is no such thing as CSS3. After CSS2 the spec was split up into many different W3C specifications which are developed and versioned independently. So the model of versioning these properties linearly is broken.

**Comment by codebrainz** [comment]
@chrisgraham don't disagree, but it's just a default and Geany does provide at least two ways for users to customize this; either move all the keywords into the same group [here](https://github.com/geany/geany/blob/c88c27e2d22dbff72488d8a57a825830fb833682/data/filedefs/filetypes.css#L29) or edit your colour scheme to style all of the groups the same.
