### ISSUE TITLE
Error with compiling Pascal code on Geany

### ISSUE THREAD

**Issue by synapps16** [geany/geany#1345]
-Geany 1.29 
-GTK 2.24.31, GLib 2.50.2
-macOS Sierra (Version 10.12.2)

After the update to macOS Sierra, all compiling failed.
For Example the following code creat following error:

> program Hello (input, output); 
> 
> begin
>   writeln ('Hello, world.')
> end.

After compiling and "run or view the file":

> /var/folders/wp/8mrx8h3x1bb8k3fq10hr6n400000gn/T/geany_run_script_QZVTSY.sh ; exit;
>   File "hello.py", line 1
>     program Hello (input, output); 
>                 ^
> SyntaxError: invalid syntax
> 
> 
> ------------------
> (program exited with code: 1)
> Press return to continue
> 

Anyone please help?
Thank you

**Comment by codebrainz** [comment]
If the file has the `.py` extension (`hello.py` in your case) it will be detected as a Python script rather than a Pascal file. It's trying to compile the Pascal code using the Python compiler/interpreter.

You should rename the file to use a Pascal file extension like `.pas` and/or change the filetype using `Document->Set Filetype->Programming Languages->Pascal source file`.

**Comment by synapps16** [comment]
I tried with the correct extension .pas
