### ISSUE TITLE
Wrong error message when Directory for seach not exists

### ISSUE THREAD

**Issue by NTMan** [geany/geany#1347]
Example: directory `inside-test` not contain directory `Модули интерфейса`

![22 12 2016 12-29-16-363](https://cloud.githubusercontent.com/assets/200750/21418391/c1246f4e-c842-11e6-8431-97db3225f853.png)

**Comment by elextr** [comment]
The English message when the FIF directory does not exist is:

"Cannot execute tool "grep": Failed to change to the working directory. Check the path setting in preferences"

This makes sense, the command cannot be executed with a non-existent working directory.  If the translation does not match the message above please file an error with the OS since all Geany does is output the system message.  

Clearly also there appears to be a disconnect between the system and Geany about that locale you are in since the system message is in a different language to the Geany message parts.  You may need to set some environment settings to make them agree.

**Comment by NTMan** [comment]
This message is very confuse two things:
1) Cannot execute tool "grep" - means problem with launching grep itself. 
2) Check the path setting in preferences - means problem with path to grep executable in Geany settings.

More correct in this case would message `"C:\Sources\inside-pre-test\Модули интерфейса" not exists`

**Comment by elextr** [comment]
> Cannot execute tool "grep" - means problem with launching grep itself.

Well that is actually what failed, the Glib call to execute the grep command, no command can be launched in a non-existent working directory, so that system call fails.

> Check the path setting in preferences - means problem with path to grep executable in Geany settings.

Yes probably could be clearer that this is just guidance or advice that "This may be due to the path of the grep executable being wrong in Geany settings".  I guess at one time in the past this was a common cause of problems so the guidance was added.

> More correct in this case would message "C:\Sources\inside-pre-test\Модули интерфейса" not exists

Geany gets an error code `G_SPAWN_ERROR_CHDIR` back from [Glib](https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html#GSpawnError),  so "Failed to change to the working directory" is a reasonable message.  The glib error code it doesn't tell why it failed to change the directory.

**Comment by hartmut27** [comment]
In Geany 1.32 / build 2018-01-08 it says:

> execute grep tool "grep": Failed to change to the working directory. Check the path settings in preferences.

But this failure message is wrong since not the preferences settings path is wrong but the entered directory to find in files for. This confusing.

**Comment by codebrainz** [comment]
Closing due to age a no more comments.

@NTMan feel free to re-open if you want to discuss further, or even better provide a pull request to cleanup the messages.
