### ISSUE TITLE
The print function is not concatenating strings correctly for Python

### ISSUE THREAD

**Issue by HuongD97** [geany/geany#1349]
When I get the user input and try to print it concatenated with other strings, the statement is printed out with the added string at the end showing up at the very beginning and cutting off words at the beginning. When I wrote the same exact code in IDLE, the print statement is perfectly fine.

![image](https://cloud.githubusercontent.com/assets/21274031/21480617/c65648c4-cb2c-11e6-9095-424ef9f6a822.png)

**Comment by elextr** [comment]
Doesn't happen on Linux, must be a Windows specific problem.

It looks like the `usercar` input includes a carriage return after "corolla" making the `.` overwrite the first character position.  Might be something related to what the Python 3 universal newlines think is the correct end of line in a windows terminal, taking the line feed as end of line, and leaving the carriage return in the string.

Try running your program in a windows terminal outside of Geany and see what happens.

**Comment by HuongD97** [comment]
How do I run the program through a non-Geany windows terminal?

**Comment by eht16** [comment]
I can't reproduce the issue, neither on Windows nor on Linux (Windows: Python 3.6; Linux: Python 3.5).

I support @elextr's observation about the newlines but the docs for input() tell that trailing newlines are stripped (https://docs.python.org/3/library/functions.html#input).
Not sure what's happening on your system but since it happens on a usual command prompt as well on your system, it seems unrelated to Geany.
