### ISSUE TITLE
Separate config file for persistent config

### ISSUE THREAD

**Issue by aklt** [geany/geany#1392]
Currently geany updates geany.conf with info about window position and
geometry.  These vary across different machines and cause diffs that
are meaningless.

**Comment by elextr** [comment]
The separation of session and configuration information has been discussed, but no concrete conclusion has been reached.

To solve your different machine situation you could use different configs for each selecting via the `-c` option.

**Comment by aklt** [comment]
Thanks, I will go for that option for now.

In  my opinion it is the best to separate these two types of information.  Is there somewhere
where I can follow this discussion?

**Comment by elextr** [comment]
I couldn't find it on an issue, but my issue search is notoriously bad, however I suspect it was on the mailing list.

I personally agree that session and config information should be separated, but IIRC one problem is issues around handling projects similarly (since projects also save session info).  But there could be other unresolved points that I don't remember.

Also there is a suggestion to use gsettings instead, see #1257

**Comment by aklt** [comment]
Thanks for the pointers.  I am not a hardcore geany user, but It is a nice project.

I'll follow the discussion :)

**Comment by kugel-** [comment]
Window position and geometry will be stored outside geany.conf with 1.39/2.0 so consider this fixed.
