### ISSUE TITLE
Find Previous disabled

### ISSUE THREAD

**Issue by oonet** [geany/geany#1494]
Find dialog shows "Next" enabled but "Previous" disabled.

Xubuntu 17.10 with latest version of Geany from repository (1.29)

**Comment by elextr** [comment]
Doesn't happen for me with latest Geany.  Perhaps you need to give more information about what you are doing.

**Comment by oonet** [comment]
Open new document. Select "Find" from "Search" menu (ctrl+f). Next is enabled, Previous is disabled.

**Comment by elextr** [comment]
Don't have Xubuntu, but doesn't happen here, what versions of GTK and Glib is it using?  Can you try the latest version of Geany (1.30.1) from the [PPA](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa).

**Comment by codebrainz** [comment]
It happens here if you enable regular expression searching, which makes sense since it probably can't match expressions backwards.

**Comment by oonet** [comment]
Good catch! Previous doesn't work with regular expressions enabled, but does work with regular expressions disabled. As you say, makes sense. Fixed!

**Comment by dicktyr** [comment]
I'm surprised this has remained broken for so long, and further surprised that the issue was closed (at least twice)! Navigating to the previous regex match remains broken in the latest Geany (1.32) and, unfortunately, this appears to be "[by design]" (the same bug was reported in 2011)!

**In any case, Geany is the only text editor I've used which does not support navigating to the previous regex match.**

[by design]: https://sourceforge.net/p/geany/bugs/698/

**Comment by elextr** [comment]
@dicktyr its not by design, its because the regular expression library does not support searching backwards so it would require finding all matches forwards from the start of the document and picking the one before the current position and __nobody has written the code__.  Pull requests that add the facility are welcome, attempts to shame volunteer contributors are not.

**Comment by dicktyr** [comment]
> nobody has written the code

hence it seems quite reasonable that this issue should remain open until then
and potential writers may appreciate this: https://github.com/google/re2/wiki/WhyRE2

(@elextr by the way, I made no attempt to shame anybody
but rather to bring attention to some simple facts)

**Comment by elextr** [comment]
@dicktyr the OP closed the issue, not any of the Geany contributors, thats their decision.
