### ISSUE TITLE
[Compile-Time Problem] Can not compile geany 1.30

### ISSUE THREAD

**Issue by shevegen** [geany/geany#1516]
Error is:

 /usr/bin/ginstall -c -m 644 SciLexer.h Scintilla.h Scintilla.iface ScintillaWidget.h Sci_Position.h '/Programs/Geany/1.30/include/geany/scintilla/'
make[3]: Leaving directory '/Depot/Temp/geany-1.30/scintilla/include'
make[2]: Leaving directory '/Depot/Temp/geany-1.30/scintilla/include'
make[2]: Entering directory '/Depot/Temp/geany-1.30/scintilla'
make[3]: Entering directory '/Depot/Temp/geany-1.30/scintilla'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/Depot/Temp/geany-1.30/scintilla'
make[2]: Leaving directory '/Depot/Temp/geany-1.30/scintilla'
make[1]: Leaving directory '/Depot/Temp/geany-1.30/scintilla'
Making install in src
make[1]: Entering directory '/Depot/Temp/geany-1.30/src'
Making install in tagmanager
make[2]: Entering directory '/Depot/Temp/geany-1.30/src/tagmanager'
make[3]: Entering directory '/Depot/Temp/geany-1.30/src/tagmanager'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/Programs/Geany/1.30/include/geany/tagmanager'
 /usr/bin/ginstall -c -m 644 tm_source_file.h tm_tag.h tm_workspace.h tm_parser.h '/Programs/Geany/1.30/include/geany/tagmanager'
make[3]: Leaving directory '/Depot/Temp/geany-1.30/src/tagmanager'
make[2]: Leaving directory '/Depot/Temp/geany-1.30/src/tagmanager'
make[2]: Entering directory '/Depot/Temp/geany-1.30/src'
  CCLD     geany
./.libs/libgeany.so: undefined reference to `Editor::RangeText[abi:cxx11](int, int) const'
./.libs/libgeany.so: undefined reference to `Document::TransformLineEnds[abi:cxx11](char const*, unsigned int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:758: geany] Error 1
make[2]: Leaving directory '/Depot/Temp/geany-1.30/src'
make[1]: *** [Makefile:1214: install-recursive] Error 1
make[1]: Leaving directory '/Depot/Temp/geany-1.30/src'
make: *** [Makefile:595: install-recursive] Error 1

My host system is:

    Operating System:                GNU/Linux                                           
    Os Bit Type:                     i686                                                
    CPU Model:                       Intel(R) Celeron(R) CPU G1630 @ 2.80GHz, 2 cores    
    CFLAGS in use:                   -O2 -fPIC -fno-strict-overflow -Wno-error           
    RAM:                             7977364 kB RAM (7790.4 MB) (7.6 Gig)                
    Screen Resolution:               1920x1080                                           
    Gcc Version:                     7.1.0                                               
    Glibc Version:                   2.23                                                
    Kernel Version:                  4.4.14                                              
    Ruby Version:                    2.4.1p111 (2017-03-22 revision 58053) [i686-linux]  
    Rubygems Version:                2.6.11                                              
    Rubygem Installation Directory:  /Programs/Ruby/2.4.1/lib/ruby/gems/2.4.0/           

Not sure what Editor::RangeText is ... may this be due to GCC version 7.x? I remember having  had compiled geany before... but since then I changed my host system a bit. hmm.

Either way, if this is a valid error, could the error message be made better? Something indicitave of the error. I can change everything here on my system but I am not quite sure about the error right now. Thanks for reading anyway!

**Comment by elextr** [comment]
It may be due to your bleeding edge version of gcc, AFAIK nobody has tested compiling Geany with gcc-7.

The errors come from the [Scintilla](http://www.scintilla.org/) 3 editing component we use, which is C++ but uses only limited C++11 features to be able to support gcc 4.something.  The next version of Scintilla 3 requires slightly more recent C++ features and is waiting for testing in #1504.  Maybe you could try that.

Scintilla 4 is in development and is intended to target gcc 7 (and use C++17 features) but its not yet released and may be API incompatible so it may be a while before it can be used by Geany (we will see when its released and Geany devs have gcc 7 available, we tend to be stuck in the mud stable distro users :).

As for changing the error message, sorry thats a question you need to ask of the gcc developers, its not something we control, but it probably can't be improved much, it lists the missing functions and really can't do much else.

**Comment by shevegen** [comment]
Thank you for the information!

I think there was another error. I re-compiled some other components, including gdk-pixbuf (not sure if this has had an effect).

I just compiled geany again and it works fine (also starts fine).

Unfortunately I have not had captured the specific environment. Since I do these things via scripts, I can eventually modify my scripts to also capture all that information when something goes awry, and then can make another snapshot when things work fine.

I also realized that I had several gcc versions installed, so I could have tested with another gcc - I guess it was not related to gcc, it only was my guess because I remember that I could compile geany just fine some months ago (gcc 7 probably did not come out that long ago so I was probably not using it yet but I can state that gcc works just fine).

I'll have a look at the new geany code a bit later - finals are coming up and I am actually not supposed to spen too much time at the computer when there are books to be studied :D But I'll come back to this eventually, thank you!

**Comment by b4n** [comment]
I'm really not sure, but if by any chance you build the C++ files with one version of GCC and linked with another it's not very surprising, because of the possibly different default ABIs (like here it specifies `abi:cxx11`, which likely isn't the default for GCC 4/5, and possibly 6, not sure.

Anyway, unless you can find a reliable reproduction scenario I'm afraid there's not much we can do.

**Comment by codebrainz** [comment]
Shouldn't Geany be linked with G++? It's tough to tell without `make V=1` but isn't `CCLD` the plain C compiler driving the linking?

**Comment by shevegen** [comment]
b4n this may be a possibility but I am not sure, reason being that I normally have no gcc variant at /usr prefix anymore (neither anything left at /usr/lib) and all my gcc versions residing at /Programs/Gcc/VersionHere - this is a setup similar to GoboLinux. So to change gcc versions I just change the symlink at /Programs/Gcc/Current to the current version, then re-symlink everything (via a script).

I can perhaps use "make V=1" too as codebrainz suggested but actually what this taught me, is that I actually need to capture the full environment that I have on my system, the very moment I try to build/compile comething. I added this on my todo list for my ruby scripts to do so and sooner or later I will have added support for this, then I can provide more information whenever I may run into similar problems. I most definitely did something, without even thinking :D and then it suddenly worked... next time I'll try to provide as much information as possible too on my host systems.

**Comment by b4n** [comment]
@codebrainz good thinking, but "apparently" only libgeany is linked with CXXLD, geany itself uses CCLD (which somewhat makes sense as the geany part is super small and doesn't use any C++.  And this always worked for me and everyone else (apparently).

@shevegen possibly you changed GCC version without triggering a whole rebuild?  If for any reason changing the symlink didn't trigger a rebuild, but the generated objects weren't compatible (e.g. because of the C++ ABI), then it could explain why it failed, and why cleaning or rebuilding some other component that lead to a rebuild would have fixed it.  That's wild speculations, but that's the best I can do so far.
