### ISSUE TITLE
no auto-reload opened file view if change it's encoding

### ISSUE THREAD

**Issue by andysendo** [geany/geany#1529]
Hi, i am a newly geany user.

when i open a plain/txt file that is gbk encoding from file-manager, always show measy characters due to geany default using utf-8. 

if i change encoding by the menu 'doc - encodeing - lang ...', geany do not auto-reload the file with the changed encoding. kate editor can do that way. 

i know geany how to correctly open non-utf8 txt file, but auto reload when change encoding makes user much simpler. i hope geany have the function. 

Regards.

**Comment by vfaronov** [comment]
Instead of *Document* → *Set Encoding*, use *File → Reload As*.

**Comment by andysendo** [comment]
yes, manual reload works. but auto reload is better.

**Comment by elextr** [comment]
@andysendo document->set encoding sets the encoding to save the document in, if it reloaded then there would be no way to change the encoding of the document as noted in the manual.

**Comment by andysendo** [comment]
"if it reloaded then there would be no way to change the encoding of the document as noted in the manual."

not understand what's that mean.

as my experience, open non-utf8 plain txt file, change encoding, editor auto reload, it's simple, naturally actions. 

if i wan to change the orig file encoding, such as gbk->utf8 whaterver, i just create new empty file with utf8 then crtl+c/v, or by enconv/iconv tool.

**Comment by elextr** [comment]
@andysendo clearly the people who made the Geany UI have a different usage and workflow than yours.  

It was worth them adding the capability of modifying the encoding *inside* Geany and mentioning it in the manual.

@vfaronov indicated the intended way to use Geany to reload an already open file with different encoding, and as that also sets the document encoding it makes no difference in terms of UI actions, just "reload as" instead of "set encoding".  Neither is "better", they are just different ways of achieving the same thing.

**Comment by andysendo** [comment]
ok, thanks for help, guys.

**Comment by elextr** [comment]
Closed works as intended
