### ISSUE TITLE
macos sierra: geany 1.31 does not start 

### ISSUE THREAD

**Issue by silberzwiebel** [geany/geany#1555]
it blinks in the dock for a very long time (suggesting to start), then the light is permanently on (meaning: program is running), but it doesn't react and I never see a GUI.

It starts properly within seconds but with broken icons when I manually start `/Applications/Geany.app/Contents/MacOS/geany-bin`

Installed using the .dmg file from the official homepage.

Here is (I suppose) relevant log output:
```
> tail /var/log/system.log
Jul 25 13:39:51 wilde com.apple.xpc.launchd[1] (com.apple.quicklook[1633]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
```

**Comment by elextr** [comment]
@techee catch :)

**Comment by techee** [comment]
@silberzwiebel A few questions. What Geany version are you using? What happens when you start Geany from the command-line - i.e. when you open the terminal app and enter

```
/Applications/Geany.app/Contents/MacOS/geany
```

Does it print some useful information? You might also try to start Geany without plugins by

```
/Applications/Geany.app/Contents/MacOS/geany -p
```

or removing/renaming Geany configuration directory in case it got corrupted by e.g.

```
mv .config/geany .config/geany-old
```

**Comment by techee** [comment]
Also the message you mentioned doesn't seem to be related to Geany in any way from what I an see.

**Comment by techee** [comment]
Ignore the thing about the Geany version number - you mention it in the title that it's 1.31. Does some older version, e.g. 1.30 work for you?

**Comment by silberzwiebel** [comment]
version 1.30.1 works fine.

```
$> /Applications/Geany.app/Contents/MacOS/geany

(geany-bin:3789): GLib-GObject-WARNING **: cannot register existing type 'VteTerminal'

(geany-bin:3789): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(geany-bin:3789): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
and nothing more happens, no more errors but also no GUI ...

Without plugins, i.e.,
```
 /Applications/Geany.app/Contents/MacOS/geany -p
```
works, it opens up directly, but (surprise ;) ) without the plugins.

Renaming the plugins folder did work. Now I get a working geany 1.31. Not sure how much preferences I've made, but I guess it will be fine and I can re-adjust my preferences ...

Feel free to close this bug if you don't want to find the root cause of this issue. I reckon it would be better to show an appropriate error message like `setting/plugin blabla is deprecated and disabled, you have to use blabla` instead of just not opening but I understand that it might be not so easy to find out what was actually going wrong.

Thanks!

**Comment by elextr** [comment]
@silberzwiebel since Geany seems to run without plugins, you could try enabling plugins one at a time to find out which is the problem.

Most plugins are not developed by the Geany team directly, each one has its own developer, and Geany itself has no knowledge of what plugins do and so does not know if they are working or not and so cannot warn you about anything to do with them.

The removal of settings was probably only intended if the `geany -p` still failed.  If Geany fails to start again when enabling plugins to find which one hangs Geany on startup, just edit `.config/geany/geany.conf` (with another editor since you need Geany closed) and remove the line starting `activated_plugins=` and that will disable all plugins so you can start Geany again.

If you find its a plugin please report it and if its not one of ours we will probably ask you to report it to Geany-plugins directly so the developer can contact you for more info if needed.

**Comment by silberzwiebel** [comment]
okay, I tested this with my old config folder and found that the plugin `Debugger` (path `/Applications/Geany.app/Contents/Resources/lib/geany/debugger.so`) is the one that causes the problem. Enabling this from a running geany instance results in a non-responsive GUI and the same error messages as above.

**Comment by elextr** [comment]
@silberzwiebel could you report the problem on the Geany-plugins project [issues](https://github.com/geany/geany-plugins/issues) which is where that plugin lives.

**Comment by techee** [comment]
@silberzwiebel Can reproduce now, thanks.

@elextr I think it's more related to making Geany OS X bundle I think - the plugin seems to load fine when I run Geany without bundle but hangs when run from bundle. In fact, 3 plugins are affected as far as I can tell:

Debugger
Scoped debugger
Multiterm

Interestingly everything runs fine with Geany 1.30 bundle - I'll investigate what could be wrong.

**Comment by techee** [comment]
This problem seems to be related to VTE - all the mentioned plugins use VTE and it seems that when these plugins are loaded, a second instance of VTE starts loading and the whole program freezes. All the 3 plugins run fine when Geany is started without VTE (geany -t).

The interesting thing is that these plugins load fine in the Geany 1.30 bundle. I tried to grep the shared libraries of the plugins for VTE symbols and in the 1.31 bundle the 3 plugins contain VTE symbols; however, these symbols are missing in the 1.30 bundle. I'm not aware of any change in the build scripts and don't really know what's going on here.

**Comment by techee** [comment]
So this turns out to be a bug in the current version of gtk-mac-bundler, see

https://bugzilla.gnome.org/show_bug.cgi?id=788408

If the problem isn't fixed before the next Geany release, I'll just use an older version of the bundler so the next Geany macOS release should have this fixed.
