### ISSUE TITLE
Toggle Line Commentation makes too much slashes

### ISSUE THREAD

**Issue by ibinshoid** [geany/geany#1558]
edit->format->Toggle Line Commentation makes //// instead of // on c and vala files
edit->format->Comment Line(s) works fine.

**Comment by elextr** [comment]
I get "//~", have you set `Menu->Edit->Preferences->editor->features->Comment toggle marker` to "//"?

**Comment by ibinshoid** [comment]
Yes there is a // but when i remove it comments are set right.
It seems like geany set this string additional to the one set in the filetype descryption in /usr/share/geany/filedefs/*

**Comment by elextr** [comment]
Correct.  It distinguishes comments set by the command with those set by the user.  The command does not remove comments set by the user since that would not allow selecting a block of code that included comment lines and simply having it commented out in a reversible manner.  It is best to set it to something that does not usually occur in your files, hence the default `~`.
