### ISSUE TITLE
Activate local plugin from configuration file

### ISSUE THREAD

**Issue by fjvico** [geany/geany#1562]
`togglebars` plugin is to be made available for Geany in an application that installs itself from a deb file and copies `togglebars.py` in the `~/.config/geany/plugins/` directory in run time. So, the plugin is intended to be active when Geany is launched by the application, meaning that it should be included in `~/.config/geany/geany.conf` in the form:
`active_plugins=/home/<user>/.config/geany/plugins/togglebars.py;`

But the name of the user is not known at the time of installation. Alternative solutions like 
`active_plugins=togglebars.py;`
`active_plugins=plugins/togglebars.py;`
`active_plugins=~/.config/geany/plugins/togglebars.py;`
don't work. How can this file be included, independently of the user name?

**Comment by elextr** [comment]
Installation != enabling, its rude for an installer to force enabling on the user.

The user should enable geanypy and the plugin using the GUI.

Anyhow, the installer must be running as the user or `~` would not work to find the configuration directory, so it does know the user at install time.

**Comment by codebrainz** [comment]
On 2017-07-26 02:14 PM, fjvico wrote:
> `togglebars` plugin is to be made available for Geany in an application that install from a deb file and copies `togglebars.py` in the `~/.config/geany/` 

I'm not sure if it's outright banned/impossible, but it's highly unusual 
for a .deb package to install stuff into user's home directory. I think 
because it probably needs the apt-get lock which requires root, and then 
it would put it in /root/.config/geany/... instead, I presume, or at 
best make the file unmodifiable by the user who's home directory it got 
plopped into.

directory. So, the plugin is intended to be active when Geany is 
launched by the application, meaning that it should be included in 
`~/.config/geany/geany.conf` in the form:
> `active_plugins=/home/<user>/.config/geany/plugins/togglebars.py;`
> But the name of the user is not known at the time of installation. Alternative solutions like
> `active_plugins=~/.config/geany/plugins/togglebars.py;`
> `active_plugins=$HOME/.config/geany/plugins/togglebars.py;`
> don't work. How can it be included this file independently of the user name?
> 
> Also, this plugin demands `geanypy`, which is placed in:
> `active_plugins=/usr/lib/x86_64-linux-gnu/geany/geanypy.so;`
> what depends on the architecture. Does this plugin need to be precompiled? Can it be placed somewhere else?
> 
> 

I would recommend installing the `togglebars.py` plugin into the 
system-wide plugins dir `$prefix/lib/geany` (if I remember correctly) 
and making the package depend on `geany-plugin-py` so it gets installed 
as well.

Also as elextr mentioned, it's probably not a good idea to force 
geanypy/togglebars.py to be loaded automatically either, not only 
because you can't know what config directory to actually modify (I have 
several Geany's each using separate config dirs besides the default), 
but also because you could mess up their config (imagine Geany's already 
open, it will clobber your changes), or Geany could change the internal 
format/fields used in the config file at any time.

Regards,
Matthew Brush

**Comment by fjvico** [comment]
@elextr @codebrainz fully understand your point, it's the user who has to enable what has been installed. But this is a particular situation, where Geany is the editor of a programming environment for children which is to be used at schools, meaning that after a fresh installation by the admin, the (normally) computer-illiterate teacher is not supposed to follow instructions to activate plugins, and the child is not intended to have access to such a thing (actually, that's the reason to use `togglebars`: to keep the menu bar away from children's' curiosity). So, precisely like `savewhenoutoffocus` is enabled, I need this plugin enabled by default.
The problem above has been fixed with a `find` and a `sed` commands that updates `geany.conf`, but now I need help to make it active by default. By now, when the program is run for the first time (after been installed), it copies `geany.conf` in a directory (from where Geany is to be configured), and it contains the line:
`active_plugins=/usr/lib/x86_64-linux-gnu/geany/geanypy.so;/usr/lib/x86_64-linux-gnu/geany/saveactions.so;/home/fjv/.toolbox//util/geany/plugins/togglebars.py;´
- `togglebars.pyc` is built by `python -m compileall togglebars.py`, placing the py file in the same directory plus `plugins` folder, and
- `togglebars.on` is just copied in the same `plubins` folder.
When the environment is run, it launces Geany, it is configured from this directory, and I see `GeanyPy` enabled, and `Toogle bars` disabled.
What is left in the process to have it enabled by default?

**Comment by fjvico** [comment]
Solved bypassing the confirmation process: `self.confirmed = True`.
