### ISSUE TITLE
geany cannot restore previous window size (reopen after maximized)

### ISSUE THREAD

**Issue by llpub** [geany/geany#1593]
How to reproduce:
(geany1.24 - 1.30, with gtk2 from xfce4.10 or 4.12, gnome3.14)

1. make sure "Save window position and geometry" is checked in geany preference;
2. resize geany window to any size (except nearly maximized size), here call this size as sizeA;
3. maximize geany window;
4. close && open geany, geany window would be nearly maximized size (but not truely maximized).

Here geany window should be sizeA (or be maximized but can be resize to sizeA by clicking Unmaximize button). It seems that geany lost sizeA info after maximized. 
Same problems can be observed in some gtk2 software (e.g. sublime text). However, some other gtk2 apps can restore to window sizeA even after a restart from maximized status (e.g. firefox gtk2 version).
Thanks in advance.

**Comment by elextr** [comment]
Resizing, maximising, minimising and restoring are window manager functions, not application functions.  Geany is not informed of their happening, all it can do is read the state at shutdown and try to restore it at startup if the WM allows.  So Geany is not aware of the resize to sizeA so it can't remember it, it just gets the maximised size when it reads it at shutdown.

Applications like firefox probably interface to the desktop via dbus and will get informed of the resizes and maximises and other session functions that way.  But Geany does not do dbus interfacing because its not standardised across different systems (especially windows).  High resource projects like Firefox can afford to support multiple such systems, but Geany cannot, but may add it if a portable library becomes available.

> close && open geany, geany window would be nearly maximized size (but not truely maximized).

Opens maximised here on a cinnamon desktop, after you close Geany look at the `geometry=` setting in `~/config/geany/geany.conf` and check that the last value is `1` which means maximised.  If its not, then the desktop is not telling Geany its maximised.

**Comment by llpub** [comment]
Thank you, now I understand this.

**Comment by codebrainz** [comment]
> Resizing, maximising, minimising and restoring are window manager functions, not application functions. Geany is not informed of their happening, ...

Naw, [MMOP](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-window-state-event)
