### ISSUE TITLE
delete hard-coded keybinding?

### ISSUE THREAD

**Issue by paul1149** [geany/geany#1622]
Hi,
It seems that geany has some keybindings coded in and inaccessible to the user? I work on text files with thousands of lines, and one keybinding that gets me into trouble is _Ctrl-Up/Down_. I occasionally hit it by accident, and it takes me to the top or bottom of the file, from which finding my way back to the line that was in focus is a chore.

I have no need of this shortcut, as it only duplicates the standard Ctrl-Home/End functionality. I don't see the binding listed either in Settings or the keybindings.conf file, so I guess it's hard-coded in? Is there any way to neutralize these shortcuts?
Thanks.

**Comment by elextr** [comment]
The ctrl-home and ctrl-end keybindings are provided by the Scintilla editing widget that Geany uses and are documented [here](http://www.geany.org/manual/current/index.html#keyboard-commands)

Since they are not provided by Geany they can't be undefined, but since Geany keybindings override Scintilla ones, you can define them to something in Geany that annoys you less, maybe an undefined custom command.

**Comment by paul1149** [comment]
Thank you! Much better.

I see the rationale for the two commands, they actually are "go to previous/next paragraph", but since the docs I edit don't have paragraphs, they take me to the beginning or end.

I remapped them to merely switch the location of the file's tab on the tab bar.

Thanks for the speedy and helpful answer!
BW.
