### ISSUE TITLE
Unexpected behavior from UNDO when using seach-replace -> in session

### ISSUE THREAD

**Issue by andy5995** [geany/geany#1631]
When changing the text layout of seven documents, I was using search and replace. I used the feature to make the changes to all documents _in session_.

It was in that situation where I found that _undo_ only undid changes to the active document, not to my last change of replacing text in all the documents _in session_.

**Comment by elextr** [comment]
There is no global undo stack.  Each file has its own undo stack since most editing makes changes to one file and not any of the others.  When you do a session change each file has the change made independently and the undo is saved to its stack.  Of course files where nothing was changed have no undo, so globally undoing the last undo entry is a "bad thing".

In general changing files other than the current one is a "bad thing" except when explicitly instructed by the user (eg replace in session).
