### ISSUE TITLE
Multi-edit mode feature or plugin?

### ISSUE THREAD

**Issue by LeeteqXV** [geany/geany#1656]
Is there a plugin or function that enable multiple edit points/cursors in the same file?
("Multi-edit-mode" as one of the plugins for the gedit editor provides?)

In large files, I would like to set maaany edit points that would get their insertion point highlighted with the color setting of the "current_line", so that we can easier find back many edit places. Especially practical in two-column/split window mode.

(I am checking out this exciting editor right now. Looks very promising.)

**Comment by elextr** [comment]
No Geany does not support multiple selection/insertion points.  It is a capability of the underlying editor, widget Scintilla, but cannot be added by a plugin because none of the code in the main program supports more than one selection/insert point so it would only work with some functions and not others.

**Comment by LeeteqXV** [comment]
Ok, I just asked about this over at the Scintilla queue:
https://sourceforge.net/p/scintilla/feature-requests/1202/

**Comment by elextr** [comment]
@LeeteqXV it is already in Scintilla, I said above "It is a capability of the underlying editor, widget Scintilla".

**Comment by LeeteqXV** [comment]
I am just trying to pinpoint the right place to address this so that it becomes possible with such a function in Geany.

**Comment by elextr** [comment]
Work on multiple insertion points is ongoing at #1141.

Closed as duplicate.
