### ISSUE TITLE
Feature suggestion: Color picker/translator

### ISSUE THREAD

**Issue by BarbzYHOOL** [geany/geany#1669]
When you write CSS, html or maybe other markup languages, you often need to type colors. A very nice feature would be to have the same thing we got in modern browsers (like firefox) when you inspect an element : 
- next to the RGB/RGBA color code there is a big dot representing the color (very useful)
- if you click on it, you have a color picker to change it and it changes the color code accordingly

Actually we are forced to open a color picker just to see what is the color code, so I open Gimp which is heavy and it's quite unpractical

Thank you :)

**Comment by b4n** [comment]
Geany has a builtin color picker (*Tools → Color Chooser*) that will also display the selected color.  With CSS you should be able to just double-click (or otherwise word-select) on the color, and invoke the color picker (possibly with a keybinding you can configure) both for displaying and picking a color.

For the additional fancyness you're suggesting, it could likely be implemented by a plugin with more or less effort (e.g. displaying a popup when hovering a color will probably be easier than displaying a colorful dot, as I'm not sure Scintilla, the editing component Geany uses, have that ability builtin).

**Comment by elextr** [comment]
The colour chooser is also available from a toolbar button.

**Comment by LarsGit223** [comment]
@BarbzYHOOL: did the answers from @elextr and @b4n help you? Can this be closed?

**Comment by BarbzYHOOL** [comment]
Well yes but it's still really unpractical so I don't use it...

**Comment by LarsGit223** [comment]
@b4n wrote:

> For the additional fancyness you're suggesting, it could likely be implemented by a plugin with more or less effort (e.g. displaying a popup when hovering a color will probably be easier than displaying a colorful dot, as I'm not sure Scintilla, the editing component Geany uses, have that ability builtin).

Maybe you should place a feature request/enhancement at geany plugins also.

**Comment by LarsGit223** [comment]
This can be closed as the feature is released in geany-plugins 1.33 (plugin Addons).

**Comment by BarbzYHOOL** [comment]
o_0 nice
