### ISSUE TITLE
Message Window notebook tabs wrong size

### ISSUE THREAD

**Issue by twmccart** [geany/geany#1723]
In the Message Window is a selector that scrolls through "Status" "Compiler" "Messages" "Scribble" "Terminal" "Tasks". In Geany 1.32 for Fedora 27, the text size/spacing of this scroller is too large, and apparently not changeable. When run from the command line, a GTK error is produced, making me suspect that this is a GTK-related bug. Is there any chance of it being fixed on Geany's end?

Example error:
(geany:21820): Gtk-WARNING **: Allocating size to GtkScrollbar 0x559bda5fd300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

More errors are generated if menus are opened within Geany.

**Comment by codebrainz** [comment]
I think this is a regression in GTK+ 3 where the notebook tabs are massive and full-width. I'm pretty sure you could tweak it in an application-specific CSS file.

The mentioned warning messages are [due to a bug (fix) in GTK+ as well](https://bugzilla.gnome.org/show_bug.cgi?id=773814). The other warnings from menus are due to some weirdness in GdkPixbuf IIRC.
