### ISSUE TITLE
Multiple window headaches

### ISSUE THREAD

**Issue by JoshDreamland** [geany/geany#1727]
Hi there,

A minor problem that comes up a lot when I use Geany is wanting to open additional documents in a particular window. Opening a file with Geany via command line will open it in the first available Geany process—ostensibly the first process to try to create the socket file. This instance's editor window usually isn't the one I want and is typically in another workspace. As a result, my "main" Geany window has over thirty open documents in it right now.

I can often mitigate this problem using the `--new-instance` flag to just pop open a new editor, but this leads to lots of Geany windows, quickly.

It would be good if Geany could organize its sockets so that more than the first open instance could be communicated with. Ideally, the most recently focused editor would accept document open commands.

If that isn't an option, I often find myself poking around in the Geany Terminal for files I want to edit (usually with `grep` or `find`). Once I have a list, though, I have no good way of opening those documents. Simply calling ``` geany `find . -name 'foo.bar'` ``` will open them in the first process. What would be cool is if I could type `open` or `edit` instead, to open them in the current instance.

I think the terminal feature might actually be more difficult to implement than proper IPC. I've considered implementing it myself, but didn't want to just drop that feature on you as a big pull request. My thoughts:
- We could tackle multiple-instance communication by allowing successive instances to listen on the existing socket, or just having them create sequential new sockets. I prefer the former.
- However we handle that, we will want to add a `socket_get_focus_time` (or similar) to look up how recently the editor was used.
  - If we put multiple listeners on a socket, we'll need to tag their responses with a UID (eg, their PID).
    - In this case, I'd probably just call the routine something like `socket_identify_instances`.
  - Tracking the focus timestamp is as simple as updating a global in each process's `set-focus` or `notify::is-topmost` event.
- Once we've iterated all sockets or all responses, we would request the one with the latest (highest) timestamp to open the given files.
  - Again, if we had multiple instance on one socket, we'd need to tag the request with a PID or other UID from the timestamp call.

I believe this change isn't all that complicated, and might be interested in making it if the team doesn't have any other plans. Let me know.

**Comment by elextr** [comment]
> It would be good if Geany could organize its sockets so that more than the first open instance could be communicated with. 

See --socket-file or -c [here](https://www.geany.org/manual/current/index.html#command-line-options)

>  Ideally, the most recently focused editor would accept document open commands.

Needs some system wide shared global thing that records who was the last Geany to be focussed, but I doubt it will be very useful on systems with "focus follows mouse" since it would be too easy to change which Geany that was.

> What would be cool is if I could type open or edit instead, to open them in the current instance.

See above.  You can define your own `open` or `edit` aliases since the terminal has a shell running inside it.  (Note Geany does not see anything that you type in the terminal other than a few shortcut keys, it all goes directly to the shell)

> We could tackle multiple-instance communication by allowing successive instances to listen on the existing socket, or just having them create sequential new sockets. I prefer the former.

Unix sockets allow multiple listeners, but only one of them can read a message, so its the one taht wins the race that gets it.  You need a shared server (the "global thing" referred to above) that communicates wit all the instances.  IMO this is all becoming too complex just to automate which Geany gets an open request, its better to specify it explicitly as above.

> I believe this change isn't all that complicated, and might be interested in making it if the team doesn't have any other plans. Let me know.

Other than the fundamental flaw noted above :)

**Comment by elextr** [comment]
You could however always write a plugin to manage opening files in multiple Geany instances in any way you like and not use the Geany sockets.  It could use whatever IPC it wanted.

**Comment by elextr** [comment]
Closed as out of scope for Geany

**Comment by lar3ry** [comment]
@JoshDreamland 
I too have the same problem with Geany, and have found a workaround that, while not perfect, works for the most part.
My problem is best stated as 'Geany is not workspace-aware.
What I do is to load one instance of Geany, and set it to 'Always on Visible  Workspace. Of course, this doesn't stay set unless I drag its window down as far as it will go. I discovered (by accident) that if I do this, it will remain set. When I say it isn't perfect, it's because sometimes I forget to 'park' it.

To load a file into geany from a terminal, I use an alias:
alias edt='nohup geany $1'
and it loads no matter which workspace it's on.

Anyway, while looking to see if the devs had any plans to make it workspace-aware, I ran across your issue, and thought I'd offer my solution.

**Comment by JoshDreamland** [comment]
Thanks, @lar3ry!

I think for me, the real issue was that only the first instance of Geany gets to make modifications to the preferences, so I'd often lose changes to those. I just became more deliberate about editing them. I use projects to manage files I want to open in batch, and I meticulously close all Geany windows but the main one I want to persist open files from, first.

It's a lot of chore to do what editors like Notepad++ can just do naturally, but I've been able to mostly phase Geany out as my primary editor at this point (in favor of vscode), so I'm doing all right myself.

As to your workspace-aware Geany, maybe did you see the `--socket-file` workaround they recommend?
`geany --socket-file=/tmp/geany-sock-$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')`

Cheers

**Comment by lar3ry** [comment]
> Thanks, [@lar3ry](https://github.com/lar3ry)!
> 
> I think for me, the real issue was that only the first instance of Geany gets to make modifications to the preferences, so I'd often lose changes to those. I just became more deliberate about editing them. I use projects to manage files I want to open in batch, and I meticulously close all Geany windows but the main one I want to persist open files from, first.

That's the beauty of my workaround. If it happens to lose the 'always on visible workspace' setting, and I click on my geany panel icon, it opens, but has no files in it, so I know right away to go find it on a workspace.
 
> It's a lot of chore to do what editors like Notepad++ can just do naturally, but I've been able to mostly phase Geany out as my primary editor at this point (in favor of vscode), so I'm doing all right myself.

Is that available on Linux?

I hear ya. I really miss the vertical select/cut/delete/paste and the easy macros. I like Pluma for its workspace awareness, but it's no Notepad++.

> As to your workspace-aware Geany, maybe did you see the `--socket-file` workaround they recommend? `geany --socket-file=/tmp/geany-sock-$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')`

Is that a command line? Or? (relative newbie to Linux, but I used Unix a lot when I worked for Sun.

**Comment by JoshDreamland** [comment]
Yes, `$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')` is a subshell that is executed and its output is treated as a string, as if the `$()` were an ordinary variable. It's just the current workspace number. So the `--socket-file` is set to `/tmp/geany-sock-WORKSPACE_NUMBER`.
