### ISSUE TITLE
Open dialog doesn't allow to insert path to file directly

### ISSUE THREAD

**Issue by nazar-pc** [geany/geany#1865]
Steps to reproduce:
* copy full path to file into clipboard, for instance, `/home/nazar-pc/.gitconfig` in my case
* open Geany
* Ctrl+O to open "Open file" dialog
* Ctrl+V to insert file path

Expected result:
Dialog window switches to corresponding directory with file from clipboard selected or something very similar.

Actual behavior:
```
The folder contents could not be displayed
Operation not supported
```

Workaround:
Type `/` first, then Ctrl+V and Enter.

**Comment by b4n** [comment]
This is a GTK+ issue; the open dialog is 99% stock GTK.  Apparently it works with URIs (e.g. `file:///home/nazar-pc/.gitconfig`) but fails if the scheme is missing.
Anyhow, you should be reporting this against GTK.

**Comment by nazar-pc** [comment]
Does it depend on GTK+ version from system libraries on GTK+ Geany was built with? In other words I'm curious whether Geany 1.33 uses latest GTK+ version (I'm on Ubuntu 18.10 with 3.28).

**Comment by elextr** [comment]
It uses whatever your distro makes the package with.

**Comment by elextr** [comment]
Geany supports both gtk2 and gtk3, which is why I said it depends on what the distro does when it makes the package.

**Comment by nazar-pc** [comment]
Says `GTK 3.22.30, GLib 2.56.1`. Yeah, look like Ubuntu still ships with libgtk-3 3.22.30 while other components are at 3.28. I'm wondering how Chromium from stock repos doesn't have this issue.

Thanks for clarification.

**Comment by b4n** [comment]
> Firefox, Chromium and Ghex also use GTK+ and its open dialog, but there it works properly.

Interesting.  This actually shows that it only fails when the open dialog is configured to accept non-local files (e.g. URIs and not only paths).  If you have remote bookmarks, you can see they don't show in Firefox (where the bug at hand doesn't happen indeed) but do in Geany, GEdit (where the bug is reproducible).

> Are you sure this is an upstream issue?

Yes, many other apps suffer from the same issue, including for example GEdit.

> Yeah, look like Ubuntu still ships with libgtk-3 3.22.30 while other components are at 3.28.

GTK 3.22 is the latest and will be the last GTK 3.X release (next will be 4.X), but GNOME has newer 3.X releases.

**Comment by nazar-pc** [comment]
@b4n, those are very useful details, thanks!
Reported upstream: https://gitlab.gnome.org/GNOME/gtk/issues/1119
