### ISSUE TITLE
New start flag: --wait

### ISSUE THREAD

**Issue by yory8** [geany/geany#1867]
Geany lacks a --wait flag to lock the caller until geany exits.

This is necessary when calling it from a script/program to process some text that needs to be fed back to the script after editing, for example ranger's (the file manager) bulkrename command.

**Comment by elextr** [comment]
Try -i to open it in a separate process that the script can wait on.

**Comment by yory8** [comment]
It works! Thank'you very much for your feedback. Maybe it might worth it to add this to the help message for -i? Maybe changing: `Don't open files in a running instance, force opening a new instance` to `Don't open files in a running instance, force opening a new instance. Blocks process until window is closed.`

**Comment by elextr** [comment]
That doesn't make sense, nothing in Geany is blocked.  

Without `-i`, the first Geany command (with a particular config) will, create an instance with a window for editing and continue to run until the user quits it, just like any other GUI application.  It doesn't need any special explanation.

The `-i` option causes Geany to create an independent instance which displays a window and continues to run so the user can perform the editing, until the user tells it to quit, just like any other GUI application. This is explained in [startup](https://www.geany.org/manual/current/index.html#startup) and the command options.

While the first instance without `-i` is still running any other Geany command without `-i` (but with the same config) will not create a window and will request the first instance to open the file and do the editing.  Since it has no window, so no way for a user to tell it to quit, and having asked the primary instance to do the editing work, it has nothing else to do, so it quits automatically.  As explained [here](https://www.geany.org/manual/current/index.html#opening-files-from-the-command-line-in-a-running-instance).

**Comment by yory8** [comment]
thank'you for the detailed explanation, all clear now.
