### ISSUE TITLE
Infer static analyzer report

### ISSUE THREAD

**Issue by Tzqt** [geany/geany#1876]
Geany version: 1.33

[gist: geany-bugs.txt ](https://gist.github.com/Tzqt/c5b34569bfb65aafeb5a8ade6bd1b7cd)

**Comment by b4n** [comment]
It's partly interesting, but as every static analyzer it's at least half wrong, so it has to be used carefully, and it takes time.  For example, the first issue is both irrelevant and mostly wrong (it probably comes from the fact `Assert` is defined conditionally as a non-aborting check, which makes the analyzer incorrectly think the checked value can be `NULL`), and the third is totally wrong, which might be interesting to report to the authors (it wrongly assumes control flow could skip the body of a `while(1)` loop). `src/encodings.c:608: error: PREMATURE_NIL_TERMINATION_ARGUMENT` is also incorrect, because of the semantic of the "incriminated" function.

Anyway, thank you for this, but it has to be sorted out, as it's not very useful straight out of the analyzer.

**Comment by elextr** [comment]
Note, individual pull requests fixing an individual fault or a very small number (after showing it really is a fault, not just "because the analyser says so") are likely to be welcome.  Omnibus pull requests are likely to take a long time to be accepted due to the issues @b4n notes above.

**Comment by b4n** [comment]
See #1878

**Comment by b4n** [comment]
Closing as the Gist is gone and at least some of the relevant things are fixed by #1878
