### ISSUE TITLE
Ecma script 6 in sidebar class view probably broken

### ISSUE THREAD

**Issue by zero0bytes** [geany/geany#1891]
Hi !
When i edit ecma script 6 javascript files i see there is maybe broken class view, there  is problem when editing big files, i use geany because of its class view lovely feature. Im using geany version 1.33 "Gorgon"

![geany](https://user-images.githubusercontent.com/39689342/42286358-eb3b62dc-7fb2-11e8-8ac5-9dfe4dcb951b.jpg)
as you can see there is no show class but source contain classes

update:
Here is example javascript ES6 code: https://github.com/zero0bytes/pixi.js-GUI/blob/master/pixi-gui.js

best regards

**Comment by b4n** [comment]
JavaScript is notably hard to analyze statically due to it's inherent dynamic nature, which means that short of actually executing the JavaScript code (and every single possible code path) and discovering new functions such, it's unlikely it could be possible to get fully accurate code structure.

However, in most common cases it's possible to infer what the developer meant, which gets mostly good results.  In your case, could you provide a sample JavaScript source so we could try and debug this?
BTW, [@universal-ctags/ctags](https://github.com/universal-ctags/ctags) is now the canonical upstream for the code that parses sources, so you might wanna check how it behaves, and report a bug there (I'm also involved there).

**Comment by zero0bytes** [comment]
Hi !
Here is  example javascript ES6 code: https://github.com/zero0bytes/pixi.js-GUI/blob/master/pixi-gui.js

**Comment by elextr** [comment]
Be nice if you could provide a minimum example, with what you got and what you expect.

**Comment by b4n** [comment]
The missing classes are fixed by ctags sync from #2018.
