### ISSUE TITLE
Geany saves preferences even if they weren't modified

### ISSUE THREAD

**Issue by JoshDreamland** [geany/geany#1934]
This makes updating your preferences an unduly laborious process, as chances are, you have more than one instance of Geany open when you go to update them. The solution right now is to either do this when you only have one open, and then close it, or to close all instances of Geany in the correct order.

It would be nice if Geany updated the preferences when you hit "Apply"/"OK" rather than when the editor is closed.

**Comment by elextr** [comment]
Geany isn't really designed to run multiple instances sharing preferences. 

This is more complex than it may seem because the session is also saved in the preferences file, and that must be saved at shutdown.  There have been various suggestions and discussions about splitting them, but nobody has come up with a concrete suggestion that addresses all the problems (or code).

Personally I suggest not using multiple instances sharing the same config, use `-c different/directory` to make each have its own prefs and session.  That way each instance maintains its own state and can be restarted where it was.

**Comment by elextr** [comment]
Closed, workaround available
