### ISSUE TITLE
The program can't start because libgcc_s_sjlj-1.dll is missing from your computer

### ISSUE THREAD

**Issue by CollinChaffin** [geany/geany#1979]
Latest nightly (10-19-2018) from `https://nightly.geany.org/win32/`

Installed with the instructions on that page of:
````
Usage:
Just extract this zip archive into your regular Geany installation
directory and start Geany. The About dialog should mention the
revision number in the header which was used when creating these files.
````

I receive this error, and Geany refuses to launch:

![snag_10-19-2018_17-10-32](https://user-images.githubusercontent.com/9301483/47246168-e3f41680-d3eb-11e8-9246-0769b43a7ea8.png)

Prior to extracting today's nightly zip over the 1.31 install as instructed, Geany 1.31 opened fine and if I uninstall, remove the entire Geany folder, and reinstall 1.31, returns to opening fine.  Only with the new binaries overlaid does it refuse to even launch.

I know nightlies are "unsupported" but thought it was worth opening an issue if one won't even open. :)

**Comment by elextr** [comment]
Between 1.31 and 1.33 (current) Geany I think there was a change to msys2 which may have different libraries, so a nightly might not work with the libraries of a pre-msys2 version of Geany.

**Comment by codebrainz** [comment]
I think the nightlies are meant to overlay onto the latest release, not old ones. Maybe the instructions could make that more clear.

**Comment by elextr** [comment]
> I think the nightlies are meant to overlay onto the latest release, not old ones. Maybe the instructions could make that more clear.

IIUC  previous statements by @eht16 correctly, as @CollinChaffin said, they are not supported to work at all, its just a side effect of testing the build that there is an executable result.

**Comment by eht16** [comment]
I removed the statement about using the nightly binaries on an existing Geany installation from the nightly website.
This is a relict from past times when it was actually possible to use the nightly binaries together with a normal installation of a Geany release. IIRC since the switch to the MSYS2 build environment on Windows, the binaries are incompatible and so this isn't supported anymore.

In theory it could be possible to produce nightly binaries which are more or less compatible with the GTK environment shipped with a Geany release. Though this needs some work to get the MSYS2 environment installed and working on Linux.
