### ISSUE TITLE
Add option to "Open files on read-only mode"

### ISSUE THREAD

**Issue by wiwwo** [geany/geany#1987]
When opening files, i want to be able to specify (before opening) the file should be in RO mode.
Just a "Always open files in read-only mode" check in Options will do.

Perfect for persons owning cats :-)

**Comment by elextr** [comment]
Feel free to have the cats submit a well written pull request.

**Comment by kugel-** [comment]
I think your use case is already covered:

1) When opening files within Geany you can click the "View" button instead of "Open" in the dialog. This will open the file in read-only mode.
2) When opening files from the command line you can add the -r parameter, making Geany open all files mentioned on the command line in read-only mode.

**Comment by wiwwo** [comment]
Yup, that makes perfect sense! :-)
It would be cool to have it as a "less hidden" config IMHO, but i trained my cats not ot walk on keyboard when i am using Geany, so for me problem solved :-D ;-)

**Comment by aks2161989** [comment]
As a Grant user on Windows, how can I open a file in read-only mode? I launch grant from the Start menu.

**Comment by codebrainz** [comment]
@aks2161989 as mentioned by @kugel- above:

> When opening files within Geany you can click the "View" button instead of "Open" in the dialog. This will open the file in read-only mode.

Just making sure you aren't [using "native dialogs"](https://www.geany.org/manual/current/index.html#miscellaneous), but rather the default GTK+ ones.

**Comment by aks2161989** [comment]
@codebrainz Thank you! I don't know how I missed that!
