### ISSUE TITLE
Missing size data to Windows installer

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#2007]
In Windows 7 control panel where you can see a list of installed applications you can se info in columns like name publisher installation date size and version.

For Geany 1.33 there is no data for the size column.

So i suggest adding the size info.

**Comment by eht16** [comment]
Basically possible but tricky in detail:
I tried adding the size information with method 1 described on https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs#Computing_EstimatedSize.

This works well enough for Geany itself but provides wrong information for G-P:
the mentioned GetSize function works by determining the used disk space of the installation directory *after* installation. This fine for Geany and gives accurate numbers.
However since G-P has to be installed in the same installation directory as Geany itself, the G-P installer would include the existing Geany installation into the calculation and so reports wrong numbers.

I think telling the user wrong numbers is worse than not telling anything.

In theory, the best solution probably to sum up the required disk space numbers in the installer's Components page and use the result for the uninstall information.
But I didn't find a way to get these numbers in the NSI script.

If anyone has an idea and/or other solution, just re-open.

**Comment by codebrainz** [comment]
Just a random idea, I have no idea if it's feasible; what about writing out the size of Geany files to a text file (maybe the manifest file where Windows reads this from) and then when GP is installed, reading it in and subtracting that amount from the new size (after GP)?

**Comment by eht16** [comment]
Should be possible, instead of writing the size to a file, the G-P installer could also read the size of the Geany installation from the Windows registry.
Though it would create a new dependency between the two installers and so more maintenance work.
I won't do it as I personally don't consider this so important to spend much time on it but if anyone likes to, why not.
