### ISSUE TITLE
Geany does not recognise markdown .md files

### ISSUE THREAD

**Issue by liborty** [geany/geany#2025]
An .md file from github.com is treated as plain text. No colouring, no preview, no way of setting anything, no nothing.
Even though in document, set filetype, markdown languages, markdown source file is automatically ticked.

**Comment by b4n** [comment]
You should explain what you're expecting.  For me, italics are italic, bolds bold, headings underlines are highlighted as well as list bullets, etc.  For a preview, install the Markdown plugin.  Not sure what you mean with "setting something".

**Comment by liborty** [comment]
Interestingly, it has started doing some highlighting once there was enough actual md code in the file.
I was expecting preview capability "out of the box". Markdown plugin is not even in the usual lists.

**Comment by elextr** [comment]
When posting please always specify the version of Geany and the OS you are using.  For a period the markdown preview plugin was removed by some distributions because the version of a library it required was no longer available on those distributions.  

The plugin has been updated to the new library version and (IIUC) should be available again with Geany-Plugins collection 1.34 and should be available in the plugin manager after installing it.

**Comment by elextr** [comment]
Removed labels since the md filetype works on 1.34 as expected, see also #2026

**Comment by dandv** [comment]
@liborty: were you perhaps affected by #2029?

**Comment by elextr** [comment]
@dandv doesn't seem related
