### ISSUE TITLE
on OpenBSD 6.4, "don't know how to make geany.desktop"

### ISSUE THREAD

**Issue by andy5995** [geany/geany#2049]
config.log attached
```
andy:18$ make              
make  all-recursive
Making all in ctags
Making all in scintilla
Making all in include
Making all in src
Making all in tagmanager
Making all in plugins
Making all in icons
Making all in 16x16
Making all in 24x24
Making all in 32x32
Making all in 48x48
Making all in scalable
Making all in tango
Making all in 16x16
Making all in 24x24
Making all in 32x32
Making all in 48x48
Making all in scalable
Making all in po
Making all in doc
Making all in data
Making all in tests
Making all in ctags
make: don't know how to make geany.desktop (prerequisite of: all-am)
Stop in .
*** Error 1 in . (Makefile:622 'all-recursive')
*** Error 1 in /home/andy/Desktop/src/geany (Makefile:481 'all')
```

[config.log](https://github.com/geany/geany/files/2755395/config.log)

**Comment by b4n** [comment]
Looks like the Intltool rule for generating Desktop files is not portable across Make implementations, it seems to be using GNU make `%` rules…

@andy5995 did you run autogen.sh, or did you use a tarball with a pre-generated configure?  If you didn't run autogen, maybe try it as I could hope that the BSD port of intltool might have a BSD-Make-compatible rule.  Otherwise, I'm afraid you'll have to use GNU Make.

It'd like to have a fix for this, but I'm not sure if it's worth maintaining our own version of the rule.  Maybe reporting it to upstream intltool if it still exists.

**Comment by andy5995** [comment]
I ran `CXX=eg++ CC=egcc ./autogen.sh`

>It'd like to have a fix for this, but I'm not sure if it's worth maintaining our own version of the rule.

Probably not. I ran `gmake` now and it's working. Maybe just a doc update? I noticed that BSD isn't listed on [the HowTos](https://wiki.geany.org/howtos/start).

**Comment by elextr** [comment]
Does this help (note latest commit) https://github.com/openbsd/ports/blob/master/devel/geany/Makefile

**Comment by elextr** [comment]
PS Open BSD isn't in the how tos because its in the Third Party Packages page where it says "use the ports".

**Comment by b4n** [comment]
@elextr I really think the only problem is that because of the mentioned intltool snippet our makefiles are dependent on GNU make.  The rest seemed to go well, or at least isn't the reason of the problem form the OP.

About howtos, it's probably mostly because nobody wrote one, which you could do if you felt like it as it's a wiki ;)  And as @elextr mentioned, we mention the port on the [third party packages page](https://www.geany.org/Download/ThirdPartyPackages#openBSD) already, so maybe not so many people wondered.

**Comment by elextr** [comment]
> our makefiles are dependent on GNU make.

@b4n, yeah, as I said in the edit the port makefile has `GMAKE=yes`, basically it seems to me that it should be the reference for "how to" build Geany for BSD.

**Comment by andy5995** [comment]
As I'm pretty new to BSD, my goal was just a little testing, to see if I could build geany ok and to see if any docs about it needed updating.

>About howtos, it's probably mostly because nobody wrote one, which you could do if you felt like it as it's a wiki ;) 

Yeah, I kinda do feel like it :)

**Comment by andy5995** [comment]
> > About howtos, it's probably mostly because nobody wrote one, which you could do if you felt like it as it's a wiki ;)
> 
> Yeah, I kinda do feel like it :)

I created https://github.com/geany/geany/issues/2053 for that.
