### ISSUE TITLE
Questions about auto completion

### ISSUE THREAD

**Issue by hkcorac** [geany/geany#2071]
Hello Geany developers,

I have some questions about configuring auto-completion, may I ask if you could help?

1. Is there a setting to always show suggestion list (the popup menu)?

In docs, the menu does not pop up, unless I press for `Ctrl-space`. However I write docs a lot, so it would help me if the menu is shown. I tried to find, but couldn't find a setting.

2. The initial list does not always offer all phrases. Is there a setting to change that?

For example, I often have to press `Ctrl-space` _twice_, in order to show all phrases.

Thank you very much,

**Comment by elextr** [comment]
`Edit->Preferences->Editor->Completions->Characters to type for autocompletion`?

What sort of filetype is your "doc"?

**Comment by elextr** [comment]
> I mean Java docs. When I type, the popup menu doesn't show up, unless using Ctrl-space. It also doesn't show up in Java's comments.

So you actually mean embedded Java doc comments?  

Automatic autocompletion doesn't happen inside comments and strings since they are meant to be text and only coincidentally contain words that happen to match symbols.  But you can still trigger autocompletion manually in the case you are actually typing a symbol name or an existing word.

The first time the keybinding is pressed the symbols (and tags) autocomplete list is shown, so the names have a symbol type icon in front of them.  

The second time it shows completions for all words in the document, so symbols from the document will still appear, but tags will disappear unless they happen to also occur in the document.  Notice that the symbol type icons disappear because its just words, not symbols, so they have no type.

**Comment by hkcorac** [comment]
@elextr 

Thank you very much, now I understand how the program works.

It would be great if the program has option to show autocompletion list inside documentation or comments. For example in Java-docs, `{@link}` or `{@code}` are common phrases. Or the autocompletion list might be able to help a lot with long words, such as: _synchronization_, _implementation_... In my code, docs lines are about 40%. So it would help a lot.

If I have more knowledge about C and Gtk, I would try to code and send you pull requests. Unfortunately for now it's not the case  :-(

Thank you again for your hard work. Geany is one of my best editors.
