### ISSUE TITLE
Disabling language files in Windows installer doesn't affect Gtk localizations

### ISSUE THREAD

**Issue by danpla** [geany/geany#2090]
The "Language Files" option of the Windows' installer only disables language files for Geany, but not for Gtk runtime. As a result, the installation takes 68.7 MB, 33.5 MB (49%) of which are MO files of Gtk in "share/locale" folder. However, the real issue is not the disk space but the fact that the interface becomes partially translated.

The same problem is with the installer for plugins.

**Comment by eht16** [comment]
Yes, this is some sort of intended because it is not that easy to seperate the GTK stack translations from the rest and so I decided to just live with it, especially as disk space is not a real problem nowadays.

But I didn't really realise the other mentioned problem: partially translated interface. This is in fact quite bad. I might work on this at some point but would be happy if anyone likes to contribute a patch.

**Comment by eht16** [comment]
It turned out it was actualy quite easy to solve.

The only drawback is that now GTK/dependency translations will be installed if translations are selected but GTK runtime/dependencies are not selected. Hope that's ok.
Preventing this is possible but would require quite some logic and more code in the installer for a probably uncommon combination.
