### ISSUE TITLE
Proposed slight change to Go-To Line functionality

### ISSUE THREAD

**Issue by rubyFeedback** [geany/geany#2146]
Right now if you input a number like

12345678

In the go-to widget

nothing happens.

The file I was modifying was a large .yml file, 16000 lines.

12345678 is much higher than 16000 so "technically"
geany would be "correct". But, the event that me as the user
is using that, the current behaviour is quite useless as the
go-to functionality does not work. In that case I would
like to, in pseudo code, have this behaviour:

    if user did input a HUGE number here
      automatically set the number to the "end of the file"

That way I as the user do not have to give an exact number
if I want to quickly jump to the end of a file, even if only
accidentally.

I reason that this behaviour would be better than the current
"no action is done" behaviour, which is quite useless to me.
(I also admit that this behaviour was with my old editor,
and I got used to it a lot. The go-to behaviour of geany
ni this regard is quite useless to me right now; I dont want
to need or have to need to know the number, it could be
autoset in this case, to the last line).

**Comment by elextr** [comment]
Always put the OS, version of Geany, GTK and Glib even if you think they are irrelevant.

With current git it goes to the end.

**Comment by b4n** [comment]
> With current git it goes to the end.

Does it?  It doesn't for me with master.

Regarding the feature request, it sounds reasonable to me.  Knowing it didn't go to the expected line might be useful, and maybe it shouldn't set the marker in this case, but it also seem to make sense to go to the closest line to the request.

**Comment by elextr** [comment]
> Does it? It doesn't for me with master.

Hmm, can't repeat, maybe the cursor was already at the end when I tested.

**Comment by codebrainz** [comment]
If the line is out of range, it could just leave the dialog open and make the text box red similar to the search dialog. It could also disable accepting the dialog (disable the "OK" button). It could do these in real time while typing to give some feedback whether the line entered is even valid, since it's a cheap check in code.

For jumping to the end of the file, better than inputting a random out of range number, the dialog could accept negative numbers and go that far from end, like -1 for the last line, -2 for the 2nd to last line, and so on.

Just a few ideas which would probably be easy to implement.

**Comment by elextr** [comment]
> Just a few ideas which would probably be easy to implement.

Pull requests are welcome (don't forget the toolbar as well).
