### ISSUE TITLE
Please include an address bar in the open dialog of geany!

### ISSUE THREAD

**Issue by roboirc** [geany/geany#2182]
Please include an address bar in the open dialog of geany so that users can go to custom locations eg /home/user/docs instead of having to go through the menu. Thanks!

**Comment by codebrainz** [comment]
This is controlled by GTK+. I believe in GTK+2 it has a location box by default except for in the "Recent" section. For GTK+3, as with most things, it's less user-friendly. In both, you can press <kbd>Ctrl</kbd>+<kbd>l</kbd> to get it to show the location box.

For more info, Google found this: https://winaero.com/blog/how-to-enter-file-location-manually-in-gtk-3-opensave-dialog/

Closing since it's not a Geany issue and must be fixed in GTK+.

**Comment by roboirc** [comment]
Then atleast indicate to the user the shortcut of CTRL+L to show the location box! Thanks!

**Comment by roboirc** [comment]
I would have never known that the shortcut CTRL+L exists! lol

**Comment by codebrainz** [comment]
I agree and I don't think GTK+ even documents this anywhere. It's a terrible design/UI, but unfortunately we are beholden to GTK+ dialogs (similar to Windows and Macos native dialogs), and it's totally external to Geany. If you had used any other GTK+3 program before Geany, you would've had this same issue with the other GTK+ program.
