### ISSUE TITLE
The default execute command for python on windows should be "py"

### ISSUE THREAD

**Issue by novel-yet-trivial** [geany/geany#2211]
As a python teacher I recommend Geany to newcomers a lot. It's always a pain to explain to them that first you need to change the execute command. The official python installer no longer adds itself to the path variable by default, therefore on a default python install the command "python" does not work. Instead for several years now the python installer also installs the "python launcher" named "py.exe". Users are expected to use the command "py" in the command prompt instead of "python". The python launcher adds support for shebangs to windows, making it easier to control python versions. 

I propose that you change the default execute command for python files from `python "%f"` to `py "%f"` in order to make Geany on Windows work with python out of the box. 

A potential downside is people that install python from Anaconda or similar packages, which do not install the python launcher and therefore still require modifying PATH and using the "python" command. However I feel that a user adept enough to adjust the PATH variable can probably also figure out how to change the execute command.

**Comment by elextr** [comment]
Good to hear that Geany works for you.

The problem is that we believe that most Geany users are on Linux/OSX (we __do not__ collect statistics, so its just a belief) and there the command is the current default "python".  

So someone needs to come up with a way for the default command on the windows build to be different from the one on Linux/OSX.
