### ISSUE TITLE
Allow users to pick GTK2 or GTK3 

### ISSUE THREAD

**Issue by LadyAleena** [geany/geany#2214]
I upgraded my OS from Debian Stretch to Buster, which upgraded Geany from 1.29-1 to 1.33-1. I found that Geany had switched from GTK2 to GTK3. GTK3 does not have as many available themes as GTK2 has. Currently I have found that Debian only offers six GTK3 themes. My favorite theme, the only one that does not assault my eyes, is not available in GTK3 through Debian's package system. So, this me wishing that Geany have a preference to use, my chosen, GTK2 theme instead of the default GTK3 theme, at least until all GTK2 themes have been converted to GTK3.

**Comment by elextr** [comment]
Geany supports both GTK2 and GTK3, but the selection has to be made at compile time since thats the way GTK works.  No application can be compiled with both at the same time.  Therefore it cannot be a runtime selection between GTK2 and GTK3.

GTK2 does not read GTK3 themes and GTK3 does not read GTK2 themes so having compiled Geany with either GTK2 or GTK3 you are stuck with their respective themes.

The choice of what version to put in its repositories is the distributions, not Geanys.  Ditto the choice of what themes to provide for GTK2 and GTK3.

Your only option is to compile your own GTK2 version of Geany and Geany-plugins or your own GTK3 theme.  You can put your own geany.css in the config directory so it only affects Geany.

**Comment by codebrainz** [comment]
> Currently I have found that Debian only offers six GTK3 themes.

For what it's worth, there are quite a few themes here: https://www.gnome-look.org/browse/cat/135/

> My favorite theme, the only one that does not assault my eyes, is not available in GTK3 through Debian's package system.

If you mean it's available for GTK3 (outside of Debian repos), you could just install it manually. You can install into `~/.themes` if you don't want to mess with package manager/system wide stuff.

**Comment by LadyAleena** [comment]
The theme I want is **not** available in GTK3. I've searched the internet for 2 days for it. There are themes that are close, but not enough.

**Comment by b4n** [comment]
As @elextr said, we don't have any control on what Debian provides, and we still support GTK2 if selected (but that's a selection only the binary provider can make).  You can still rebuild Geany yourself and make that selection, just bare in mind that you'll also have to rebuild any plugins you want.
