### ISSUE TITLE
when you reduce directory in the sidebar, hide equivalent tabs in the editor.

### ISSUE THREAD

**Issue by sgnyjohn** [geany/geany#2216]
when you reduce directory in the sidebar, hide equivalent tabs in the editor.

in the logic that each directory is a project, would allow filtering the editor's tabs with the projects of interest.

**Comment by elextr** [comment]
> in the logic that each directory is a project, would allow filtering the editor's tabs with the projects of interest.

A single directory == project is not an idiom that Geany specifically supports.  It is not an idiom that would work for anything but the smallest projects, since many (most?) projects use more than one directory, see Geany's own source.

If you use the sidebar documents list you can close the tabs and get back precious vertical real estate.

**Comment by LarsGit223** [comment]
The workbench plugin has got an option in it's context menu labeled "Open all files in sub-directory" and "Close all files in sub-directory". So it does not work automatically on reducing/collapsing a sub-directory in the tree but it's still faster than closing each single file by hand.

**Comment by ntrel** [comment]
> Close all files in sub-directory

Geany's built in Documents sidebar supports this, right click on a folder and click close.

**Comment by elextr** [comment]
@LarsGit223 and @ntrel the OP wants to __hide__ not close the tabs I believe.

**Comment by elextr** [comment]
> If you use the sidebar documents list you can turn off the tabs and get back precious vertical real estate.

It has been pointed out that this may not be clear, so to expand:

The "Documents" sidebar tab has the same functionality as the notebook tabs, and since its vertical not horizontal it can show many more files than the tabs can before scrolling is needed.

Since it has the same functionality, when it is in use the tabs are redundant, and can be turned off (Edit->Preferences->Interface->Notebook Tabs->Show Editor Tabs) to get some vertical space back (especially on systems where the theme makes tabs very high).

When the tabs are turned off, rolling up a directory in the Documents tab is effectively hiding those files as the OP requested.

**Comment by ntrel** [comment]
> @ntrel the OP wants to hide not close the tabs 

I know.

**Comment by sgnyjohn** [comment]
well, what I need is a context manager. my projects or sub-projects
are organized into directories. I have in use scripts that open different contexts,
but it is not ideal because there are libraries that are repeated in contexts.

the option to navigate in the "Documents" sidebar tab is possible, but if
there are many "directories" and files open, it becomes slow and not pleasant,
and higher horizontal tabs, with fewer options, in my opinion, are practical.

I then imagined a checkable option that would trigger this behavior
in Preferences -> Interface -> Notebook tabs.

however, one change may lead to other ...

**Comment by elextr** [comment]
@sgnyjohn perhaps you could use the Geany project files since they are basically a named session and can have files from anywhere open, and switching projects switches files open.
