### ISSUE TITLE
'Save As' dialog uses search mode in some cases

### ISSUE THREAD

**Issue by andy5995** [geany/geany#2267]
I wasn't sure of a good title for this ticket. Maybe a maintainer could change it?

When "untitled.c" appears highlighted in the field near the top of the "Save File" window, and I start typing to change the file name, instead of the file name changing, the file list changes as if I'm searching for a file with the characters I'm typing.

If I see a field highlighted like the filename, I expect that it's focused I guess, but maybe I'm wrong. Though I don't see any indication that this "search" mode is activated until I start typing characters; then it appears near the top, center.

To reproduce:

* File -> New with template -> main.c
* File -> save as
* Navigate to the directory where you want to save the file
* Note "untitled.c" still appears highlighted
* begin typing

## Sysinfo

* OS: Debian 10
* XFCE 4.12

```
15:29:13: Geany INFO		: Geany 1.36 (git >= 770cda40), en_US.utf8
15:29:13: Geany INFO		: GTK 3.24.5, GLib 2.58.3
15:29:13: Geany INFO		: System data dir: /home/andy/local/share/geany
15:29:13: Geany INFO		: User config dir: /home/andy/.config/geany
15:29:13: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/local/share/geany/geany.css'
15:29:13: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/local/share/geany/geany-3.20.css'
15:29:13: Geany INFO		: System plugin path: /home/andy/local/lib/geany
15:29:13: Geany INFO		: Added filetype Clojure (61).
15:29:13: Geany INFO		: Added filetype Nim (62).
15:29:13: Geany INFO		: Added filetype Graphviz (63).
15:29:13: Geany INFO		: Added filetype CUDA (64).
15:29:13: Geany INFO		: Added filetype JSON (65).
15:29:13: Geany INFO		: Added filetype Arduino (66).
15:29:13: Geany INFO		: Added filetype Scala (67).
15:29:13: Geany INFO		: Added filetype Genie (68).
15:29:13: Geany INFO		: Added filetype Swift (69).
15:29:13: Geany INFO		: Added filetype Cython (70).
15:29:13: Geany INFO		: Loaded libvte from libvte-2.91.so
15:29:13: Geany INFO		: Loaded:   /home/andy/local/lib/geany/editorconfig-geany.so (EditorConfig)
15:29:13: Geany INFO		: unknown : None (UTF-8)
```

**Comment by andy5995** [comment]
Obviously the work-around for this is to click in the "Name" field before you begin typing the new filename.

This bug doesn't reproduce unless you navigate to a different folder after clicking "save as".

**Comment by elextr** [comment]
This is the normal way a GTK UI operates.  Only one "current" field can be modified at a time but every field can have a selection.

You will notice that the filename entry is current when you first enter the dialog (how that is indicated varies with theme, on mine it has a bright outline) and typing replaces the selected (highlighted) text "untitled" as you would expect.

But when you go to the directory/file chooser field the filename field is no longer current and whatever indication your theme uses for current field is removed.  But the selection highlight remains.  Any text you type is always used by the current field, the directory/file chooser in this case, and the usual behaviour of choosers is to use characters typed to assist selection, the "search mode" I presume you mean.

Then as you observed you have to click on the filename field to re-enter it.  Of course that cancels the selected text in the field as it moves the cursor to the location you clicked.  But if you tab to the filename field the selection isn't changed and typing replaces the still highlighted text.

So when you change current fields the former selection in non-current fields remains, notice that if you select a line in the directory/file chooser and return to the filename field the line in the chooser remains highlighted.

The only thing that might be clearer is to indicate that the chooser is the current field instead of just removing the current field indication on the filename field (at least on my theme this doesn't happen).

**Comment by codebrainz** [comment]
@andy5995 if you mean the thing where you start typing and it mysteriously jumps to the "filter file list" text box, instead of affecting the main file name text box, I'm pretty sure this bug has been in GTK+ for a long long time.

**Comment by codebrainz** [comment]
Closing since this is a GTK+ bug.
