### ISSUE TITLE
Scrollbars don't repaint

### ISSUE THREAD

**Issue by truth-quark** [geany/geany#2277]
I'm unsure if this relates to #1002 in any way. The bug is being reported here first as Geany is the only application with the behaviour so far.

For the past year or more, geany's scrollbars haven't repainted properly, as I've observed in a few versions of Lubuntu (Ubuntu with the alternate LXDE desktop environment). This happens on my desktop and numerous Lubuntu VMs. I'm using ```apt``` installed geany. I haven't tried building it from source, or normal Ubuntu to see if is happens there. 

To reproduce:
1. Start geany
2. Make a new document
3. Copy & paste text into the new document, enough to make the document bigger than the available view.
4. Switch to another desktop (I'm using LXDE's desktop pager)
5. Switch back to the desktop with Geany
6. Note the scrollbars have not been repainted, so they show whatever was previously on the screen in the scroll area.

This happened in a fresh Lubuntu 18.04 VM I built earlier today.

Geany info (this is geany installed with ```apt```):
```
$ geany -V
geany 1.32 (built on 2018-01-08 with GTK 3.22.26, GLib 2.54.1)
```
System info:
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

$ uname -sr
Linux 4.15.0-58-generic
```
Here's the before/Geany freshly started view on a new VM:
![01_freshly_started](https://user-images.githubusercontent.com/526793/63740506-a5b16880-c8d4-11e9-8d75-c75ac60fd58d.png)

After switching away, then back, the scrollbars have the desktop colour:
![02_no_repaint](https://user-images.githubusercontent.com/526793/63740520-b235c100-c8d4-11e9-89d9-d07f6893705b.png)

**Comment by elextr** [comment]
Don't see this on other desktops (well nobody has reported, and I don't see it on cinnamon).  Since those scrollbars are drawn by Scintilla perhaps try Scite and see if it has the same problem and then refer the issue to Scintilla (preferably a Scite 3 if you can get it, Geany does not use Scintilla 4 yet).

**Comment by truth-quark** [comment]
Here's the result of experimentation with different versions:

Fresh Ubuntu 18.04.3 VM using apt to install:
* Scite 4.0.0 for GTK+ 3.22.30 (Nov 23rd 2018) --> scrollbars OK
* Geany 1.32 (built 2018-01-08 with GTK 3.22.26, GLib 2.54.1) --> scrollbars *don't* repaint properly.

Fresh Lubuntu 16.04.5 VM using apt to install:
* Scite 3.6.0 for GTK+ 3.16.7 --> scrollbars OK
* Geany 1.27 (built 2016-04-17 with GTK 2.24.30, GLib 2.48.0 --> scrollbars OK

**Comment by elextr** [comment]
Hmmm, lets see

| Scintilla | GTK | Result
| --- | --- | --- |
| 3.6.3 | 2.24.30 | Ok |
| 3.6.0 | 3.16.7 | Ok |
| 3.7.5 | 3.22.26 | bad |
| 4.0.0 | 3.22.30 | Ok |

IIRC there were a number of problems with GTK 3.22 and Scintilla, maybe you are hitting one of those  which has been fixed since 3.7.5.  Any chance you can try a later Geany (its up to 1.35 now with Scintilla 3.10.2), maybe from the [PPA](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa) if you can't build yourself.

**Comment by truth-quark** [comment]
I tried the PPM option with the same test VMs as before:
* Ubuntu 18.04.3 with Geany 1.34.1/GTK 3.10.8 --> Scrollbars OK
* Lubuntu 18.04.3 with Geany 1.34.1/GTK 3.10.8 --> Also OK

This fits with your suggestion. I'll check normal Ubuntu 19.04 since the next long term support edition (20.04) doesn't exist yet.

**Comment by truth-quark** [comment]
Quick test of Ubuntu 19.04 & geany 1.34.1/GTK 3.24.5, GLib 2.59.3  --> scrollbars ok.

**Comment by elextr** [comment]
So seems to be fixed in more recent systems, its unfortunate if a LTS distro has a bad combo, but it not anything Geany can fix.

**Comment by truth-quark** [comment]
Of course, the useful thing is identifying the most likely source of the problem :-) I'll close the issue.
