### ISSUE TITLE
GTK+ 3 installation not used by default by configure script

### ISSUE THREAD

**Issue by paulmenzel** [geany/geany#2393]
I have to use `--enable-gtk3` to built Geany with GTK+ 3.24.x. My understanding is, that if installed, it would be used over GTK+ 2 by default.

**Comment by LarsGit223** [comment]
IMHO the documentation at https://geany.org/manual/dev/hacking.html#gtk-versions-api-documentation sounds like GTK2 is the default.

**Comment by paulmenzel** [comment]
True, but the description of the configure help text is confusing to me.

    $ ./configure --help
    […]
      --enable-gtk3           compile against GTK3 [default=auto]
    […]

**Comment by b4n** [comment]
@paulmenzel The GTK version is automatically selected (it'll use the one you have), but is currently conservative towards GTK2 (if you have both, GTK2 will be selected).
The help text looks OK to me, and I'm not sure *"default=yes if available and GTK2 is not available, no otherwise"* would be an improvement.  As for all options, if you really have a preference just set it explicitly (`--enable-gtk3` or `--enable-gtk3=yes`).

**Comment by paulmenzel** [comment]
For me the extended text would clear it up, but I know the answer now, so fine by me. Thank you for the explanations.

**Comment by elextr** [comment]
Not worth worrying, GTK2 will go away soon, (ducks) :grin:
