### ISSUE TITLE
What exactly are the required deps for building on Ubuntu?

### ISSUE THREAD

**Issue by dandv** [geany/geany#2403]
I've installed `build-essential`, but beyond that, the build instructions in the README are pretty vague. When I run `./configure`, I get

> configure: error: in `/home/dandv/prg/geany-1.36':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

This is unnecessarily painful. Ubuntu is a very popular distro. Can we please have a one-liner `apt install ...` with the deps for Ubuntu?

**Comment by LarsGit223** [comment]
Did you run ```./autogen.sh``` first?

**Comment by elextr** [comment]
Somebody who is an expert on Ubuntu might know whats in `build-essential` but it seems it doesn't include `pkg-config`, which is surprising.

**Comment by codebrainz** [comment]
> Can we please have a one-liner apt install ... with the deps for Ubuntu?

`apt-get build-dep geany`

**Comment by dandv** [comment]
> Did you run `./autogen.sh` first?

No, because I had downloaded [a source tarball](https://www.geany.org/download/releases/).

> `apt-get build-dep geany`

```
$ sudo apt-get build-dep geany
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
```

**Comment by elextr** [comment]
> No, because I had downloaded a source tarball and the README doesn't mention running autogen in that case.

Thats correct, not needed for tarballs, but since you hadn't said tarball before, its a reasonable question.

> E: You must put some 'source' URIs in your sources.list

Thats telling you what you need to do.  `apt-get` needs to know what is needed to build, and for that it needs the distribution source package, which lists what the package needs on that specific distribution and version of the distribution, then it will get what you need on _your_ system.  I'm not a Ubuntist, but its likely that you can do this from some GUI setting.

The readme is vague because there are so many systems out there that "it depends" is the answer.

**Comment by codebrainz** [comment]
https://askubuntu.com/a/857433
