### ISSUE TITLE
Simple question with ./autogen.sh Beginner

### ISSUE THREAD

**Issue by Nick-us** [geany/geany#2406]
I understand that depending on Source I need to run autogen
**Doubt:** In my slackbuild I don't use ./configure
And now I'm worried if I need after running autogen also run ./configure
Although everything seems to work, I would like to know if I am doing it the right way!
I'm doing it below

```
SLKCFLAGS="-O2 -fPIC"

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./autogen.sh \
   --prefix=/usr \
   --sysconfdir=/etc \
   --libdir=/usr/lib64 \
   --localstatedir=/var \
   --mandir=/usr/man \
   --docdir=/usr/doc/$PRGNAM-$VERSION \
   --disable-static \
   --build=$ARCH-slackware-linux
```
Any help or tip I am grateful!

**Comment by elextr** [comment]
Autogen runs configure, see [here](https://github.com/geany/geany/blob/5cc69b3d6728a714637caabf0238759363e91e85/autogen.sh#L100).

**Comment by codebrainz** [comment]
If you're making a package, I would use [the stable releases](https://geany.org/download/releases/) as Source. When using those you don't need to run `autogen.sh` at all.

If you're using Git as Source then you need to run `autogen.sh` once in order to generate the `configure` script (and various other files). Once `configure` is generated, you never need to re-generate it using `autogen.sh` again, unless you're making changes to the build system of Geany. `autogen.sh` script has a bunch of dependencies which are not needed just to compile Geany, so you wouldn't want people using the package to have to install all of them for no reason, and spend all the extra time regenerating already existing files.

autogen.sh = prepare the Git repo to be built
configure = prepare the build system for the host/target

Disclaimer: I'm not familiar with Slack packaging.

**Comment by Nick-us** [comment]
> Autogen runs configure, see [here](https://github.com/geany/geany/blob/5cc69b3d6728a714637caabf0238759363e91e85/autogen.sh#L100).
Thanks for the clarification! This means that if I need to run autogen for any reason I already know that it also ran ./configure

I needed to know that! Thank you!
And your idea of showing this on autogen Source helped even more! Because I learn to identify and know these commands better

**Comment by Nick-us** [comment]
> If you're making a package, I would use [the stable releases](https://geany.org/download/releases/) as Source. When using those you don't need to run `autogen.sh` at all.
> 
> If you're using Git as Source then you need to run `autogen.sh` once in order to generate the `configure` script (and various other files). Once `configure` is generated, you never need to re-generate it using `autogen.sh` again, unless you're making changes to the build system of Geany. `autogen.sh` script has a bunch of dependencies which are not needed just to compile Geany, so you wouldn't want people using the package to have to install all of them for no reason, and spend all the extra time regenerating already existing files.
> 
> autogen.sh = prepare the Git repo to be built
> configure = prepare the build system for the host/target
> 
> Disclaimer: I'm not familiar with Slack packaging.

Thanks again! Your explanations add more information to me, and it helped me a lot! Now with the 2 answers you gave me helped me to advance my knowledge!
