### ISSUE TITLE
Typescript symbols

### ISSUE THREAD

**Issue by srgcdev** [geany/geany#2442]
When I open a typescript file (.ts), I can't navigate between symbols because geany doesn't find any symbol.
However, in a javascript file (.js) I can't navigate between symbols with no problem, for example, classes, methods, constructor, etc.

**Comment by elextr** [comment]
Thats because there isn't any symbol parser for typescript.  There is one in upstream ctags, but to add it then typescript would have to become a built-in language (at the moment its a customisation).  

Becoming a built-in language requires C coding to incorporate it into Geany, and someones got to do it, the basics are in HACKING.  Pull requests are welcome.

**Comment by codebrainz** [comment]
If anyone feels like working on this, it might be nice to rip out the old JS tag parser and use the upstream TS one for both JS and TS to avoid having duplicate parsers.

**Comment by techee** [comment]
The upstream typescript parser unfortunately doesn't parse function signatures (unlike the javascript parser) so using it for javascript files would remove calltips so better to use the javascript parser. I'd like to add the missing parsers for filetypes that Geany supports at the end of the "ctags sync" odyssey. The parsers we could use are:
- ocaml
- typescript
- ada
- CUDA (part of the already included cxx parser)
- clojure
