### ISSUE TITLE
Main editor scrollbar leaves copies of itself

### ISSUE THREAD

**Issue by Jappel97** [geany/geany#2458]
I'm running on Ubuntu 18.04

When I scroll or jump in the main text editor, the scroll bar (on the left) leaves copies of itself. This ends up resulting in eventually the entire "bar area" (not sure what to call it? The area in which the scroll bar may scroll) seems to be the scroll bar. (see here: https://i.imgur.com/HAMRZJ4.png)

More specifically, this occurs after: opening a file in a new tab, switching tabs, switching back to previous file.

**Comment by Jappel97** [comment]
Changing themes on the main OS seemed to have resolved the issue. Please disregard.

**Comment by nomadbyte** [comment]
I'm experiencing the same issue on Ubuntu 18.04. Though the appearance is different. The scroll marker (in my vanilla Ubuntu install it's orange colored) is not properly cleared on movement and eventually the whole vertical scroll bar turns orange.

I'm not uploading a screenshot, but here's how I can repro this.

- open a file (I opened a C file)
- then open a Search > Find (Ctrl+F) dialog
- then find something (I typed 'gchar' as I've quite a few of those)
- once it matched one, with Find dialog still on-screen, try to manually drag the scroll marker in Editor window.
- the scroll marker gets "smeared" all over the scroll bar area.

I have no plugins enabled.

**Comment by elextr** [comment]
This is a recorded message, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages) and the operating system and version you are using.

And in this case, the desktop (don't assume everybody knows when Ubuntu switched from mir to gnome).

And did you try changing the theme as posted by the OP?

Needless to say WFM on Linux Mint Cinnamon (based onUbuntu 18.04) with Geany 1.37 (git >= 82590af4), en_AU.UTF-8 GTK 3.22.30, GLib 2.56.4

**Comment by nomadbyte** [comment]
D you know if this this issue has been specifically fixed since 1.32, or "It just works"?

Btw, 1.37 is not released  (even 1.36 is not pullable from Ubuntu repos yet). I tried a nightly, and Geany seems to use a different theme internally, unlike the rest of the installed apps (Firefox, LibreOffice etc.), AND it is different from the look of Geanyy 1.32 from Ubuntu's package. In the nightly's  theme the scrollbar marker is not orange and flat, instead it's gray and "rounded".

I reinstalled 1.32, and the issue is very much still there.

**Comment by elextr** [comment]
> Btw, 1.37 is not released 

Yes its the development version, AFAIK there are no specific fixes.

> even 1.36 is not pullable from Ubuntu repos yet

Thats a general problem with distros, they may be slow to release new versions of software, especially LTS distros like 18.04.

>  I tried a nightly, and Geany seems to use a different theme internally

And does the problem still occur?  Geany does not have its own themes, it just uses what the desktop provides (unless the distro patches its releases).  Which is why I asked about which you are using (hint hint :) because it won't be the Cinnamon that LM uses.

**Comment by nomadbyte** [comment]
This is not about the theme, unfortunately. It seems to me that it was likely a bug in Scintilla. I can't zero in on exactly what their fix was. But this all seemed to be be related to transition to GTK3. BTW, the nightlies look like built to GTK2, otherwise they'd comply with my current GTK3 theme.

Starting with Geany 1.34, at most, this scrolling bug does not manifest itself anymore. 1.32 is affected. If you're up for this, you could try building that version from source to see if it acts up on your end.  As much as I could gather `sci_set_selection_start()  / end()` is what eventually breaks the sync between scrollbar state and redraw of the vscroll slider. This scroll misbehavior just as well cold be triggered from tool-bar search field.

Geany also had a scroll-related fix [604eac9f0], but it does not look like it targets this specific issue.

> Thats a general problem with distros, they may be slow to release new versions of software, especially LTS distros like 18.04.

Too bad, as I was hoping to introduce a few more "regular" users to Geany. I won't expect them to build it from sources. Hopefully, 1.36 would find its way to repos soon: [https://tracker.debian.org/pkg/geany](https://tracker.debian.org/pkg/geany)

**Comment by elextr** [comment]
See also #2277

**Comment by elextr** [comment]
> > Thats a general problem with distros, they may be slow to release new versions of software, specially LTS distros like 18.04.

> Too bad, as I was hoping to introduce a few more "regular" users to Geany. I won't expect them to build it from sources. Hopefully, 1.36 would find its way to repos soon: https://tracker.debian.org/pkg/geany

Yeah, not much Geany can do about distros backport rules, each distro has its own Geany supporter who kindly makes packages that comply with that distros rules, otherwise it wouldn't be available in many at all, since Geany devs have no expertise in packaging.

**Comment by nomadbyte** [comment]
Confirmed. Swapping Scintilla version used in Geany version 1.32 with one from 1.34  resolved this issue. There was some rework in Scintilla editor classes around selection and scroll handling.
