### ISSUE TITLE
geany freezes computer

### ISSUE THREAD

**Issue by ferdymercury** [geany/geany#2484]
If one provides a text file with a single line but an insane number of characters (columns) with a lot of quote opening and closing, braces, non-closing double quotes, etc. in this first single line, the CPU usage skyrockets and Geany freezes the computer. One has to kill the terminal.

This happens sometimes to me when I get a quite long JSON (preferably quote-corrupt) file (6Mb) that has no newlines, so all is in the first line.

Maybe some security check could be added to avoid this?

**Comment by elextr** [comment]
Geany is designed for editing human files, not machine minimised files.  Many things happen per line, and its more than proportional to the line size.

You should be able to open the file fairly quickly if you open it as filetype `none` and wrapping off, but otherwise it will be slow, especially with very long lines because the code is optimised for short lines.

The problem with warning about lines too long is, what is too long?  The answer is likely to be different for a Raspberry Pi and an i9 9900k workstation.  Also it would require scanning the file to determine line length further slowing _all_ file loads.

**Comment by ferdymercury** [comment]
I tried the same file but adding many newlines and the problem was the same.

But the solution of setting the filetype as none allowed me to open the document, now it loaded instantly. Thanks for the hint!
