### ISSUE TITLE
Multiple Terminal Tabs with more Scrollback lines [feature request]

### ISSUE THREAD

**Issue by hubitor** [geany/geany#2528]
Please consider adding support for multiple terminal tabs as well as increasing the current limit of the scrollback lines (5000).

**Comment by codebrainz** [comment]
https://plugins.geany.org/multiterm.html

`Edit->Preferences->Termial->Scrollback lines`

**Comment by hubitor** [comment]
Thanks!
I've installed the geany-plugins package from here:
https://www.archlinux.org/packages/community/x86_64/geany-plugins/
but MultiTerm is not among the plugins. I guess, I have to install it manually.

The maximum number of Scrollback lines appears to be 5000. I would like to increase it, but it's ok. I'm closing the issue...

**Comment by codebrainz** [comment]
> The maximum number of Scrollback lines appears to be 5000. I would like to increase it...

Oh. That limit does seem kind of arbitrary. Also according to [the docs](https://developer.gnome.org/vte/0.48/VteTerminal.html#vte-terminal-set-scrollback-lines) it's legal to pass a negative value for "infinite scrollback" but that won't work since the value is arbitrarily clamped between 0 and 5000.
