### ISSUE TITLE
drawing artifacts on resize and close

### ISSUE THREAD

**Issue by magnetophon** [geany/geany#2534]
When I resize or close geany, I get drawing artifacts like these: https://youtu.be/ds-Opjl1N6c

I also get them on 3 other gtk3 based programs: termite, lxterminal, and emacs.
I don't get them with baobab, wich also used gtk3, so maybe the issue is in the text drawing code?

[Here](https://github.com/thestinger/termite/issues/719) is another issue about the same thing.

A cursory search on https://gitlab.gnome.org/GNOME/gtk/-/issues didn't turn anything up, but maybe someone more familiar with the geanny codebase will have more success with a more targeted search.

**Comment by elextr** [comment]
As it happens with other GTK3 apps, but not all GTK3 apps its unlikely anything to do with Geany.

**Comment by elextr** [comment]
PS, my first guess would be the desktop manager since its background thats flickering.

**Comment by magnetophon** [comment]
@elextr Agreed that it's probably not directly geany's fault, but I was hoping someone knowledgable on this stuff could do a good bug-report to gtk.

**Comment by elextr** [comment]
Projects that are applications which just use GTK are unlikely to have sufficient detailed knowledge of its internals to help you with interactions between it and other software.  Asking directly of GTK is more likely to get useful assistance.  

But I am not sure why you want to raise a bug report there first, rather than on the project for the thing (the desktop background?) that is actually flickering.

**Comment by codebrainz** [comment]
@magnetophon one thing to try to narrow it down might be to switch to an X11 session if using Wayland or vice versa. I think most of the current popular login managers offer an option to pick the session type.
