### ISSUE TITLE
File save issue

### ISSUE THREAD

**Issue by mdziczkowski** [geany/geany#2542]
I have opened a file with a ISO-8859-1 encoding. After doing changes, I tried to save it and had received following error message, while having full permissions (0777 = rwx rwx rwx) to the file:

> An error occurred while converting file from UTF-8 in "ISO-8859-1". The file remains unsaved.
>
> Error message: Invalid byte sequence in conversion input
> The error occurred at "Ż" (line 3, column 18)

This is strange. The original file was opened in the ISO-8859-1 encoding and there is no possibility to chose the destination encoding while saving.

Please fix it asap

**Comment by codebrainz** [comment]
Ż is not valid in ISO-8859-1 (Western Europe), it's part of ISO-8859-2 (Central Europe). If you have the choice, I'd stick with UTF-8 though as it covers all languages.

> there is no possibility to chose the destination encoding while saving

The buffer in the editor is always UTF-8, but you can choose which encoding to save with using the Document->Set Encoding menu.

**Comment by mdziczkowski** [comment]
The problem is  that I'm unable to open this file as UTF-8 because there is no possibility to choose the encoding of the opened file in the "file open" dialog

**Comment by elextr** [comment]
The `More options` expander on the open dialog allows the encoding to be specified.

**Comment by mdziczkowski** [comment]
@elextr: Please read above. I wrote that I had set changed in the editor the encoding to UTF-8 and are getting the mentioned error message, so it's a issue with the file saving... it's like the save process does has a problem with saving while the file and buffer (editor) encoding are different

**Comment by elextr** [comment]
@mdziczkowski my comment was in response to your "The problem is that I'm unable to open this file as UTF-8 because there is no possibility to choose the encoding of the opened file in the "file open" dialog" pointing out that you can in fact choose the encoding to read the file in the open dialog instead of Geany using heuristics to decide the encoding to read the file.  Heuristics can be wrong.

As @codebrainz said, the Geany buffer is always UTF-8, the open dialog gives you the choice to select the encoding of the file which is converted into UTF-8 in the buffer, and you can add any UTF-8 character to the buffer.

Looking at your OP, perhaps you meant the "File Save" dialog?  In which case you are correct, the selection is not in the save dialog, the setting in `Menu->Document->Set Encoding` sets the encoding to write the UTF-8 from the buffer to the file.  It defaults to the encoding used to read the file into the buffer but can be changed by the user.

As @codebrainz said, if the encoding at `Menu->Document->Set Encoding` cannot encode a character in the buffer you will get the error in your OP.  He suggested you select ISO-8859-2 which contains the character you added, or UTF-8 to be able to save any character Geany can add to the buffer.
