### ISSUE TITLE
Symbol list does not switch between name / appearance

### ISSUE THREAD

**Issue by TinCanTech** [geany/geany#2553]
geany 1.36 - Symbol list does not switch between name / appearance until restart.

geany 1.32 - does

**Comment by elextr** [comment]
1.36 WFM

**Comment by TinCanTech** [comment]
I'll double check. I built 1.36 from source so maybe `gtk+2.0-dev` old version or something.

**Comment by TinCanTech** [comment]
More details:
- Using Edit -> Preferences -> Interface: Sidebar
 Switching between * Name / * Appearance
 Pressing Apply and/or OK, has **no** effect until `geany` is restarted.
- Right click on Sidebar `Symbols +Functions`
 Switching between * Sort by Name / * Sort by Appearance
 Works as expected.

Does that shed any further light ?

**Comment by elextr** [comment]
1. since you didn't specify the details I only tried the right click menu, which as you say works immediately, but only to the current file.

2. the label on the `Edit->Preferences->Interface` setting says it all, `Default sorting mode:`, it just sets the default to use when first opened before any right click setting is applied to the file

**Comment by TinCanTech** [comment]
I'll just take this as `acceptable change` then.
