### ISSUE TITLE
"Adjust line" preferences setting only works on opened files after closing and reopening them

### ISSUE THREAD

**Issue by ruben39x2** [geany/geany#2589]
Tested in Windows and Linux versions, Geany 1.32.

1. Have two or more files opened with Geany (not sure if with 1 also happens)
2. Go to Edit > Preferences > Editor 
3. Check the first item in "Features" section; line adjustment.
4. This should make the lines not to be rendered beyond the right margin of the window, making them split into multiline (not actually adding a \n char, you know). It doesn't happen.
5. Close the Geany window. Reopen it.
6. The lines still are not displayed multiline (adjusted).
7. Close one file tab. Reopen the same file. 
8. Lines are finally correctly rendered.

I think it'd be awesome to see the new preferences setting in effect in (4), although at least in (6) the lines should be correctly rendered.

Please, contact me if further details are needed. Thanks.

**Comment by elextr** [comment]
Note that 1.32 is a fairly old version and can't remember how it worked, I have tried to translated to current 1.36.

> Have two or more files opened with Geany (not sure if with 1 also happens)
> Go to Edit > Preferences > Editor
> Check the first item in "Features" section; line adjustment.

In the 1.36 its called "Line Wrapping"

> This should make the lines not to be rendered beyond the right margin of the window, making them split into multiline (not actually adding a \n char, you know). It doesn't happen.

Line wrapping does not add `\n` to the contents, it simply renders the content limited to the right margin.  You can see that because the line numbers do not display on wrapped content and only increment on line endings actually present in the document.

Each document thats open can have a different wrapping setting by the user via `Document->Line Wrapping`.  The preferences setting is the default used for newly opened documents.

> Close the Geany window. Reopen it.
> The lines still are not displayed multiline (adjusted).

When Geany is closed and re-opened, document settings for documents open at close are remembered so they can be reopened in much the same state as they were when Geany is closed, so wrapping won't change for files that are reopened.

> Close one file tab. Reopen the same file.

But by closing the documents and re-opening you are using the default as its then a newly opened document, thats why the setting changes when you do this.

> Lines are finally correctly rendered.

> I think it'd be awesome to see the new preferences setting in effect in (4), although at least in (6) the lines should be correctly rendered.

The reason neither of these happens is explained above and is the intended operation to allow per-document wrapping settings.
