### ISSUE TITLE
Save As dialog can save the wrong document

### ISSUE THREAD

**Issue by ntrel** [geany/geany#2599]
## Steps to reproduce:

1. Open a document
1. File->Save As
1. Notice an interesting file in the list of files in the dialog
1. Open interesting file from the command-line (in another program) with `geany interesting-file`. The file opens in the background underneath the Save As dialog.
1. Type a new filename and click save

The `interesting-file` document will have been saved with the new filename. The original document will still be open, unsaved.

## Cause

`handle_save_as` is dialogs.c uses `document_get_current`.

**Comment by elextr** [comment]
Yes, Geany is totally non-reentrant, thats why all dialogs are blocking, to stop users doing other things while they are open.  IIRC used to cause intermittent reports from KDE because the dialogs didn't block there.

Because the dialogs are blocking probably the socket operations are the only things that can cause reentrancy (well all I can think of just now :).  There is the potential for issues to happen anywhere Geany returns to mainloop while an operation is in progress, not just save as.

At least for save-as it might be fixed by getting the document to be saved before opening the save-as dialog so changing the current document won't affect which one gets saved.
