### ISSUE TITLE
windows, new file do not create a new file

### ISSUE THREAD

**Issue by fyah** [geany/geany#2656]
Hello,

Geany 1.36/1.37 (maybe this exists since a long time)

Start geany without opening a document
you get the following window
![image](https://user-images.githubusercontent.com/2546966/98952981-63397300-24fc-11eb-86c3-3313938f40da.png)

clicking on new file, do not create any new file
we can see however the action in the logs
![image](https://user-images.githubusercontent.com/2546966/98953079-82d09b80-24fc-11eb-89ef-ba6a92bcd2dd.png)

but no new file created
![image](https://user-images.githubusercontent.com/2546966/98953131-9419a800-24fc-11eb-96cf-1ba4cea8772c.png)

If I start geany with a document opened then all I can observe is the same (message, logs) except that the new file action is working fine
![image](https://user-images.githubusercontent.com/2546966/98953458-fe324d00-24fc-11eb-95fd-987f1bc5db88.png)

If I start the application without any document and then I open a file afterwards, it also works as expected

**Comment by codebrainz** [comment]
I believe this is intentional and has been the case since very early, if not the initial commit.

See the [code here](https://github.com/geany/geany/blob/0a0b4b000cf18e837b921057a461ad05a08e41d3/src/document.c#L628); when you open new untitled document and there's only one new/untitled document that hasn't been changed, it closes the previous untitled document and opens a new one. I'm not sure I see the point of that, but I also don't see a particular problem with it, unless I'm just not seeing the use case for wanting many new/untitled tabs open with no changes to them.

**Comment by fyah** [comment]
indeed that seems rigth to me 👍 
i just never realized this until recently, because i was looking into the slow startup
