### ISSUE TITLE
File edits slowly

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2675]
Geany edits the attached file very slowly. Might it be possible to make it edit more quickly without having to reformat the HTML?

[zzzNetwork.txt](https://github.com/geany/geany/files/5608094/zzzNetwork.txt)

**Comment by elextr** [comment]
Files containing a single very long line are a known issue with Scintilla because a lot of its work happens on the visible lines, which in this case is the whole file.  This is unlikely to change, its not what it was designed for and its not the common use-case its optimised for.

You can try setting the filetype `Document->Set Filetype->None` to see if it has any noticable effect.

**Comment by codebrainz** [comment]
Related to/duplicate of #2484 et al.
Upstream bug: https://sourceforge.net/p/scintilla/bugs/1563/
