### ISSUE TITLE
Transparent search/replace dialogs when out of focus

### ISSUE THREAD

**Issue by etkaar** [geany/geany#2698]
I am used to have the Find/Replace dialogs opened all the time and would like to have an option to make it a little bit transparent (50-70% or something) while out of focus. I believe there is no such preference yet implemented.

I think it can be also a useful feature for other users, so I think about making a Pull Request for it (in case I am at all able to implement it). Do you think _Edit > Preferences > Interface_ would be a good place for such a preference? Notepad++ for instance has it on the search dialog itself, but I think we can save the space for more heavily used settings because I think, once enabled, this setting wouldn't be changed very often by users afterwards.

**Comment by elextr** [comment]
Its preferred that styling for everything but the editing window be done with GTK CSS.  I'm no expert, but I believe it can specify differing settings from states like focussed etc.  Not sure about transparency, but maybe opacity will work.  Probably best to read the GTK docs/tutorials etc and try it.

For selector purposes both the Find dialog and the Replace dialog are called "GeanyDialogSearch", not sure how well that will work, but may be ok if only one of them is visible at a time.  Otherwise we can probably change one if needed.

**Comment by elextr** [comment]
See also https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-3-css

**Comment by etkaar** [comment]
Way more easy then I initially thought – I was not aware that I can use CSS since it is the first time at all I work with GTK:

Add at the end of _Tools > Configuration Files > geany.css_:

```
/* make search dialogs transparent if out of focus */
#GeanyDialogSearch:backdrop {
	background-color: transparent;
	opacity: 0.6;
}
```

**Note:** _opacity_ will only work together with _background-color: transparent_ otherwise it will become black.

@elextr If I understand it correct, there is no need to implement it as feature, since it is easily possible due to GTK CSS styling. Should we then close this issue or link it to a specific "tutorial" page?

---

**Example**

![Screenshot from 2020-12-21 13 39 46](https://user-images.githubusercontent.com/40885610/102777993-08fcbf00-4392-11eb-853f-7ed36dce48c7.png)

**Comment by codebrainz** [comment]
@etkaar nice work.

> Should we then close this issue or link it to a specific "tutorial page"?

If you're willing, I would suggest to post a [HowTo on the wiki](https://wiki.geany.org/howtos/start).
