### ISSUE TITLE
geany not merge local NF_XX_XX  build-menu items for filetypes

### ISSUE THREAD

**Issue by djadala** [geany/geany#2740]
Hi,
Arch linux, 
```
geany --version
geany 1.37.1 (built on 2021-01-05 with GTK 3.24.24, GLib 2.66.4)
```
with all plugins disabled,
If i edit file /usr/share/geany/filedefs/filetypes.go and add :
```
NF_02_LB=Install  3
NF_02_CM=go install
NF_02_WD=

```
geany correctly display this item in build menu,
but if i made these edits in ~/.config/geany/filedefs/filetypes.go,
these changes are not in build menu,
but changes for FT_xx_xx and EX_xx_xx are there, only NF are missing.

Regards

**Comment by djadala** [comment]
and to clarify, there is no open project.

**Comment by elextr** [comment]
Filetype dependent non-filetype commands are only loaded from the project file, not from the user filetype file.  

I admit that the [wiki](https://wiki.geany.org/howtos/configurebuildmenu) article could be clearer when it says:

"As noted before, filetype dependent settings are only considered if the file currently selected in the editor matches the filetype the setting is for. For settings in the filetype file, clearly that is the filetype the settings are in, but for project settings both the filetype and non-filetype dependent settings are stored in the project file."

which is intended to indicate only the project file has those settings.

This was done to retain backward compatibility with the preceeding build settings operation where the user non-filetype settings are loaded from the user config file, not the user filetype file because, after all, they are non-filetype settings.  

The reason non-filetype commands were read from system filetype commands was because there was already some hard coded exceptions that checked the filetype and overrode the default "make" commands, so that was removed and it was generalised.

**Comment by djadala** [comment]
Thanks for explaining,
I still think it is good idea user to be able to override NF type commands when you are in some filetype,  but closing this as "it works as intended" :)

Regards
