### ISSUE TITLE
Plugin preferences greyed out on new install of geany on Linux mint

### ISSUE THREAD

**Issue by chrisaww** [geany/geany#2762]
Followed instruction to install plugins which appeared to run smoothly.
However the menu option under edit - plugin preferences is greyed out.
geany version 1.36.
geany.conf attached renamed geany.txt to enable upload
[geany.txt](https://github.com/geany/geany/files/6136831/geany.txt)
Please advise steps to correct position
Thanks in advance

**Comment by elextr** [comment]
How did you install Geany and plugins?

**Comment by chrisaww** [comment]
geany installed using mint software manager.
Geany plugins installed following instructions on geany plugins install page for ubuntu.
namely sudo apt-get install geany-plugins.
hope this helps.

**Comment by chrisaww** [comment]
geany installed using MINT software  manager.
Geany plugins installed as per geany plugin install guidance fro Ubuntu
sudo apt-get install geany-plugins
Hope this helps

**Comment by elextr** [comment]
Have you enabled any plugins under `Tools->Plugin Manager` ?

**Comment by chrisaww** [comment]
Part success: Have now enabled documentation generator and that has resulted in Edit->Plugin preferences being available for that pliugin.
Part failure : unable to access preferences for markdown plugin since it seems to be enabled by default and there is no option to disable it in Tools ->Plugin Manager. With that Plugin I expected to see a panel containing the formatted output
Thanks for your patience in responding to a novice in this area.   My I suggest  the documentation is improved in this area.

**Comment by elextr** [comment]
Not sure whats with markdown, since I don't have that plugin I can't help.

Why did you install Geany from Mint and plugins from Ubuntu? It would be better to use one package set from one distro.  Geany plugins is in the Mint software manager.

Apart from a few that are part of Geany, plugins are developed by individuals, all the collection is, is well, a collection for convenience, they are still individuals work, and as such so is the documentation (or lack thereof).  Also how they are packaged (as a single package or lots of individual ones) is again the distros decisions.

**Comment by chrisaww** [comment]
a) Linux Mint is based on Ubuntu. I have just looked at the software sources and ubuntu is included by default..
b) you may have markdown plugin installed by default see the following https://plugins.geany.org/markdown.html. and try the filtype set command as shown on the page. or else load a file with extension.md. After all geany handles some filetype out of the box.
it does seem to me there may be a slight design error in disabling Tools->plugin  manager for pre-installed plugins.
I attach a sample.md file. with extension set as txt.
It would help me if you could help me if you have the same issue on your  setup. I would then feel happier knowing it is not just me. (README.md files are regularly associated with githib !!)
Thanks in advance.
[sample.txt](https://github.com/geany/geany/files/6143116/sample.txt)

**Comment by elextr** [comment]
@chrisaww as a Geany developer I build Geany/Plugins from Git, I don't install from distros, so I know what is/is not built and installed on my system, and Markdown Plugin is not built because I have not installed its build dependencies because I don't use markdown.  

Plugins can have inter-dependencies and, if another plugin depends on it, a plugin is no longer removable until the other plugin is closed.  That is not the case with markdown, but maybe markdown or another plugin is confusing something when it registers with Geany.

Since there are no other reports of markdown being permanently enabled I suspect it probably is just you, hence my concern you were mixing packages.  Try running Geany without any configuration `geany -c /tmp/does_not_exist` and see if it is still enabled. 

As I said above, plugins are created and maintained by individuals, not the Geany team (even team members are acting as individuals if they happen to maintain a plugin), so probably best to report it on [geany-plugins](https://github.com/geany/geany-plugins) where the markdown plugin is maintained.

**Comment by elextr** [comment]
> It is slightly misleading having the web page up but no libraries installed.

I don't understand what you mean? Which webpage?

**Comment by chrisaww** [comment]
The web page I am referring to is Plugins for Geany [install]

| 
| 
|  | 
Plugins for Geany [install]


 |

 |

 |


I have now established that following the get single plugin for ubuntu returns 
 Unable to locate package geany-plugin-Markdown
Matthew Brush has pointed me to the source downloads page and I now have the source for the Markdown plugin.
I just suspect some finger trouble behind the compiled code web page means the Markdown plugin is not available.Hoping to be helpful
Fully appreciate all your effortsChris  

    On Tuesday, 16 March 2021, 19:25:17 GMT, elextr ***@***.***> wrote:  
 
 



It is slightly misleading having the web page up but no libraries installed.


I don't understand what you mean? Which webpage?

**Comment by elextr** [comment]
Still don't understand which webpage, please provide a link or at least the URL.

**Comment by chrisaww** [comment]
:https://plugins.geany.org/install.html
Dummy colon installed at start of url to prevent auto processingregardsChris Walker

    On Tuesday, 16 March 2021, 19:49:34 GMT, elextr ***@***.***> wrote:  
 
 


Still don't understand which webpage, please provide a link or at least the URL.

**Comment by elextr** [comment]
> It is slightly misleading having the web page up but no libraries installed.

Thats the Plugins collection project website, its not specific to your install, or even to Ubuntu/Mint or other distribution.  So its not going to change just because you don't have the libraries installed for markdown.  

As I said above, the Geany project doesn't make the distribution packages for Ubuntu/Mint (or any distribution).  So I don't know why markdown is not provided by them, for example it is available on [Fedora](https://fedora.pkgs.org/32/fedora-updates-x86_64/geany-plugins-markdown-1.37-1.fc32.x86_64.rpm.html).  Perhaps Ubuntu/Mint don't provide some dependency of the plugin, so they can't make it available.  That has happened in the past, and perhaps it has again.  Or maybe the packager just made a mistake.

**Comment by chrisaww** [comment]
The general advice provided by Linux Mint community  about Ubuntu packages is as follows:'Linux Mint comes in two flavours. One is based on Ubuntu, the otherone (LMDE) is based on Debian. The Ubuntu based version (the defaultone) is guaranteed to work with Ubuntu packages.' 

My apt-get command is only configured to use either Ubuntu or Mint repositories. 
So I still think the steps I took were appropriate.
I strongly suspect the web page owner is not the one who loads the repositories with the geany- plugin packages, but the individual needs to be aware the markdown package has not been included and it would help future users to be aware of the limitation.
I have raised a question with Ubuntu to understand if this was a positive decision to omit that plugin. 
Going back in time (several years) I have found another plugin was suspended due to webkit dependancy version issues. 
As I have a work around using a python library rather than taking up too much time of others, I have closed to comment. If I get a clear response from Ubuntu I shall forward it to Matthew in the spirit of being helpful


    On Tuesday, 16 March 2021, 20:15:15 GMT, elextr ***@***.***> wrote:  
 
 



It is slightly misleading having the web page up but no libraries installed.


Thats the Plugins collection project website, its not specific to your install, or even to Ubuntu/Mint or other distribution. So its not going to change just because you don't have the libraries installed for markdown.

As I said above, the Geany project doesn't make the distribution packages for Ubuntu/Mint (or any distribution). So I don't know why markdown is not provided by them, for example it is available on Fedora. Perhaps Ubuntu/Mint don't provide some dependency of the plugin, so they can't make it available. That has happened in the past, and perhaps it has again. Or maybe the packager just made a mistake.
