### ISSUE TITLE
"Long line marker" does not match line length for different fonts

### ISSUE THREAD

**Issue by w3lifer** [geany/geany#2811]
For example:
- if I set the font "Ubuntu **Mono** Regular" with a size 12 and  "Long line marker" column value to 80, then 80 characters will match "Long line marker"
- if I set the font "Ubuntu Regular" with a size 12 and  "Long line marker" column value to 80, then 80 characters will **not** match "Long line marker"

![1](https://user-images.githubusercontent.com/14075412/118899628-d42c6e00-b917-11eb-87a3-11826620beec.png)
![2](https://user-images.githubusercontent.com/14075412/118899629-d4c50480-b917-11eb-801b-b2c0f89f5acc.png)
![3](https://user-images.githubusercontent.com/14075412/118899630-d55d9b00-b917-11eb-9e6a-66d2b1130d06.png)
![4](https://user-images.githubusercontent.com/14075412/118899631-d5f63180-b917-11eb-9889-2a0f5b1bd7ab.png)

**Comment by elextr** [comment]
Ubuntu regular is a variable width font, different characters have different widths.  Therefore its not possible to draw a continuous straight vertical line through a specific column since the position of that column depends on which characters exist in the lines. 

The vertical line is drawn at the position as if all the lines contained all spaces.

When you use a "mono" font is its monospaced, ie all characters have the same width, so column 72 of a line of spaces is the same as a line of `a`s or `z`s or anything and it works.

**Comment by w3lifer** [comment]
For those looking for a specific font, `DejaVu Sans Mono Book` is a good choice.
