### ISSUE TITLE
Cursor moved to search box?

### ISSUE THREAD

**Issue by janp20** [geany/geany#2838]
This is a very newbie question, I suppose, but why the cursor is not moved to the search box on CTRL-F?
Other programs normally move the cursor to the search box allowing to type in the phrase to search for while by default geany leaves the cursor inside the code window and this is not good. Is there a way to change this behavior?
Thank you

**Comment by elextr** [comment]
Not newbie, but WFM, on `<ctrl>f` the word under the editor cursor is put in the search box and selected so by default typing will replace it all.

What _is_ newbie is not providing any information on the version of Geany and GTK and OS from the `Help->Debug Messages` that look like this:

```
08:41:52: Geany INFO		: Geany 1.38 (git >= b524a58e), en_AU.UTF-8
08:41:52: Geany INFO		: GTK 3.24.20, GLib 2.64.6
08:41:52: Geany INFO		: OS: Linux Mint 20 (ulyana)
```

**Comment by janp20** [comment]
Ops, you're right 

Geany INFO		: Geany 1.37.1, en_US.UTF-8
Geany INFO		: GTK 3.24.29, GLib 2.68.3
Geany INFO		: OS: Arch Linux

I thought it was a FAQ since, as far as I can remember, this problem has been always there. I am using xfce with focus follow mouse and without the "automatically give focus to newly created windows" option (I tried to use it to solve this problem but it brought me others since it is a  desktop option). 

Geany should override the default desktop behavior in this case, and give focus to the search box.

![geany_searchbox](https://user-images.githubusercontent.com/63359862/124690445-80cbaa80-deda-11eb-854d-53d2ebfb6091.gif)

**Comment by elextr** [comment]
I'm afraid you just answered your own question, you told the window manager (WM) to do it.

I also have "follow cursor" set (Cinnamon not XFCE) and if I do `<ctrl>f` the focus moves to the dialog ... so long as I don't bump the mouse, then it moves back to the main window as I asked the WM to do.

Geany does request the focus to the dialog, and it goes there, but the WM can override it at any time, and in Cinnamon it seems that any mouse movement causes it to re-focus, but maybe XFCE is more authoritarian, or uses a timer to decide to refocus or something.

Anyway its not under Geany's control AFAICK since WMs can always override focus at any time, and as I said we do issue `gtk_widget_grab_focus(find_dlg.entry);`

**Comment by janp20** [comment]
Hi, first of all thank you for your answer. Anyway I think that some solution to this problem will be very useful. I looked a bit at the code and noticed that making both the search and the search/replace dialog modal could solve the problem. What do you think?

**Comment by elextr** [comment]
Those dialogs are deliberately not modal so that they do not need to be closed to do editing between uses.  That is an especially important use-case with find.  So, no, making them modal isn't an option.  Also modal doesn't work on all platforms IIUC.
