### ISSUE TITLE
Tab switch disk check

### ISSUE THREAD

**Issue by elextr** [geany/geany#2861]
Why is a disk check on tab switch only done if the switch is from the tab menu, not clicking the tab?  Surely it would be better for it to happen every tab switch so the file changed infobar comes up immediately on switch?

**Comment by eht16** [comment]
For me the disk check happens when switching the tab, no matter in which way I change it.
And the code looks like this too: https://github.com/geany/geany/blob/master/src/callbacks.c#L467

We check the disk status in the GtkNotebook page switch signal handler. I'm curious what it is what is causing the behaviour you describe.

**Comment by elextr** [comment]
Ahh, thanks, I missed the "after" callback. Fine.
