### ISSUE TITLE
Geany crashes with a regexp

### ISSUE THREAD

**Issue by InfoLibre** [geany/geany#3066]
Linux Mint Cinnamon 20.2
Geany 1.36

I open the joined file (unzip it before).

[Recherche morhange.html.zip](https://github.com/geany/geany/files/7769819/Recherche.morhange.html.zip)

I do this "search and replace":

![Capture d’écran du 2021-12-23 15-26-40](https://user-images.githubusercontent.com/3955499/147253748-ec80a9d2-9f8f-44ec-aa34-2d241f7b01c1.png)

I click on "In the document" button and then Geany crashes.

**Comment by InfoLibre** [comment]
mcedit crashes too with this regexp.

**Comment by elextr** [comment]
Your regular expression makes a capture for every character in the file, so you probably ran out of memory, ditto mcedit.

**Comment by InfoLibre** [comment]
MemTotal:       24553444 kB

Only Geany crashes and quit, nothing else is crashing.

**Comment by elextr** [comment]
GDB says the crash is inside the system regex library and it looks like it runs out of stack which is usually limited to much less than the total available memory.  As its a system library Geany has no control over it.

**Comment by InfoLibre** [comment]
Where could I make a report for the regexp library? Or is it possible to add something in Geany to prevent the crash?

**Comment by elextr** [comment]
Since its a (recursive) loop in the regex code Geany can't do anything about it.  

I suspect the library (PCRE) can't do anything about it either.  You are simply asking for something that is too big for your available system stack, if you run the regex on a small file it will not crash because there is enough stack to do it.

But I doubt that regex is actually what you actually want to do anyway, making a capture for every character is unlikely to be what you want.
