### ISSUE TITLE
Persistent blocks?

### ISSUE THREAD

**Issue by Dim-Tim-1963** [geany/geany#3079]
Is it possible to implement persistent blocks in Geany?  Got used to them since Turbo/Borland Pascal and Delphi. :)

**Comment by elextr** [comment]
What is persistent blocks?  Even google doesn't seem to know.

**Comment by Dim-Tim-1963** [comment]
Aw, sorry.  This kind of block stay marked until a dedicated hotkey is pressed or until you start marking another block.  When you copy or move it, you don't have to use clipboard.  Most of "classic" IDEs have such option.

**Comment by elextr** [comment]
Scintilla (the editing widget Geany uses) defines the selection as the text between a specified "anchor" position and the current position so it follows the cursor, so not what you want.  But since other markers are available you might be able to make a plugin to provide the behaviour you want but its pretty unlikely it will happen in Geany itself, more likely would be that multiple selections would be supported.

Google results depend on what you have been searching for (that "algorithm" remember) I got one reference to an MC change request adding a "persistent blocks" option but with no documentation on what it was, and then google switched to persistent disk and memory and other persistents. Google persistently persisted in having no persistent memory of persistent blocks (on page one, who looks beyond that?).

**Comment by Dim-Tim-1963** [comment]
Well, quite clear, thanks.  Seems, implementing features in editors heavly depend on authors' background and habits.  For example, many users of VS Code many years beg for "virtual space" (aka cursor beyond EOL), but the authors seem to despise that idea.  Though VS itself has that feature.

**Comment by elextr** [comment]
> Seems, implementing features in editors heavly depend on authors' background and habits. 

Well of course, software is written by humans, so of course it reflects the people who write it.  But that will change when the AI takeover happens ;-P
