### ISSUE TITLE
Auto-close angle bracket support

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#3228]
I would really appreciate it if Geany could support auto-close angle brackets. They are pervasively used in C++.

**Comment by elextr** [comment]
See https://github.com/geany/geany-plugins/tree/master/autoclose

**Comment by waynelapierre** [comment]
> See https://github.com/geany/geany-plugins/tree/master/autoclose

Thanks for the info but I found it difficult to install such a plug-in. Would you consider adding native support for auto-close angle brackets? Parentheses, square brackets, curly brackets, and angle brackets are the four types of bracket, and Geany already supports three of them.

**Comment by elextr** [comment]
IIUC its not provided because `<` and `>` are greater than and less than in C and thats all.  

If Geany supported `<>` autocomplete it might be used for HTML, never mind C++, can't have that. [end sarcasm]

Probably more useful to explore why you can't install the plugins, but can't help with that as you havn't posted what OS or version of Geany.

PS Even on full fat IDEs with much C++ smarts autoclosing `<>` for templates gets confused, so you might be disappointed how ineffective it is even if its available, not to mention having to delete the autoclose when typing greater than and greater or equals in `if()`s.

**Comment by zhaolinlau** [comment]
> > See https://github.com/geany/geany-plugins/tree/master/autoclose
> 
> Thanks for the info but I found it difficult to install such a plug-in. Would you consider adding native support for auto-close angle brackets? Parentheses, square brackets, curly brackets, and angle brackets are the four types of bracket, and Geany already supports three of them.

It is very easy to install plugins

For windows version you just need to go here [https://www.geany.org/download/releases/](https://www.geany.org/download/releases/) to download the .exe plugin installer and just double click to run it.
![image](https://user-images.githubusercontent.com/68846168/183120064-55afe817-2d17-422e-b5ad-f83d2fd4f9b6.png)

For ubuntu os just simply run `sudo apt-get install geany-plugins` and debian os is `apt-get install geany-plugins`
![image](https://user-images.githubusercontent.com/68846168/183120564-ff66ab56-7e6c-4154-88a4-31d2a1dbad57.png)

 Full list of linux os command to download geany plugins can simply find here:
[https://plugins.geany.org/install.html](https://plugins.geany.org/install.html)

**Comment by zhaolinlau** [comment]
this issue can be closed already
