### ISSUE TITLE
How do I set line wrapping to where the guideline is?

### ISSUE THREAD

**Issue by PhilAtKC** [geany/geany#3243]
Installed Geany on MacOS and saw this. It is wrapping, but not where the guideline is.

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/93122417/182437540-512f68b1-0e2b-4f85-ab31-e44237f9ef22.png">

**Comment by elextr** [comment]
Two points.

1. turn line wrapping on/off for the current document, `Document->Line Wrapping` or by default for [newly opened documents](https://www.geany.org/manual/current/index.html#features)
2. wrapping only happens at the edge of the window, not at the long line marker.

**Comment by PhilAtKC** [comment]
First one is addressed so I guess my second question is, can I put in a feature request for point 2?

**Comment by elextr** [comment]
Just a comment, personally I don't see why you want a blank space to the right of the window past the long line marker.  Wrapping is impermanent, it is not saved in the file in any way, so where it wraps on screen doesn't seem very useful except at the edge of the window.

**Comment by PhilAtKC** [comment]
Yes I wouldn't want a blank space there for personal work, but I can't say the same for all text files that I could potentially work with (log files etc). So having this helps with readability in that case. Feel free to close this for now, I don't imagine I would get to contacting Scintilla anytime soon (or leave open for tracking purposes, leave it up to you)

**Comment by kugel-** [comment]
@PhilAtKC do you really mean line wrapping at the indicator or (automatic) line *breaking*? Line wrapping is purely visual, i.e. just so that long lines aren't hidden after the visible area (requiring the user to scroll).

Line breaking really inserts newlines in the buffer. For this I could imagine automatic breaking to be useful in *very few* cases. However, most of the time this risks to introduce syntax problems or otherwise unreadable code. And there needs to be a way to overrule the line break on some occasions because it's never going to be perfect for everyone.

So, the answer to your original question is "you don't" as we don't support it today. I'm sorry about that. If you want support for it please open a PR.

**Comment by eht16** [comment]
@PhilAtKC 
Geany actually can do automatic line breaking: to activate use Document->Line Breaking.
In the preferences dialog on the Editor tab, there is a setting "Line breaking column" where you can configure at which column Geany should insert a line break.
