### ISSUE TITLE
Update Scintilla to 5.3.0

### ISSUE THREAD

**Issue by data-man** [geany/geany#3274]
Currently Geany uses version 5.1.5.

The most important changes are:
>Version 5.2.0 adds multithreaded layout to significantly improve performance for very wide lines.
Version 5.2.1 fixes leaks on GTK.
Version 5.2.2 on GTK, scroll horizontally with Shift + Scroll Wheel.
Version 5.2.3 adds 64-bit safe APIs and fixes scrollbar on GTK with Xorg.
Version 5.2.4 fixes failures on GTK with multi-threaded layout.
Version 5.3.0 adds change history.

"change history" seems the most interesting.

**Comment by data-man** [comment]
I can do appropriate PR if it will be accepted.

**Comment by eht16** [comment]
Sure, that would be great.

Please note the https://github.com/geany/geany/blob/master/scripts/update-scintilla.sh script which makes the update quite easy.

**Comment by elextr** [comment]
> Please note the https://github.com/geany/geany/blob/master/scripts/update-scintilla.sh script which makes the update quite easy.

But please note that script also updates lexilla lexers where the real work is.

You have to check the mappings from Scintilla lexers to Geany highlighting in https://github.com/geany/geany/blob/master/src/highlightingmappings.h for every language that has a change to its lexer since the last version in Geany.
