### ISSUE TITLE
control modifier with del/bkspc around multiple spaces should not delete the trailing word

### ISSUE THREAD

**Issue by goyalyashpal** [geany/geany#3323]
* ( `control delete` before ) or ( `control backspace` after ) multiple spaces deletes all those spaces - as well as the trailing word in the direction (i.e. following word for delete, or preceding word for bkspc) too
* due to this, there's no quick way to delete the indenting/aligning spaces

how other applications handle it:
* notepad3: treats space as a separate word for `ctrl del`, has same behaviour as geany for `ctrl bkspc`
* vscodium: treats single space to be part of next word, treats multiple spaces as a separate word for both these

Video: [link](https://user-images.githubusercontent.com/19423063/197528755-3e226f59-8a35-4c55-8b69-adb800a2056d.mp4)

version: Geany 1.38

**Comment by elextr** [comment]
> control delete before multiple spaces deletes all those spaces - as well as the following word too

Well, ctrl-delete is delete to end of word, so for sure it eats the word :-)

This is a default keybinding inherited from Scintilla.

> due to this, there's no quick way to delete the indenting/aligning spaces

Indents use ctrl-i and ctrl-u.

But aligning using "delete whitespace to next word" might be a useful addition and can be done with a plugin,  I think Scintilla has an option to behave as you described, but its simply not the default.

Did you check that none of the plugins in Geany-plugins does it?  Addons has many little bits, but there are other plugins that add different things too.

PS don't post videos, if you don't describe what you want people to notice, they may not notice it, and if you describe it there is no point in the video.

**Comment by yashpalgoyal1304** [comment]
_self hiding as either offtopic/resolved_

> PS don't post videos, if you don't describe what you want people to notice, they may not notice it, and if you describe it there is no point in the video.

makes sense, i guess the reason here being that textual description is generally enough to completely describe the matter

**Comment by yashpalgoyal1304** [comment]
> I think Scintilla has an option to behave as you described, but its simply not the default.

oh, notepad3 (mentioned in the description) is also scintilla based - so, maybe that can be probed in?

**Comment by elextr** [comment]
As I said I think Scintilla already has the option so somebody just has to add the capability to a plugin (or Geany itself if there is an option so the current behaviour is also available, but people complain there are too many options already, so a plugin is better).

PS I noticed you closed previous issues when I said somebody has to do it.  To be clear, Geany is a totally volunteer project, there is no corporate or dedicated individual backing it, so nobody can be directed to implement any feature request, nothing happens unless somebody contributes it.

**Comment by yashpalgoyal1304** [comment]
> PS I noticed you closed previous issues when I said somebody has to do it

* I totally get that it's a volunteer driven project - most FOSS I use are this way.
* the closing action by me is not specific to geany repo - i've closed around 50 issues in last several days
* anyways, now that u mention this, and as you've been kind, I'll explain it to u:

### Why (motive)?: 
To put it concisely: 
* To make things a bit more mechanised & determinisitic, & to keep my emotions in check.

Read further for details:

### Why-why (the reason behind): 
* To put time and efforts into an issue, waiting for months hanging in between, to hear no response, while still having to respond to avoid getting staled and in the end still getting it closed eventually as stale and "fixed" by <b>a stupid outdated bot</b> - without any way to re-close as "not planned". No no, no thanks.

### Evaluation (of implications of action):

Closing issue is a total harmless way that: 
* yeah, it has reached a conclusion (be via discussion, or lack thereof), and I am done with it till any further activity
* if nobody cares about the issue then good - 'ts closed already
* else if somebody cares (i.e. 'ts important for the project, or someone able comes over), then even better as <b>it can be reopened just like that</b> - I do NOT put any restrictions on reopening. <i>(but it seems people assume otherwise for the latter for reasons unknown)</i>.

That is, it:
1. covers both the cases very well 
2. fails only in searching for those issues - but the issue tracker is responsible for that with lack of filter & UI button for it.

**Comment by yashpalgoyal1304** [comment]
this behaviour applies on the trailing ampersand too, so, in the following, everything up till "this" gets cleared

* `this word & _` by `^bkspc`
* `_ & word this` by `^del`

here, `_` shows the position of cursor
