### ISSUE TITLE
Remember open documents without clean exit

### ISSUE THREAD

**Issue by willw1** [geany/geany#3324]
If geany has a clean shutdown using Quit from the file menu, it remembers which documents are open, and reloads them when it is next restarted. This doesn't happen in the case of a forced quit, such as my computer freezing and needing a reboot (which unfortunately happens fairly frequently for me). Is there any way to force the config file to be updated periodically to record the currently opened documents?

**Comment by elextr** [comment]
> Is there any way to force the config file to be updated periodically to record the currently opened documents?

Not AFAICT.

The git version of Geany has split the session files from the preferences.  If `configuration_save_session_files()` was added to the plugin API maybe the save-actions plugin could save it on the timer as well.

**Comment by cousteaulecommandant** [comment]
Does #2114 solve this issue?  I remember having this problem in the past, but learning a few months ago that it no longer happened due to that PR.  Or did the split elextr mentioned make this problem reappear?

**Comment by elextr** [comment]
AFAICT the session is still saved soon after files open and close after the split, so it should significantly improve it if not "solve" it.

Of course the LTSbuntu 20 and derivatives were(are?) still proffering 1.36 so that PR may not have been incorporated in the version the OP was using.

Will close and OP can recomment if it is still a problem in current version.
