### ISSUE TITLE
Feature Request: Place "reload etc" popup buttons to the middle instead to the right.

### ISSUE THREAD

**Issue by sushi2503** [geany/geany#3349]
Hello,

It would be nice to be able to place the reload file & etc buttons to the middle of the page instead to the right. Sounds more natural and at the same distance for right or left-handed.

Thanks for reading.

**Comment by elextr** [comment]
I presume you mean the toolbar.

AFAICT GTK does not provide any packing options for buttons in toolbars, and even if there is a way of specifying it for buttons in a toolbar only [start and end](https://docs.gtk.org/gtk3/enum.PackType.html) are available, not centre.

**Comment by elextr** [comment]
Thats a GTK infobar, and it explicitly only supports buttons at the end, see [here](https://docs.gtk.org/gtk4/method.InfoBar.add_button.html).

**Comment by elextr** [comment]
I don't think its possible, and since the infobar is deprecated in GTK 4.10 I doubt they will add any capability.

**Comment by elextr** [comment]
> But till GTK 4 arrives there is no possibility to move these buttons ? 

Not as far as I can tell.

> How you gonna do if the infobar will be deprecated ?

Well, its the least of the issues for GTK4, its only deprecated, it __shouldn't__ be removed until GTK5, the problem is the widgets that are deprecated in GTK3 and removed in GTK4 and other non-backward compatible changes in GTK4.  But that will take a GTK expert to contribute fixes to both Geany and Scintilla.
