### ISSUE TITLE
Help -> Report a bug is a no-op on Ubuntu

### ISSUE THREAD

**Issue by jorisgeer** [geany/geany#3375]
In Ubuntu 22.04, help -> report a bug is s no-op
website, wiki, donate are no-ops as well
This is Geany 1.38

**Comment by elextr** [comment]
WFM

The menu item opens the relevant page of the [Geany website](https://geany.org/support/bugs/) in whatever browser is configured, default firefox.  If that browser is not installed, is not in your path, or it doesn't work it won't the menu item doesn't work.  Probably the latter since the former should get an error asking for a new browser command.

**Comment by eht16** [comment]
@jorisgeer check Preferences->Tools->Browser to see what is configured there. Additionally, you might have a look in Help->Debug Messages to see if there are any error messages after you have clicked one of the Help menu links.

Feel free to re-open if it still won't work.
