### ISSUE TITLE
Run R codes in Geany 

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#3376]
When I press F5, my Python codes will be executed in Geany. However, this does not work for R codes, although R files are supported by Geany.

**Comment by elextr** [comment]
Because the R filedef does not define any build/execute commands.  

Since Geany devs are not Rists (AFAIK) "somebody" who is should contribute such a command (if there is a standard one).

You can set the commands yourself `Build->Set Build Commands->Execute commands` test it out then contribute a PR.
