### ISSUE TITLE
2x Speed Issue When Scrolling

### ISSUE THREAD

**Issue by x057** [geany/geany#3420]
It has taken me over a month to be able to even reproduce what I'm calling a bug. This has to do with the vertical scrollbar and the mouse cursor when still over the scrollbar, and long left clicked.

When you place your cursor anywhere on the vertical scrollbar then **long**-left click, you'll see the scrollbar reduce in width by about 2px. If you've not yet released the left button, you can keep scrolling right off the scrollbar, right smack-dab onto the Geany Interface (UI). After the left-long click, the scrollbar moves at almost 2x slower the speed than the mouse cursor does.

The transitioning effect on the scrollbar looks like it might be GTK+ related and possibly not a bug at all, but I am reporting this because in my world of development, I would call being able to control the scrollbar from outside of a document window, a mistake. If this is a feature, can someone please tell me how to have Geany not respond to long clicks while I happen to do it on the scrollbar by accident?

This is a Windows binary
The Geany version is 1.3.8

Thank you!

**Comment by elextr** [comment]
Can reproduce on current Git geany on Linux ... and with Xed, and with Gedit and any other GTK app I tried.  The narrowing happens when the mouse cursor is moved off the scroll handle a small amount while holding it (left mouse depressed), then the speed reduces.

So its a GTK thing, but is it deliberate?

From [this](https://blog.gtk.org/2017/10/11/a-scrolling-primer/) looks like it is, my emphasis:

"There’s more to scrolling in GTK+ that you may not know about. One feature that we introduced long ago is a ‘zoom’ or ‘fine adjustment’ mode, which slows the scrolling down to allow pixel-precise positioning.
To trigger this mode you can either use a __long press__ or shift-click in the slider. As you can see in the video, once you move the pointer below or above the scrollbar, it will keep scrolling at the same relaxed speed until you let go."
