### ISSUE TITLE
Mingw-w64 CI fails

### ISSUE THREAD

**Issue by techee** [geany/geany#3461]
This is the end of the end of the build log:
```
Command line defined: "GEANY_INSTALLER_NAME=geany-1.39_ci_20230416143039_83b8f7b_setup.exe"
Command line defined: "GEANY_RELEASE_DIR=/build/geany-release"
Command line defined: "GEANY_THEMES_DIR=/build/geany-themes"
Command line defined: "GTK_BUNDLE_DIR=/build/gtk-bundle"
Processing config: /etc/nsisconf.nsh
Processing script file: "/build/geany-build/geany.nsi" (UTF8)
File: "/build/geany-release\bin\*Geany*.dll" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/build/geany-build/geany.nsi" on line 144 -- aborting creation process
Error: Process completed with exit code 1.
```
It appears it started happening after https://github.com/geany/geany/pull/3432. @eht16 Any idea what could be wrong?

**Comment by eht16** [comment]
Not yet.
I debugged it a bit and noticed that some change in MSYS2 in the last few weeks causes that no shared libraries (in this case .dlls) are built anymore. Still the `make` succeeds without error.

I'm not sure what's going on. https://github.com/geany/geany/pull/3432 was also my first guess but it happens also on my native Windows system where none of these changes are relevant.

To me it seems to be caused by MSYS2 as I didn't change anything on the Windows system except updating MSYS2. I'll try to track it down further and/or open an issue in MSYS2 asking for help.

**Comment by eht16** [comment]
See https://github.com/msys2/MINGW-packages/issues/16836

**Comment by revelator** [comment]
looks like something causes libtool to bugger out, try adding lt_cv_deplibs_check_method=${lt_cv_deplibs_check_method='pass_all'} to /etc/config.site
or export lt_cv_deplibs_check_method='pass_all' to the PKGBUILD build section.
