### ISSUE TITLE
Error backing up a file located on a network drive (sshfs-win)

### ISSUE THREAD

**Issue by plegrand1** [geany/geany#3513]
Hello,
I use Geany regularly with satisfaction.
I have a problem when editing a file located on a network drive mounted with "sshfs-win" (https://github.com/winfsp/sshfs-win).

When saving the file, I get this error :
10:45:54: Error saving file (Error opening file "X:\info.php": Permission denied).

I have no problems editing a file located on a network drive (smb).

I've tested with another editor that I don't like as much, "Notepad++", and it doesn't have this problem.
Any idea how to solve this problem?

Thanks for your help.
Pascal

**Comment by elextr** [comment]
Try the various file saving settings, see https://wiki.geany.org/config/all_you_never_wanted_to_know_about_file_saving.  As that magnum opus also explains what each setting does it might help you to find whats wrong.

**Comment by plegrand1** [comment]
Hello and thank you for your reply.
I tried with the "use_atomic_file_saving" option as it is also indicated here https://github.com/geany/geany/issues/2445.
It works, but as the author says, the permissions of the saved file are modified:

**Before saving**
```
ls -al  /var/www/info.php
-rw-r--r-- 1 www-data www-data 59  7 juin  11:36 /var/www/info.php

```
**After saving**
```
$ ls -al  /var/www/info.php
-rwx------ 1 root root 65  7 juin  11:37 /var/www/info.php
```

**Comment by elextr** [comment]
Read the wiki article.  Try all the options, not just one.  

If one works, you are golden, if more than one works read the article again to understand the trade offs and choose the one you want to use.

**Comment by plegrand1** [comment]
As i said just before, it seems that diable all the 3 options
use_atomic_file_saving 
use_gio_unsafe_file_saving (default checked)
gio_unsafe_save_backup

make the job
Thanks for your help

**Comment by elextr** [comment]
> As i said just before, it seems that di(s)able all the 3 options ..

As you edited, but dear github doesn't notify of edits, so that information wasn't available when I replied :smile:

Well, with all three options off the simplest save is used, overwriting the existing file, which is probably what all the other editors do, but without giving you alternate options.  

But as the wiki article explains, saving that way means if your network stutters during saving you can end up with a truncated file.  Only you can decide if thats ok, a reliable local network is probably ok, but a remote connection might not be so safe, but you are the only one who knows.

**Comment by plegrand1** [comment]
Noted!
Now it's a bit clearer for me and I'm happy with the way it works.
Thanks again.
