### ISSUE TITLE
Set Path From Document isn't working properly

### ISSUE THREAD

**Issue by scriptum** [geany/geany#352]
After some time Set Path From Document stops to work. I looked through the code and sure that problem is somewhere in `vte_get_working_directory` with of pid = 0.

How to reproduce (not sure that will work for all configurations):
1. Restart Terminal
2. Restart Terminal again
3. Try to set path from different documents (especially with non-ASCII filenames).

Maybe this happens only with Russian locale. If not reproducible, try to run under `ru` or some other locale.

How could this be fixed:
1. Remove `if (! utils_str_equal(path, vte_info.dir))` check. Not sure that this is very necessary.
2. Check `vte_get_working_directory` logic. Sometimes `pid` variable becomes 0 and this causes a bug.
3. Check `vte_restart` - why do we need to kill shell? Also shells support `reset` command.

VTE and "Set Path From Document" also has a bug when I use C locale with Russian file paths: `cd '/home/rpg/?????????/?????? ?? GTK ? Cairo'` and so on.

**Comment by eht16** [comment]
#2116 should fix the original issue (Set path from document broken after VTE restart).
The reason for pid=0 was the removed `vte_start()` call which we removed long time ago because of a VTE bug. But the VTE bug has been fixed also long time ago, so we should explicitly start the shell again and so get a valid pid again and everything else will work again.
