### ISSUE TITLE
Long filenames in the window frame are unidentifiable in Cinnamon

### ISSUE THREAD

**Issue by ineuw** [geany/geany#3564]
Please, see the attached images of the differences between the title and the results of Geany and Pluma, and how they display the titles in Linux Mint Cinnamon. I use that info in my documents and as such, they are unidentifiable.

In Kubuntu KDE, the same filename is left aligned and displays the full title in Geany.

![230925 034127_geany](https://github.com/geany/geany/assets/10367016/60e42091-7c07-462f-82af-a08fe181587d)

![230925 034241_pluma](https://github.com/geany/geany/assets/10367016/3b207c03-b61c-4857-b8c6-e46ebe629c03)

**Comment by elextr** [comment]
For some weird reason the filename part of the window title is shortened to the setting in `Edit->Preferences->Interface->Notebook Tabs->Tab Label Length`.  So with the whole width of the window available (well less the directory path and the huge word Geany) the filename part is the same width as each of the multitude of tab labels.  

Probably the Kubuntu version has the tab width set larger, here the default seems to be 99999.

I think the presumption is that file organisation will be by directory, not structured filename, thats why the whole path is shown, but the filename ellipsized.

Probably it would be better to give the window title its own width setting, then it can be set to 99999 for all modern widescreens and no shortening will occur but the tab shortening setting will be unaffected.

But "somebody" has to do it.

**Comment by ineuw** [comment]
Thanks for the explanation and the quick reply. In testing various Cinnamon themes, it's common to all, but I needed to start with Geany to be thorough, and refute any misdirection.

**Comment by ineuw** [comment]
It took me awhile to realize the implications of what you meant. Geany window title reads the tab, and that is wrong. The current tab's abbreviated format should not be used in the window title because it's useless. So, my question is where do tabs get the filenames from before concatenation?

**Comment by eht16** [comment]
I don't know if I got all of the discussion here. I find the OP confusing as on the screenshot there is Geany and Pluma but the text refers to different distributions.

Anyway and apart of personal preferences about this feature, the next release of Geany will contain the setting @elextr mentioned in https://github.com/geany/geany/issues/3564#issuecomment-1735263332 and then, @ineuw, you can set it to a very large value to disable ellipsizing altogether.

The new setting was introduced in #3365 because of #3344 and #2112.

**Comment by ineuw** [comment]
@eht16 thanks for the comments. I was always under the impression that a window title is provided by the theme. My script's output in two different editors shows that I was wrong. But the app window title should not be a copy the contents of the tab. Should a tab be 60 characters wide if the title is that long?

**Comment by elextr** [comment]
@eht16, #3365 adds the setting to ellipsize the tab filenames, thats fine.  

My comment (ok rant :-) above was that that setting is used for the filename in the window title as well [here](https://github.com/geany/geany/blob/b3dde4d21d55f97475b623f714a1156c8d2a46d9/src/ui_utils.c#L385).  

But the window title width is greater than the sum of the widths of the tabs, so it does not make sense to use the tab width for the window title.  So I am proposing that window title needs its own setting.  Maybe for now just don't limit the window title at all (use 99999 as a constant in the above line).

@ineuw you might have been confused because I had forgotten that the tab setting was added since 1.38 so unless you had a recent git version you wouldn't have had that setting either, sorry.

**Comment by ineuw** [comment]
Thanks for clearing it up. I don't have that setting. I installed 1.38 from the software repository, but will download the git.

**Comment by elextr** [comment]
Reopened as still needs the separation of the tab and window title widths resolved.

**Comment by ineuw** [comment]
Apologies for closing it. I am reading about the topic and understand the 30 character restriction because of multiple tab's width. I assume that now you must create another branch before concatenation? From where is the complete string extracted?

**Comment by ineuw** [comment]
Many many thanks. Installed the version 2, and it it's great.
