### ISSUE TITLE
symbols panels dont update list after switching files

### ISSUE THREAD

**Issue by fbrau** [geany/geany#3622]
This is happening with the new 2.0 version. The items are still clickable but are redirecting to the lines analized for the other file. The only way to make the panel update is by switching files from the Documents panel. 

I include the geany error messages related to not loading the old 1.38 plugins, which is perfectly fine. Still I include it in the screenshot maybe this has some indicence. Im running Linux. Compiled from source and installed in /tmp/geanytest,  I havent uninstalled 1.38 yet

![Captura_2023-10-20_12-03-27](https://github.com/geany/geany/assets/8375315/dc8bdc6e-0e12-4e85-a4c2-05eb0b14de34)

**Comment by techee** [comment]
I don't seem to be able to reproduce the issue here - switching to the other file shows its own symbols immediately. I'm also a bit puzzled by how your Symbols tab looks like - with Geany 2.0 you should see a filter entry in this tab, yet there is none in your case which looks like some older Geany (but the message in your screenshot clearly says Geany 2.0):

<img width="453" alt="Screenshot 2023-10-20 at 19 13 47" src="https://github.com/geany/geany/assets/713965/5905d083-99fb-4eef-937f-b00b426dfec5">

Also, if you compiled Geany in `/tmp/geanytest` you should check which `libgeany.so` is called in your case because the newly built executable could load the old library. (But then you are seeing "This is Geany 2.0" so it appears the new library was loaded.)

A bit mysterious...

Does the same happen when you run Geany without plugins?  `geany -p`

Also, have you compiled geany-plugins? It seems you did based on the block cursor as it seems vimode is running right? Are you sure you compiled it against the version you have in `/tmp/geanytest`?

**Comment by cwendling** [comment]
Just as puzzled here, but given 2.0 will not load older plugins, it's unlikely it's the issue…

Do you see the same thing using a fresh configuration, e.g. with `geany -c /tmp/tmpconf`?  If not, save your conf and see if you can share it.

**Comment by eht16** [comment]
One more guess: did you pass `/tmp/geanytest` with `--prefix` to `./configure`? If not, Geany would load the `geany.glade` file from your old installation and this would explain at least the missing filter entry @techee mentioned.

**Comment by techee** [comment]
> One more guess: did you pass /tmp/geanytest with --prefix to ./configure? If not, Geany would load the geany.glade file from your old installation and this would explain at least the missing filter entry @techee mentioned.

Really good guess - that could probably explain about everything because with the old glade file, weird things will start happening.

**Comment by fbrau** [comment]
> One more guess: did you pass `/tmp/geanytest` with `--prefix` to `./configure`? If not, Geany would load the `geany.glade` file from your old installation and this would explain at least the missing filter entry @techee mentioned.

That was it. I did a ./configure && make... but then I forced with a ./configure --prefix to do some tests before installing. The binaries were already pointing to /usr/local. Its all my fault
