### ISSUE TITLE
replace xterm with gnome-terminal

### ISSUE THREAD

**Issue by eexpress** [geany/geany#3703]
The xterm is small without configure it, and I do not like to make a .Xdefaults config for xterm any more. So I want replace the `xterm` with well work's `gnome-terminal`.

In `Preferences -> Tools -> Terminal`:
1. when I set as `gnome-terminal -e "/bin/sh %c"`, and click the **RUN** botton in toolbar to execute, the gnome-terminal is show, but the RUN botton can not display as an "STOP" icon, that's say I can not stop the running application by click the RUN button.
2.  when I set as `gnome-terminal -x "/bin/sh %c"`, it failure to lanuch.

I want click the button to run, click again to stop.

**Comment by elextr** [comment]
> but the RUN botton can not display as an "STOP" icon, that's say I can not stop the running application by click the RUN button.

IIUC `gnome-terminal` is a front end for `gnome-terminal-server`.  The server shows the terminal screens and `gnome-terminal` just tells it what to show and exits.  Since Geany knows nothing about the server it watches the `gnome-terminal` process and when it exits it presumes the run is complete and switches the stop back to run.  Unless you can find options that tell `gnome-terminal` not to behave like this there is not much Geany can do.

> when I set as gnome-terminal -x "/bin/sh %c", it failure to lanuch

Thats a `gnome-terminal` problem, nothing to do with Geany, but I think it expects a list of arguments, not a single string.  Also `-x` is deprecated.

**Comment by b4n** [comment]
IIRC gnome-terminal has an option like `--disable-factory` or similar not to connect to a running instance, if that's indeed the issue.

**Comment by elextr** [comment]
[This](https://manpages.ubuntu.com/manpages/jammy/en/man1/gnome-terminal.1.html) was what google found for me, maybe a newer version has that option.

**Comment by b4n** [comment]
Ok so maybe `--wait`?

**Comment by elextr** [comment]
Works for me `gnome-terminal -e python3` returns immediately and a window with python REPL pops up, but `gnome-terminal --wait -e python3` does not return until after the Python REPL is exited.

Note `-e` is also deprecated, @eexpress use `--` and look at how the arguments need to be structured.

**Comment by eexpress** [comment]
> `-e` is also deprecated,

OMG.

**Comment by eexpress** [comment]
> Ok so maybe `--wait`?

Thanks. --wait is works.
