### ISSUE TITLE
Please provide an official and ready to use dark theme for the UI

### ISSUE THREAD

**Issue by iahung3** [geany/geany#3781]
Old thread: https://github.com/geany/geany/issues/2928 (closed)

**Comment by elextr** [comment]
There is no official theme for Geany, its whatever your selected GTK theme is.  If you mean "colour scheme" for the editor then see the misnamed [geany themes](https://github.com/geany/geany-themes) repository.

**Comment by elextr** [comment]
PS if you are on Windows there is a theme provided because so many people hated the GTK default dead tortoise (Adwaita, google it) theme and Windows users couldn't be bothered to download alternate GTK themes, but the argument and disagreement that went into getting to that makes the chances that anyone will provide a dark version fairly low without an actual pull request and sufficient agreement.

**Comment by qlxxvi** [comment]
Go to your gnome instalation location `~\geany\share\themes\Prof-Gnome\gtk-3.0` and change name of `gtk` file to 'gtk-dark'.
![Zrzut ekranu 2024-07-22 180406](https://github.com/user-attachments/assets/f0371c2d-b9ff-4f0d-975c-50a7cf20a75e)
![Zrzut ekranu 2024-07-22 180452](https://github.com/user-attachments/assets/4e35319c-2155-4f1c-985d-59b20aea648b)
