### ISSUE TITLE
Make default tab width standard 8 characters

### ISSUE THREAD

**Issue by drws** [geany/geany#3790]
As @elextr already [pointed out](https://github.com/geany/geany/issues/1379#issuecomment-275570440) in #1379 standard tab width is 8 characters. However, Geany uses 4 by default for some reason. The proposal here is that the default should rather be standard than not, meaning changing it to 8 characters instead of the current 4. Just to make Geany "100% ASCII-compatible" with its default settings.

**Comment by elextr** [comment]
I would also point out the rant at the end of the linked comment.  New projects should not be using tabs, and spacing indent widths can usually be automatically detected.  Olde projects that use tabs and are not gonna change will be used to it by now.

Tabs being 8 is not "ASCII" compatible, its clattering physical typewriter/teletype compatible, which chose 8 because there were only a limited number of physical mechanical stops and dividing evenly across an 80 character punched card gave 8.  Punched cards, a good model for Hidpi screens ... not. :wink: 

Geany does not enforce any "standards", and defaults are suitable for its own formatting, and thats tabs=4.  Also 4 is the default tab size for other IDEs like vscode, eclipse etc so its not like Geany is an outlier.

Given that it hasn't changed for the nearly two decades (wow!) of Geany existence its unlikely to change now so closing, can be reopened if somebody made a cogent reasoning why it should be changed.

**Comment by drws** [comment]
Whatever the reason behind, the basic standard is 8 characters. 4-character width seems like a pre-HD pre-widescreen hack to make better use of screen real estate. Which we have plenty of now, besides wider aspect ratio. A bit more horizontal separation actually looks good/can be useful on HiDPI screens, so punched cards' standards might not be completely obsolete :).
