### ISSUE TITLE
When opening a document from a file manager, then the tab of the editor is not in focus

### ISSUE THREAD

**Issue by ralf3u** [geany/geany#3796]
**Steps to reproduce**
1. open a document in Geany
2. click on a tab-title of the sidebar
3. switch to a file-manager-window, like PCManFM-Qt
3. mark a TXT-document
4. press enter (result: the document appears in Geany)

**Result**
the tab-title of the sidebar is still in focus

**Expectation**
the tab-title of the editor should be in focus

**Remark**
same for the message window (so, do the test from above with the message window instead of the sidebar)

**System**
Lubuntu 23.10
Geany 1.38

**Comment by elextr** [comment]
Just a clarification first, in a notebook focus of the _tab_ is different to focus of the _contents_, and is different to the _current_ tab which is the one displayed, whichever has focus (tab or contents).  IIUC not all themes distinguish focussed tabs from current tabs so the difference might not be clear.  

Please be sure which you mean, in this case I will presume you do mean the symbols tab has focus, not the contents, and you actually want the contents of the editor to have focus, not the tab.

The results as described appear to be deliberate, the focus only shifts to the newly opened editor widget if the widget which has focus or would have focus if the window was focussed, is either of an editor widget or the symbols tab contents.

This makes sense since the open request is asynchronous, it can happen at any time, its not within Geany.  In your case it comes at a time when you are not interacting with Geany, but it might come from a background process while a user is using Geany, and there could be a dialog open in Geany or some other partly completed interaction.  

So to avoid causing issues by interrupting something (interrupting is rude and Geany is totally polite ;-) only if the focus is on or would be on a widget that will be changed by the open is the focus shifted to the newly opened editor.

**Comment by ralf3u** [comment]
>[...] you actually want the contents of the editor to have focus, not the tab.

Yes, that's right. My expectation was:
The cursor should blink in the content area of the editor while the tab-title of the editor should have the format that way, that one know that this is the current tab.

So, if you think this issue is invalid, I suggest that you close this issue.

**Comment by elextr** [comment]
Well, as I said, your expectations are met if the sidebar _contents_ or one of the editors was what was focussed before you switched to the file manager.  But for the reasons I explained above the focus is deliberately not moved from any other widget so its not really a bug or feature, and "invalid" is the only label we have to say that.
