### ISSUE TITLE
Plugin request: Run several linters

### ISSUE THREAD

**Issue by StrayFeral** [geany/geany#3799]
I want to be able to specify all linters I use for a specific language and either have them run automatically for the currently open file OR at least a single keyboard key-binding to run them all on the currently open file.

Currently I specify them all in the build-menu and I run them one by one.

Also - each linter should be run in background. Results should be parsed and displayed in the Status/Messages tab.

So for Python I use: mypy, flake8 and bandit. It is too tiring to run them all one by one from the build menu.

**Comment by elextr** [comment]
You havn't provided your platform, but on Linux multiple commands can be run from the build menu by separating them with semicolons, but I don't think Windows can do that and Macos I don't know.

But on all platforms and the recommended method is to put the multiple commands in a script and run that from the build commands.  Since you seem to be Python centred it could even be a Python script.

**Comment by StrayFeral** [comment]
I am on Lubuntu. Your proposed workaround works for me, so I will close this issue now.

**Comment by StrayFeral** [comment]
Closing issue
