### ISSUE TITLE
Windows: Geany does not update the UI text to be white on dark background/dark gtk-theme

### ISSUE THREAD

**Issue by HarrisonFld** [geany/geany#3827]
Using a gtk theme called Orchis in my AppData/Local/gtk-3.0 (https://itsfoss.com/best-gtk-themes/) and have also tried the gruvbox gtk theme (https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme).
Both themes have worked and produced the results depicted in the theme photos, except the UI text as depicted in the photo.

Anyone have a fix or can provide the settings in the geany conf that can fix this?

![image](https://github.com/geany/geany/assets/145621888/383dbe26-34f2-46ad-bc43-e11510886082)

**Comment by elextr** [comment]
There is probably something wrong with the theme, note the text in the document tree is white.  Customisations can be put in `Tools->Configuration Files->geany.css` but as this project isn't responsible for the theme we can't advise what you need to change, you will need to look at the theme and see what it sets for what elements.

**Comment by eht16** [comment]
I tested the Orchis theme and it looks good, I think:
![geany_windows_orchis](https://github.com/geany/geany/assets/617017/0a43ca17-41f1-45e3-b9f3-682f740c2c8e)

Since you said you installed the theme into `AppData/Local/gtk-3.0`, this might cause the problems. Usually, themes are to be put into `AppData/Local/themes` and then configured in `AppData/Local/gtk-3.0/settings.ini`, e.g.:
```ini
[Settings]
gtk-theme-name=Orchis
gtk-application-prefer-dark-theme=1
```

This worked for me. See also https://www.geany.org/documentation/faq/#on-windows_1.

Feel free to re-open if I'm wrong.
