### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ineuw** [geany/geany#3852]
Downloaded the current master file, tried to install it, and it failed what am I missing? 

> ineuw@lmcde:/media/logiciels/geany/geany-master$ ./autogen.sh
>
> **Warning**: I am going to run `configure' with no arguments.
> If you wish to pass any to it, please specify them on the
>./autogen.sh' command line.
>
> Processing configure.ac
> ./autogen.sh: 33: autoreconf: not found

**Comment by ineuw** [comment]
Installed the two required apps autoreconf and autopoint and it terminated with the following messages:

> autoreconf: running: aclocal -I m4
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: configure.ac: not using Intltool
> autoreconf: configure.ac: not using Gtkdoc
> autoreconf: running: /usr/bin/autoconf
> configure.ac:106: warning: AC_DISABLE_STATIC is m4_require'd but not m4_defun'd
> m4/geany-plugins.m4:5: GEANY_CHECK_PLUGINS is expanded from...
> configure.ac:106: the top level
> configure.ac:106: warning: LT_INIT is m4_require'd but not m4_defun'd
> m4/geany-plugins.m4:5: GEANY_CHECK_PLUGINS is expanded from...
> configure.ac:106: the top level
> configure:12873: error: possibly undefined macro: AC_DISABLE_STATIC
>      If this token and others are legitimate, please use m4_pattern_allow.
>      See the Autoconf documentation.
> autoreconf: error: /usr/bin/autoconf failed with exit status: 1

At this point I haven't installed the plugins.
 
![geany version](https://github.com/geany/geany/assets/10367016/0dcff13f-a3fa-45da-9fc8-1d7b0fb16e0c)

**Comment by b4n** [comment]
The [README](https://github.com/geany/geany?tab=readme-ov-file#using-autotools) should be a good start I believe.

**Comment by rdipardo** [comment]
@ineuw 

> There doesn't seem to be a simple direct installation method for users with limited knowledge, like myself.

Here is a copy-and-paste-able installation script (assuming you don't care about the API documentation), suitable even for [CI/CD deployments](https://github.com/rdipardo/fpgeanyplugin/blob/7250943f3a158e9d0cb9d4d9a5aa79dd3f755266/.circleci/build_geany.sh):

~~~sh
sudo apt update && \
sudo apt install --no-install-recommends \
    build-essential \
    autopoint \
    ccache \
    gettext \
    intltool \
    libtool \
    libgtk-3-dev
NOCONFIGURE=1 ./autogen.sh
mkdir -p _build && cd _build
../configure --prefix=/usr \
    --disable-html-docs \
    --disable-pdf-docs \
    --disable-api-docs \
    --disable-gtkdoc-header \
    --enable-binreloc=no
make -j4 && sudo make install && sudo ldconfig
~~~

**Comment by elextr** [comment]
@ineuw to be fair to us, you are not just installing, you are building and installing, and building is a development activity that assumes that you know enough to install the relevant tools, because its not the job of every project to teach the tools they use.

You have not specified what operating system you are trying to build on, but the script by @rdipardo looks like it will work on Debian like distros (untested) when run from the top level of the clone tree.

There was a PR to add the simplest build sequence to README, but it kept getting kibbitzed with "no it needs to do this", "should be out of tree", "its better to use the tools in this more complex way", etc etc so it was abandoned.

**Comment by ineuw** [comment]
@rdipardo, Thank you for the script. It went smoothly and all installation problems are solved, including the root version which I also use often. I also installed the plugins (2.0) and the themes in both.

@elextr I will post a separate reply later. 

![geany2_1](https://github.com/geany/geany/assets/10367016/772857f3-b076-485a-adf5-ab94d07d41d1)

**Comment by ineuw** [comment]
> @ineuw to be fair to us, you are not just installing, you are building and installing, and building is a development activity that assumes that you know enough to install the relevant tools, because its not the job of every project to teach the tools they use.
> 
> You have not specified what operating system you are trying to build on, but the script by @rdipardo looks like it will work on Debian like distros (untested) when run from the top level of the clone tree.
> 
> There was a PR to add the simplest build sequence to README, but it kept getting kibbitzed with "no it needs to do this", "should be out of tree", "its better to use the tools in this more complex way", etc etc so it was abandoned.

@elextr, I am not tuned in completely to the Linux culture where my expectations are wrong. My apologies. 

I will return to post the results of installing Geany 2.1 in a Linux Mint Cinnamon 21.3 installation.

Previously, I was unable to install 2.0, unless I installed 1.38 from the Debian/Ubuntu/Linux Mint software repository.

**Comment by ineuw** [comment]
Installed Linux Mint 21.3 on a spare drive and after updating the iso installation, installed @rdipardo's script, and followed with the latest Geany installation script of 'Yage' (or 2.1.) 

This may be a repeat installation because Linux Mint Cinnamon menu did not display the results of @rdipardo's installation script.

Then, installed geany-themes-1.24 and everything is working perfectly in a Debian installation of Linux Mint Cinnamon 21.3.

**Comment by elextr** [comment]
The desktop specification requires desktop managers (like Cinnamon) to search the list of directories in `$XDG_DATA_DIRS` for desktop files and use the first found only to add to menus, two applications with the same name cannot show in any desktop spec compliant menu.  Geany installs to `/usr/local` by default which will not overwrite the standard LM install in `/usr` but the `$XDG_DATA_DIRS` should have `/usr/local/share` before `/usr/share` in the list, so it should be shown in the menu in, not the LM default.  Check with `echo $XDG_DATA_DIRS` and check that `geany.desktop` appears in `/usr/local/share/applications`.

But you need to tell Cinnamon to re-scan those directories after an installation.  The standard Geany install (and therefore the script) doesn't do that.  This is because each desktop has a different way of doing it and the Geany install is desktop agnostic.  But LM installs know about Cinnamon and will re-trigger it.  So likely what happened when you installed something else was that Cinnamon was triggered to rescan and it found the install in `/usr/local`.

**Comment by ineuw** [comment]
Thanks for taking the time out to explain. It's much appreciated.
