### ISSUE TITLE
When closing the current tab, move to the tab on the left, not on the right

### ISSUE THREAD

**Issue by cousteaulecommandant** [geany/geany#3855]
If I open a new file temporarily to look at something and then close it immediately, the new file will open on a tab on the right of the current one, and when I close it Geany will focus on the tab on the right of this one, not on the one I originally had open which is the one on the left.
This could be solved if Geany defaulted to moving to the tab on the **left** when I close the currently active tab, instead of the tab on the right as it does now.

(This is assuming the user has their preferences set to "Open new tabs on the right of the current tab"; if they set them to open new tabs on the left, then the behavior should be mirrored and Geany should switch to the tab on the right.)

Alternatively, it could simply switch to the last open tab (emulating the behavior of Ctrl-Tab).

**Comment by elextr** [comment]
> Plus browsers are sort of crazy, so I don't think mimicking their behavior is necessarily a good idea.

+1, I just tried Chrome, sometimes it went to previous, sometimes to the one on the right, I can't tell what makes the decision.

I think (without checking) in Geany it is simply that since notebook tabs are usually referenced by number counting from left, when the current tab is closed and the tab number isn't changed the tab that was on the right will now be that number and so the current one.  So maybe there isn't any code for this, its simply what happens.

**Comment by b4n** [comment]
> Alternatively, it could simply switch to the last open tab (emulating the behavior of Ctrl-Tab).

*Preferences → Interface → Notebook tabs → Editor tabs → Switch to lasted used document after closing a tab* :wink:
