### ISSUE TITLE
error running geany at terminal as regular user

### ISSUE THREAD

**Issue by TheMCMan** [geany/geany#3931]
every time i want to run geany as a user in terminal it errors unill i kill all at-spi processes running under root...  ps aux | grep at-spi

**Comment by elextr** [comment]
Closed, No useful information provided, can be reopened if it becomes actionable.

**Comment by TheMCMan** [comment]
My bad, I originally installed geany from the Linux Mint Software Manager Repository.  I uninstalled that version and reinstalled like normal with the apt install geany command, and do not receive that error message anymore.

**Comment by TheMCMan** [comment]
My bad.  It's working now.  Had to uninstall the version i got from https://community.linuxmint.com/software/view/geany delete everything geany then use the right way apt install geany.  Bad versions of your distros are  available  in the Linux Mint GUI Software Manager that comes with every Linux Mint Cinnamon installation.  This must have been where the -i user got their flatpak version.  Because I started out with that one and got the same message and reinstalled geany as a Linux Mint System Package...  I bet a lot of people installed bad distros of your software from there.  So I had to install geany 3 times before I got it working... because of that bad distro.  

I'm thinking most people would have given up and moved on.  Meaning this is a lost opportunity to expand geany's user base.  Especially since I switched to Linux because of the end of  Win10 security updates in 2025.  Bought my brother a sweet ThinkPad 480T i7 laptop that can't run win10, for $200 from Amazon and put Linux mint on that one too.  In my opinion, Linux machines usage will expand the closer we get to Oct25.  And Linux mint installation and GUI make it really easy to use.  Kind Regards

**Comment by elextr** [comment]
The Geany project does not make the packages for Linux Mint or any distro.  Each has its own peccadilloes and the project does not have the expertise to support them.  Nor does the Geany project make the flatpacks in flathub, note the [unverified](https://flathub.org/apps/org.geany.Geany).  

IIUC LM22 (just released) will not show unverified flatpacks in its software manager by default any more, so the user has to make a selection with a big warning to see them.  The LM blog a couple of months ago explains the reasoning.

Geany is a volunteer project, people work on it because they want to, it is not in competition to "expand its user base".  This is an olde fashioned idea I know.
