### ISSUE TITLE
lines whitout spaces

### ISSUE THREAD

**Issue by lucasmz1** [geany/geany#3937]
how do I join lines without spaces ?
because every single time I click in join lines the joined lines has some spaces from word to word.

**Comment by elextr** [comment]
The use-case for join lines and reflow and related actions is for text source, so words separated by newline need remian separated, so by space instead.  Otherwise the words runtogether.

If instead you purely want to remove the newline you can ... delete the newline ... with delete :grin:.  Or for multiple lines use replace, with the escapes option selected, to replace `\n` with nothing.
