### ISSUE TITLE
Default tabs width

### ISSUE THREAD

**Issue by xinuzimi** [geany/geany#4004]
Hi,

My Geany = Geanastic :-)

One little thingy caught my attention recently (version 1.38), namely de default tabs width setting of '4'.

If you paste tabbed columns, from e.g. a terminal window, into geany they won't always render well with this setting.

In most cases tabs '11' seems to do the trick.

Furthermore users must read the top line that advises to click Project->Indentation to give the setting its overall effect.

Greatz.

**Comment by elextr** [comment]
There are many different widths of spacing for tabs, its not standardised, and different projects and different tools use different values.  So the tab settings in Geany are complex to attempt to assist accommodating the range of settings used.

So settings can be set Geany wide, or overridden by settings in individual projects, or both of those overridden by individual file settings (while the file is open in the session).  By default changing the settings does not modify the tab settings used by files that are open, Geany does not have any way of knowing that settings for open files are intended to changed, so the user has to specifically apply changes (as you have noticed since it is prompted to remind users).

So you can modify the settings yourself to meet your own needs, but the default setting is the one a majority of Geany contributors have agreed.  So it won't be changed.

[As a personal note, tabs are evil and stupid junk, they should be replaced in files with a specified number of spaces, so it will never change or be confused between projects or files or whatever.  Geany has a "Replace Tabs With Spaces" menu item to help it ;-)]
