### ISSUE TITLE
Please provide .tar.xz for Linux nightly builds

### ISSUE THREAD

**Issue by chadchoi** [geany/geany#4087]
And maybe for official release, too. I'm using Debian but I don't want to install the .deb packages. They will mess up with the Geany version I installed from Debian's repository. Providing .tar.xz will also benefit other Linux distros.

**Comment by eht16** [comment]
Are you talking about providing archives for the source code or binary builds?

Source code archives are already available at: https://download.geany.org/geany_git.tar.gz
Adding the archive packed with xz is easy but only saves a few kilobytes, I guess.

Providing binary builds is more complicated as even just for Debian we would need to support multiple versions additionally to the existing packages.

Did you try to just unpack the provided .deb packages? Though this might still cause issues because both Geanys are configured with "/usr" as prefix even if you unpack the nightly .deb into another location.

**Comment by chadchoi** [comment]
I'm talking about binary builds.

**Comment by killermoehre** [comment]
@chadchoi just compile it yourself. Would be really easier.

**Comment by eht16** [comment]
As @killermoehre said, compiling yourself is probably better when you want to install both versions in parallel.
Even if you would extract the Debian package, the compiled binaries still refer to "/usr" as prefix and so will load additional data (interface definition, filetype configurations, themes, ...) from "/usr" and so from the version installed via the Debian package manager.
