### ISSUE TITLE
Make Compiler window Monospace by Default

### ISSUE THREAD

**Issue by elextr** [geany/geany#435]
Now that GCC seems to have joined clang and old 1970s compilers in using ^ to mark where they think the error is, the compiler window should be monospace font, so the ^ points to the right place.

**Comment by b4n** [comment]
Actually one can already change the font of the whole message window (status, compiler, message, scribble) in the settings (I myself indeed have it set to monospace).

**Comment by b4n** [comment]
(BTW, IMO it makes sense in at least both compiler and message tabs, which both display more or less a program's output)

**Comment by techee** [comment]
@b4n It is of course possible, the question is whether it shouldn't be default. The only disadvantage of a monospaced font is that it's a little wider so you won't see so much text.

I think it makes sense for Scribble too because you typically paste there pieces of code.

This leaves the Status tab (which IMO should be hidden by default because it's not so interesting for normal users and just occupies vertical space) where we could use standard font like in Help->Debug Messages.

**Comment by elextr** [comment]
Oops, as @techee says, the key word I left out is "by default", now edited :)

As far as I'm concerned, simply making `monospace` the default for the whole message window would be fine.  I don't think it matters for things like status, and as @techee says above the other tabs probably should also benefit from being monospace.
