### ISSUE TITLE
Tooltip not updated in symbol tree when function return value changes

### ISSUE THREAD

**Issue by techee** [geany/geany#474]
When implementing Go function arglist/return value parser (patch to come), I noticed that when the return value changes, Geany still displays the old return value in the calltip in the Symbols panel (the tag itself is updated correctly, calltips show the correct value).

I can fix this, just a question what the preferred way is. It looks that one could either update the calltip here

https://github.com/geany/geany/blob/master/src/symbols.c#L1437

or change the tag_equal() and tag_hash() functions here

https://github.com/geany/geany/blob/master/src/symbols.c#L1173

to include the return value so when it changes, it's considered to be a different tag and the old value is removed from the symbol list and re-added.

I haven't studied the code enough so I'm not sure about various side-effects of the two solutions. Which one is the preferred way?

**Comment by elextr** [comment]
Though I'm far from an expert, I would have said that including the return type in the signature of the tag is more likely to be correct for more languages, including those that allow overloading.

**Comment by b4n** [comment]
> I can fix this, just a question what the preferred way is. It looks that one could either update the calltip here
>
> https://github.com/geany/geany/blob/master/src/symbols.c#L1437

Updating the tooltip here seem to make sense indeed.  The only reason no to do it would be speed, but as this issue shows it means that the info displayed in the toolip have to match the criteria used to consider an entry in the tree equal or not -- which was apparently not the case.

> or change the tag_equal() and tag_hash() functions here
>
> https://github.com/geany/geany/blob/master/src/symbols.c#L1173

Changing `tag_equal()` and `tag_hash()` should probably only be done when we really need to differentiate two similar tags.  E.g. if there is a language where 2 symbols can legitimately have the same type, name, scope *and* argument list, but a different return type, it should be added there.  Otherwise, there's no need to, and would only make the thing slightly less optimized for the normal case (I think, this code is complex and I wrote it some time ago, so I'm not 100% sure of the speed details).

Note: BTW, if you want to differentiate the return type of two tags, you might have to consider both `var_type` and `pointerOrder`.

**Comment by techee** [comment]
Yeah, I can't imagine how function overloading based only on return value would work (there would be ambiguity when returning compatible types) so just updating the tooltip is fine IMO.

**Comment by techee** [comment]
By the way, if there's a performance problem, we could just compare the TMTags (found_item and tag) and if they are identical, skip the tree item update. Unless I miss anything, this is not done right now.

**Comment by techee** [comment]
OK, couldn't resist the temptation and did it - I think it could make a difference on files with many tags (but haven't really benchmarked).

**Comment by b4n** [comment]
> By the way, if there's a performance problem, we could just compare the TMTags (found_item and tag) and if they are identical, skip the tree item update. Unless I miss anything, this is not done right now.

I doesn't make sense to check it because the new `TMTag`s come from a new CTags run, which means new pointers.

**Comment by b4n** [comment]
(or I myself am missing something :))

**Comment by techee** [comment]
@b4n Sorry, I meant "equal", not "identical".

**Comment by b4n** [comment]
I am the one to be, I didn't read the code before saying something :/
