### ISSUE TITLE
render problem on xubuntu

### ISSUE THREAD

**Issue by BMaxV** [geany/geany#511]
On my xubuntu install I have the problem that when I launch geany and then launch something else while the geany launch is not complete, it freezes geanys window rendering.

Meaning that if I switch back to geany when it has finished loading it doesn't update the window and I can drag other windows over it and they leave these unrendered trails.

So in case you've also noticed this problem and could find the source, I found it. A very minor inconvenience though since it launches very quickly anyway and the little bit of patience doesn't hurt.

**Comment by codebrainz** [comment]
For the record can you mention stuff like your Xfce version, window manager, graphics card, etc. I'm not sure this is going to be easily reproducible.

**Comment by borisulianov** [comment]
Hi! Not sure if it's the same problem, but every time I open Geany (in Lubuntu) the window doesn't render properly. I can load Geany and use it, but some features, like the toolbar and statusbar doesn't refresh properly.

I have installed geany 1.25 (built on 2015-07-12 with GTK 2.24.28, GLib 2.45.3). This is a screenshot:

![0000087](https://cloud.githubusercontent.com/assets/9767478/17272735/c4430d9c-5674-11e6-80d4-fb6de3c279b7.png)

**Comment by b4n** [comment]
Really looks like a GTK or WM bug to me.  The part you don't see are the part that shuold work the best: they are drawn by GTK itself, with little to no customization on our part.
Interestingly, it probably also corresponds to the double-buffered part of the app.

Maybe try disabling composition on your WM.

And in all cases, 1.25 isn't too recent, maybe something got fixed since then.

**Comment by borisulianov** [comment]
Sorry for the late answer. Yes, I can confirm it is, indeed, a GTK problem.
