### ISSUE TITLE
Since 1.25 execute command outputs error in case of non-ascii paths

### ISSUE THREAD

**Issue by Yanpas** [geany/geany#554]
I press execute button on geany panel, new terminal window opens and outputs:
/tmp/geany_run_script_6NT80X.sh: 5: cd: can't cd to /home/yanpas/\320\227\320\260\320\263\321\200\321\203\320\267\320\272\320\270/Progging/2

The exact path is /home/yanpas/Загрузки/Progging/2

This is minor issue, cause program executes correctly, but if the program will be more complex (grab files from PWD e.g.) guess there may be some troubles.

See also https://github.com/geany/geany-plugins/issues/259

**Comment by elextr** [comment]
"/home/yanpas/\320\227\320\260\320\263\321\200\321\203\320\267\320\272\320\270/Progging/2" is the UTF-8 encoding of "/home/yanpas/Загрузки/Progging/2" with the non-ASCII spelt out in octal.

Unfortunately bash doesn't recognise the escaped octal unless the filename is enclosed in `$''` like

    $'/home/yanpas/\320\227\320\260\320\263\321\200\321\203\320\267\320\272\320\270/Progging/2'

This might be fixed by #548.

**Comment by Yanpas** [comment]
So how can I check whether the bug is fixed?  Maybe you will try to create Загрузки folder?

**Comment by b4n** [comment]
Fixed now, thanks!
