### ISSUE TITLE
 For a long time to open JSON files 37mb

### ISSUE THREAD

**Issue by De-Luxis** [geany/geany#577]
I have a file that has a capacity of three tens of megabytes.
Before I opened it as a simple text document, backlight and applied separately.
It took a bit of time. Now, if you open the file, it opens up a very long time.
Can leave for several hours.
Please solve this problem, because it is important for my work. While'll deal less comfortable

**Comment by elextr** [comment]
What filetype does it open as?

**Comment by b4n** [comment]
I guess this is due to the new JSON filetype in 1.25 (providing highlighting and symbol tree).  We'd indeed need to check for optimizing this (if possible), or really add a way to fallback to filetype None for large files.

@De-Luxis A quick workaround to avoid highlighting and symbol parsing would be to set `JSON=` (yes, to an empty value) in your `filetype_extensions.conf`:
```ini
[Extensions]
JSON=
```
This will prevent `.json` files from being automatically recognized as JSON, so will use the None filtype (which drops the new features but is a lot faster).

Another solution if the highlighting is fast enough but it's the symbol tree that makes things slow (very possible, as I would guess a 37MB JSON file might have hundred of thousands of symbols) would be to disable only symbol parsing for JSON files.  You can do that by adding the following configuration to the (new) file `~/.config/geany/filedefs/filetypes.JSON.conf` (or the equivalent on Windows):
```ini
[settings]
tag_parser=
```

**Comment by De-Luxis** [comment]
@b4n Yes, really long handled Vail because of building branch. But it is also necessary to me.
If you open the file as a simple, it's fast, but not convenient.
@elextr Ubuntu 12.04 x64

**Comment by techee** [comment]
@b4n I suspect it's the symbol tree which is slow here (parsers usually parse tens of MB per second). Maybe we should really add some sanity check for the number of tags shown in the sidebar and limit it to say 10000. Plus the "big file opening warn" dialog we talked about.

@De-Luxis Could you please try the following to verify it's the Symbols list which is slow?

1. Close the big json file if it's open
2. In the sidebar switch to some other tab than Symbols
3. Open the big json file

The Symbols window isn't updated if the tab isn't shown so if I'm right it's the Symbols window which is slow, the file should open much faster with the above.

**Comment by De-Luxis** [comment]
@techee I initially all the windows and tabs are closed. In addition to the work area that is not present.
Try sgenirovat own the file and work with it.

**Comment by techee** [comment]
Alright, I profiled the sidebar code a bit and the problem is the following - inside update_tree_tags() the parents_table is a table mapping (tag_name -> list of tree iterators). The trouble with some json database export containing e.g. an array of objects like

```
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
```

is that in the array there are many of tags with "title", "type", "properties", etc. which are potentially parents of other tags inside the tree. Inside the parents_table this leads to e.g. ("title" -> long list of all the iterators to all the "title" occurrences). Then in the second pass the code

```
				/* walk parent candidates to find the better one.
				 * if there are more than one, take the one that has the closest line number
				 * after the tag we're searching the parent for */
				candidates = g_hash_table_lookup(parents_table, parent_name);
				if (candidates)
				{
					GList *node;
					glong delta = G_MAXLONG;
					foreach_list(node, *candidates)

```

the foreach_list() has to walk a big list to find the correct parent for each tag and the complexity becomes quadratic.

Now a slightly heretic question after all the works spent on implementing the JSON parser - is it a good idea to parse JSON files? These (similarly to XML, CSV and other data exchange formats) have the potential to be really big and the only usable part of the parsing is the symbol tree (neither code completion nor go to tag definition/declaration make much sense).

**Comment by b4n** [comment]
@techee thanks for investigating!  And your findings make a lot of sense, a lot of duplicate tags will degrade performance.

> Now a slightly heretic question after all the works spent on implementing the JSON parser - is it a good idea to parse JSON files? These (similarly to XML, CSV and other data exchange formats) have the potential to be really big and the only usable part of the parsing is the symbol tree (neither code completion nor go to tag definition/declaration make much sense).

Well… it's handy to navigate small JSON files, e.g. ones used for configuration of some things.  But for a 47M dump I doubt it's really practical indeed.

So… well I don't know, maybe we should have a tag count limit as you say (you could even display nothing at all probably, just "too many tags to display, change your configuration if you want to see them"), or drop the JSON parser altogether… it's not like I would suffer a lot :)
If it's really a problem it's easy to deactivate, just use my second solution from https://github.com/geany/geany/issues/577#issuecomment-122266792

**Comment by elextr** [comment]
I would tend to agree that a maximum number of tags is one place where we can have a limit, especially if its configurable.  Thats a better indicator than just raw file size.

**Comment by techee** [comment]
> I would tend to agree that a maximum number of tags is one place where we can have a limit, especially if its configurable. Thats a better indicator than just raw file size.

@elextr Unfortunately we cannot stop parsing if we reach some number of tags so if the parsing is the bottleneck, the maximum number of tags cannot be used - it only works for the sidebar.

@b4n Maybe we can wait for a while to see if other users start complaining too and if this is a real issue. At certain file sizes also the parsing becomes an issue - for a 47MB file it will take more than 1s to parse it and while this time is OK for just viewing it, it's unusable for editing.

**Comment by codebrainz** [comment]
@De-Luxis I don't suppose the file content was all on a single line and/or that you have word-wrapping enabled? IIRC that would cause massive performance problems in itself.

**Comment by De-Luxis** [comment]
Who opened a large json file of 42 megabytes, it opened very quickly.
Thank you very much!
I do not know what you've done, but it was working really fast!
