### ISSUE TITLE
Search and replace faulty for letter Eszett (ß)

### ISSUE THREAD

**Issue by nepa** [geany/geany#593]
The search and replace feature is faulty for the German letter sharp s / Eszett (ß).

In German, the letter 'ß' is often transcribed as 'ss'.

Let's assume we have this text in Geany:
> Außenhandelsstatistik in der gültigen Fassung

Now we use the search and replace dialog to turn 'ß' into its UTF-8 code '\u00DF'.

Geany will generate this output (which **is wrong**):
> Au\u00DFenhandel\u00DFtatistik in der gültigen Fa\u00DFung

However, this would have been **correct**:
> Au\u00DFenhandelsstatistik in der gültigen Fassung

So, obviously Geany converts both 'ß' and 'ss' to '\u00DF'.

For sake of completeness, these are my search settings:
![Search settings](https://cloud.githubusercontent.com/assets/772192/8955363/3cfb74f4-35ec-11e5-95d0-5f323f3a65fa.png)

**Comment by elextr** [comment]
Does it change ss if you select case-sensitive?

**Comment by nepa** [comment]
No, it does not.

**Comment by elextr** [comment]
The Scintilla library used by Geany follows the Unicode standard for locale independent case folding to do case insensitive searching section 5.18 [warning pdf](http://www.unicode.org/versions/Unicode7.0.0/ch05.pdf).

This standard specifies that 'ß' and 'ss' match when case insensitive.  

Since you selected a case insensitive search, changing both is correct.  Correctly only 'ß' is changed when you select case sensitive.
