### ISSUE TITLE
Get persistent messages saying the source file has been modified. Even though no other process is using the file.

### ISSUE THREAD

**Issue by fordanov** [geany/geany#605]
After upgrading to version 1.25

If I mount remote filesystems through FTP, SSH or whatever with Fuse or LUFS, when saving files I get persistent messages saying the source file has been modified. Even though no other process is using the file.
I don't want "set disk_check_timeout" to 0, because I want to know if someone has changed the file, while I'am working.

In version 1.24.1 it was ok

**Comment by elextr** [comment]
This has been discussed in [this](http://article.gmane.org/gmane.editors.geany.general/8442) ML thread.

Unfortunately, AFAIK none of the Geany devs has access to a setup that has the problem, so it needs someone who can replicate the problem and can build Geany to try things to see if we can figure what is the problem.

**Comment by codebrainz** [comment]
The weird thing is, I don't think anything changed between 1.24 and 1.25 with respect to how it detects changes. The only thing I can think is that some people are using 1.25 package that had `USE_GIO_FILEMON` defined when being built or something.

**Comment by elextr** [comment]
The only change is the extra `stat` that was added before the save.  That doesn't seem relevant since the file is `stat`ed again after saving.  The only thing I can think of is that the time found by the extra `stat` somehow is cached by GVFS/FUSE and used as the time returned after the save.  But 30 secs later the cache has timed out and the time is re-read.  But to test that needs someone who gets the problem to add prints of the times.

**Comment by codebrainz** [comment]
>  But to test that needs someone who gets the problem to add prints of the times

I suspect it could be reproduced if testers setup similar FUSE mounts. I haven't done it yet, but it shouldn't be considered un-reproducible just because we're too lazy to install the packages needed to reproduce it :)

I would be interested to know @fordanov's distro/version and the versions of the GTK+'s linked in both the 1.24 and 1.25 cases.

**Comment by fordanov** [comment]
I use Linux Mint 17.1
I downloaded source code from http://www.geany.org/Download/Releases when there was 1.24. version. It was about 5 months ago
Then
sudo apt-get update
sudo apt-get install g++
sudo apt-get install gtk+-2.0
 ./configure
make
sudo make install

dpkg -l libgtk2.0-0 libgtk-3-0 command shows in my computer

| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  libgtk-3-0:i386         3.10.8~8+qiana   i386             GTK+ graphical user interface library
ii  libgtk2.0-0:i386        2.24.23-0ubuntu1 i386             GTK+ graphical user interface library



Recently I decided to upgrade my geany to 1.25 version. It was about 3 days ago.
Again, I downloaded source code from http://www.geany.org/Download/Releases and just did
 ./configure
make
sudo make install

without  sudo apt-get install gtk+-2.0

Additionally I installed plugins from https://github.com/geany/plugins.geany.org

**Comment by elextr** [comment]
@codebrainz I didn't say it was not reproducible, in fact I pointed to another report of the problem, and I'm not saying that devs *can't* set it up, just that none have it as a normal part of their setup and workflows, otherwise it is likely to have been seen before release.  So that may delay any debugging, whereas if someone who has a setup with the problem can also test things, it may be debugged faster.

**Comment by tisdall** [comment]
I was using 1.24.1 from the PPA with no issues and the upgrade to 1.25 (also from the PPA) is when the issues started.  So, the issue exists in the packaged .deb file.  I switched back to the 1.24.1 .deb which still exists in the PPA's pool and now I'm not having the issue.  I'd say maybe it was the build process for the package, but @fordanov said he built from source and has the same issue.

My current system (back to 1.24.1):
```
$ dpkg -l libgtk2.0-0 libgtk-3-0 fuse geany
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                         Version             Architecture        Description
+++-============================-===================-===================-=============================================================
ii  fuse                         2.9.2-4ubuntu4.14.0 amd64               Filesystem in Userspace
ii  geany                        1.24.1+dfsg-1~hyper amd64               fast and lightweight IDE
ii  libgtk-3-0:amd64             3.10.8-0ubuntu1.4   amd64               GTK+ graphical user interface library
ii  libgtk-3-0:i386              3.10.8-0ubuntu1.4   i386                GTK+ graphical user interface library
ii  libgtk2.0-0:amd64            2.24.23-0ubuntu1.2  amd64               GTK+ graphical user interface library
ii  libgtk2.0-0:i386             2.24.23-0ubuntu1.2  i386                GTK+ graphical user interface library
```

**Comment by tisdall** [comment]
If someone could supply me with a patch that would output some helpful debugging I could compile the project and report on the output...

**Comment by codebrainz** [comment]
If you checkout the git code, you might try:

```
git revert 541cb8dbccdab127a08e63855cea00f0f5608787
```

Which will revert the commit (541cb8dbccdab127a08e63855cea00f0f5608787) @elextr was referring to above, then do the normal build procedure.

**Comment by fordanov** [comment]
> If you checkout the git code, you might try:

> git revert 541cb8dbccdab127a08e63855cea00f0f5608787
> Which will revert the commit (541cb8d) @elextr was referring to above, then do the normal build procedure.

Yes.
I have removed 
`document_check_disk_status(doc, TRUE);`
from src/document.c and build again.

Now I don't get persistent messages saying the source file has been modified

**Comment by fordanov** [comment]
But if I make changes in file with other editor I don't get messages too.

**Comment by tisdall** [comment]
@fordanov - I think it only checks for a change every 30 seconds and then I think it only gives a message if you give that file focus.  Did you wait the full 30 seconds?  I think it may also give a message if you try to make a change and save it...  it should check that something else didn't make a save before you try to make your save.  (maybe you know this already, I just don't want to assume)

**Comment by elextr** [comment]
On 12 August 2015 at 04:45, Tim Tisdall <notifications@github.com> wrote:

> @fordanov <https://github.com/fordanov> - I think it only checks for a
> change every 30 seconds and then I think it only gives a message if you
> give that file focus.
>

​Actually its every keystroke to the window, but not more often than 30secs
or something like that (keystrokes are in there somewhere anyway).​



> Did you wait the full 30 seconds? I think it may also give a message if
> you try to make a change and save it... it should check that something else
> didn't make a save before you try to make your save. (maybe you know this
> already, I just don't want to assume)
>

​The line you removed was the just before save check that it hadn't
changed, so the modified version doesn't do that any more.

Cheers
Lex

**Comment by elextr** [comment]
@tisdall thanks for trying, with the commit back in, can you add a `printf("cd:   %s\n", ctime(&(doc->priv->mtime)));` just before the `g_free(locale_filename);` at line 3634 in `document_check_disk_status()` and (with the "cd" changed to say "ut") just before the return in `document_update_timestamp()` line 1604 and lets see what it is getting for the times when you save the file.

**Comment by fordanov** [comment]
>​ Actually its every keystroke to the window, but not more often than 30secs
> or something like that (keystrokes are in there somewhere anyway).​

Actually only if you give that file focus or when you switch between tabs

Now, after removed the line, if I works with the local file and someone changes the file, I get message that the file has been modified. It' ok

But

There are cases if I work with the remote file (over GVFS) and someone changes the file, I don't get the message. Furthermore, If I reload the file (press Ctrl + R or File -> Reload) and even if I reopen Geany I don't see any changes (Other editor like "Gedit" show any changes) until I don't press "Reload" folder button in Nautilus. This is not alwas, but sometimes it happens. There need something like "Hard Reload" button. 
It's issue in both version 1.24.1 and 1.25

**Comment by elextr** [comment]
On 12 August 2015 at 16:59, Виталий Дмитриев <notifications@github.com>
wrote:

> ​ Actually its every keystroke to the window, but not more often than
> 30secs
> or something like that (keystrokes are in there somewhere anyway).​
>
> Actually only if you give that file focus or when you switch between tabs
>
> Now, after removed the line, if I works with the local file and someone
> changes the file, I get message that the file has been modified. It' ok
>
> But
>
> There are cases if I work with the remote file (over GVFS) and someone
> changes the file, I don't get the message.
>
​Note that Geany does not access the remote file, it only accesses the
local GVFS mount.  If that does not reflect the changes of modification
time of the remote file Geany will not see them.​


> Furthermore, If I reload the file (press Ctrl + R or File -> Reload) and
> even if I reopen Geany I don't see any changes (Other editor like "Gedit"
> show any changes
>
​My understanding is that gedit accesses remote files directly by GIO not
by GVFS​, so it may well work differently.

) until I don't press "Reload" folder button in Nautilus.
>
​Sounds like this triggers the local GVFS mount to update the times, and
then they can be seen by Geany.​

This is not alwas, but sometimes it happens. There need something like
> "Hard Reload" button.
> It's issue in both version 1.24.1 and 1.25
>
​It is an issue in GVFS, so yes, it doesn't matter which version of Geany
you use.​

**Comment by techee** [comment]
I had a look at the code and while I don't see any reason why the false file reload window opens (removing the check is a workaround but there doesn't seem anything wrong with it and I'd like to add even more checks in #533 ), I found one case which might cause missed file updates on remote file systems. The check here

https://github.com/geany/geany/blob/master/src/document.c#L3620

compares the modification time with local time which can be different on the remote machine and if this condition is satisfied, the next if checking the modification time isn't performed and you don't get the reload message. This if should just be removed IMO.

Another problem is here

https://github.com/geany/geany/blob/master/src/document.c#L888

where we should stat the possibly remote file instead of using system time as a timestamp.

**Comment by techee** [comment]
By the way why is the USE_GIO_FILEMON disabled? Is it because it's not stable in Geany or in GIO? At least in Geany there should be "return TRUE;" at the end of the block here

https://github.com/geany/geany/blob/master/src/document.c#L3600

otherwise it falls back to the mtime check which isn't updated in this case and things won't work.

**Comment by techee** [comment]
@fordanov @tisdall Would you try what happens if you enable/disable some of the

use_atomic_file_saving
use_gio_unsafe_file_saving
gio_unsafe_save_backup

settings from Preferences->Various page? What I suspect is when we issue stat() to check the modification time we use to check whether the file was updated, the file isn't completely saved yet and the modification time is updated afterwards so Geany thinks there was an additional modification even though it was the save from Geany itself. Using different saving methods might help.

**Comment by elextr** [comment]
@techee 

agree L3620 doesn't look real sensible, but then there have not been any reports of people getting the message (though it may be hidden for everybody who starts geany from the desktop menu)

I may have missed it, but I don't think the file is saved at L888 so there is nothing to stat, but I don't know why system time is used either.

My memory is that gio file monitoring caused multiple triggers in some cases, which was really hard to filter to ensure that you didn't get multiple info bars, so it was turned off until "somebody" has the time/interest/need to sort it out.

> What I suspect is when we issue stat() to check the modification time we use to check whether the file was updated, the file isn't completely saved yet and the modification time is updated afterwards so Geany thinks there was an additional modification even though it was the save from Geany itself.

Agree (see my comment on the ML thread I think it was), and the evidence so far seems to indicate that the metadata on the local GVFS mount is simply not being updated in a timely manner, even after the file is saved.  Thats not surprising since for a SFTP mount it would mean continually polling the remote system, something thats probably frowned upon.

**Comment by techee** [comment]
> I may have missed it, but I don't think the file is saved at L888 so there is nothing to stat, but I don't know why system time is used either.

Yeah, correct, I didn't read the code carefully enough - the value of mtime shouldn't matter here.

Now I'm wondering whether using g_file_query_info() instead of g_stat() wouldn't help. The GVFS homepage says:

"GVfs is a userspace virtual filesystem designed to work with the I/O abstraction of GIO. It installs several modules that are automatically used by applications using the APIs of libgio."

g_stat() however just calls stat() internally and doesn't use anything from GIO. Does GVFS work correctly when using standard unix API calls like stat()?

**Comment by elextr** [comment]
> "GVfs is a userspace virtual filesystem designed to work with the I/O abstraction of GIO. It installs several modules that are automatically used by applications using the APIs of libgio."

Oh great, a FUSE that only works with GIO, pfft :(

> g_stat() however just calls stat() internally and doesn't use anything from GIO. Does GVFS work correctly when using standard unix API calls like stat()?

Well, a FUSE file system is supposed to "mount" remote files locally so apps that use normal file accesses will work.  But given the previous statement, maybe the G* guys don't care about that.

But we should remember that with SFTP there is no way (IIUC) for a server to notify a client that a file has changed, the client has to poll the server and of course thats expensive, so its not done often, so there is a delay in notifying the client, and that adds to the Geany delay.  Also the ability for the client to specify metadata (like the local mtime) to the server is optional, it may work or it may not work.  If the server does not support it then the remote file will have a different mtime to the local file until it is polled and updated.

**Comment by tisdall** [comment]
@elextr Okay here's the results:
```
cd: Wed Aug 12 16:00:44 2015

ut: Wed Aug 12 16:00:44 2015

cd: Thu Aug 13 09:39:38 2015
```
It seems that immediately after saving the stat call gets the old file datetime.  Then when it tries to stat the file later it gets the new timestamp and assumes something else changed the file.

I tried again:
```
cd: Thu Aug 13 09:39:38 2015

cd: Thu Aug 13 09:39:38 2015

ut: Thu Aug 13 09:39:38 2015

cd: Thu Aug 13 09:43:04 2015
```
The first entry is from clicking in the file when I gave it focus.  The 2nd and 3rd occurred when I saved the file.  The last was when I went back to the window and clicked to give it focus again.

Here's the changes I made just to confirm:
```
diff --git a/src/document.c b/src/document.c
index ff3f5e8..4e22f12 100644
--- a/src/document.c
+++ b/src/document.c
@@ -1601,6 +1601,7 @@ static gboolean document_update_timestamp(GeanyDocument *doc, const gchar *local
 
        doc->priv->mtime = st.st_mtime; /* get the modification time from file and keep it */
 #endif
+       printf("ut: %s\n", ctime(&(doc->priv->mtime)));
        return TRUE;
 }
 
@@ -3631,6 +3632,7 @@ gboolean document_check_disk_status(GeanyDocument *doc, gboolean force)
                /* doc may be closed now */
                ret = TRUE;
        }
+       printf("cd: %s\n", ctime(&(doc->priv->mtime)));
        g_free(locale_filename);
 
        if (DOC_VALID(doc))
```

However, I complied from the tarball available from the website because I was having issues with `automake` properly creating the `./configure` on the git repo (or some other issue... basically when I run the `./configure` it complains about not finding `install.sh`).

Let me know if you'd like me to try anything else...

**Comment by techee** [comment]
@tisdall Would you try modifying 

use_atomic_file_saving
use_gio_unsafe_file_saving

as I suggested above if it makes any change?

@elextr 
> But we should remember that with SFTP there is no way (IIUC) for a server to notify a client that a file has changed, the client has to poll the server and of course thats expensive, so its not done often, so there is a delay in notifying the client, and that adds to the Geany delay. 

The stat() call we do should do the poll, we don't need to get notified by the server. I don't see the problem here unless FUSE or its ssh/ftp/... backend is buggy.

> Also the ability for the client to specify metadata (like the local mtime) to the server is optional, it may work or it may not work. If the server does not support it then the remote file will have a different mtime to the local file until it is polled and updated.

We don't specify any metadata to the server - we just save the file and the server's filesystem should update the timestamp. Afterwards we do the query using stat() which should get the new timestamp. No special metadata functionality is required.

I tried myself FUSE over ssh but couldn't reproduce the problem (could however reproduce the warning message easily so this check should really go). Will try to prepare a patch using the gio calls to see if it helps.

**Comment by elextr** [comment]
>
>
> The stat() call we do should do the poll, we don't need to get notified by
> the server. I don't see the problem here unless FUSE or its ssh/ftp/...
> backend is buggy.
>

​Agree it should poll, but I doubt it does, I bet it uses a cached local
copy, and that seems to be supported by Tim's data above.  But I'm not
gonna read the source to find out.​



> Also the ability for the client to specify metadata (like the local mtime)
> to the server is optional, it may work or it may not work. If the server
> does not support it then the remote file will have a different mtime to the
> local file until it is polled and updated.
>
> We don't specify any metadata to the server - we just save the file and
> the server's filesystem should update the timestamp. Afterwards we do the
> query using stat() which should get the new timestamp. No special metadata
> functionality is required.
>

​If the sequence is:

1. Geany does a write
2. GVFS sends the data to write the file​ and returns to Geany
3. Geany does a stat, but the remote file hasn't been written yet, so GVFS
returns its local mtime
4. the write completes, GVFS gets the remote mtime, which does not agree
with the one Geany got from the previous stat
5. 30s later Geany does another stat and gets this different time, and
goes, OH ITS CHANGED!!!!

IIUC the SFTP protocol has an optional feature for the client (GVFS) to
send the *local* mtime to the server to be recorded for the file, so the
above problem doesn't occur.  But its optional for both client and server
to support it.



> I tried myself FUSE over ssh but couldn't reproduce the problem (could
> however reproduce the warning message easily so this check should really
> go).
>

​It makes sense for local files, just not for remote files where time on
two machines will not be identical.



> Will try to prepare a patch using the gio calls to see if it helps.
>

​Try to avoid the GIO unsafe behaviour if you can.​

**Comment by tisdall** [comment]
@techee - I'm not 100% sure which settings you wanted me to test.  The previous results are with `use_gio_unsafe_file_saving=true` and `use_atomic_file_saving=false`.

With `use_atomic_file_saving=true` (which should cause the use_gio_unsafe_file_saving to be ignored) I get the following:
```
cd: Fri Aug 14 16:00:22 2015

ut: Mon Aug 17 09:36:59 2015

cd: Mon Aug 17 09:36:59 2015
```
The first timestamp is on loading, the second is when I saved the file, and the last is after some time giving the file focus again.  No warning messages (as expected from those results).

I tried again on the same file...  When I clicked "save" I got the following:
```
cd: Mon Aug 17 09:36:59 2015

ut: Mon Aug 17 09:42:01 2015
```
So, I guess it did a check on the file just prior to saving and then another one immediately after.

Third test:
```
cd: Mon Aug 17 09:42:01 2015

cd: Mon Aug 17 09:42:01 2015

ut: Mon Aug 17 09:44:02 2015
```
First entry is on giving the file focus, second two entries were after clicking "save".

So, `use_atomic_file_saving` seems to not have the same issues as the gio one.

**Comment by tisdall** [comment]
I finally figured out how to compile from the git repo (I wasn't familiar with `./autogen.sh`), so let me know if you'd like me to try any patches/PRs/branches/etc.

**Comment by techee** [comment]
@elextr 
> If the sequence is:

Mostly agree, but:

> 1. Geany does a write
> 2. GVFS sends the data to write the file​ and returns to Geany
> 3. Geany does a stat, but the remote file hasn't been written yet, so GVFS
returns its local mtime

I think something else happens here - I don't think GVFS/FUSE caches the local metadata - as you say, the remote file write hasn't been finished yet so the remote file's metadata hasn't been updated yet either and GVFS returns the remote file's (old) mtime.

> 4. the write completes, GVFS gets the remote mtime, which does not agree
with the one Geany got from the previous stat

GVFS doesn't "get" the mtime automatically - it happens in point (5) 30s later when we call stat() explicitly.

> 5. 30s later Geany does another stat and gets this different time, and
goes, OH ITS CHANGED!!!!

>> I tried myself FUSE over ssh but couldn't reproduce the problem (could however reproduce the warning message easily so this check should really go).

​> It makes sense for local files, just not for remote files where time on
two machines will not be identical.

Nope, I tried this on a remote server.

@tisdall Great to hear use_atomic_file_saving works. This leads me to one more question - what OS (kernel version) and file system is the remote file system using? If what I described above is correct, it looks much more like a file system issue than FUSE/GVFS one. I guess the file system returns the old mtime before the written file is actually flushed to the disk - ext4/linux seems to return the new mtime even before it's written to the disk but this may be different for other file systems.

I'll prepare a patch that uses fsync() to force the file to be written to the disk to see if it helps in the gio case.

**Comment by b4n** [comment]
> IIUC the SFTP protocol has an optional feature for the client (GVFS) to send the *local* mtime to the server to be recorded for the file, so the above problem doesn't occur. But its optional for both client and server to support it.

I think I remember earlier reports about problems with SSHFS after an SSHFS change, and I think it needed a workaround, maybe `-o sshfs_sync` or something like this.  Or maybe not, as all I can quickly find is https://sourceforge.net/p/geany/bugs/669/ and linked.

> I'll prepare a patch that uses fsync() to force the file to be written to the disk to see if it helps in the gio case.

Heh, I was about to suggest trying to `fsync()` :)  Not certain it would help though -- and it certainly will destroy performances in some cases (but it's probably better than not working).

BTW, you seem to focus on GVFS only, but as I read the various reports, people get this with various remote file systems, not only GVFS, but also SSHFS and others.  Not saying that using GIO won't solve it because they might have special code for this already, but it might not be related to GVFS directly.

**Comment by tisdall** [comment]
@techee - The remote file system is ext3, and OS is `Linux dev 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux`

**Comment by techee** [comment]
@elextr I tried sshfs with FUSE on a remote server with a different time zone and it worked fine (but with a new kernel and ext4, in the case of @tisdall it's a fairly old kernel with fairly old ext3). I just got the warnings from the comparison with local time. I haven't tried GVFS actually.

It's the gio g_file_replace_contents() corresponding to (geany's default)  use_gio_unsafe_file_saving=true which doesn't seem to work and after which I'll try to call fsync - I'm not trying to do anything GVFS-specific otherwise.

@tisdall One more case to try:

use_atomic_file_saving=false
use_gio_unsafe_file_saving=false

to see if this case needs the fsync() or not.

**Comment by techee** [comment]
@tisdall For the above enough to know if it works or not - no need to check the timestamps.

**Comment by techee** [comment]
@tisdall What version of glib are you using on the machine where Geany is running? The thing is that I've checked the sources and the current glib version should do about the same as in the use_atomic_file_saving case (plus some extras which should however not affect its behavior regarding the mtime).

**Comment by elextr** [comment]
@techee 

> > Geany does a stat, but the remote file hasn't been written yet, so GVFS returns its local mtime

> I think something else happens here - I don't think GVFS/FUSE caches the local metadata - as you say, the remote file write hasn't been finished yet so the remote file's metadata hasn't been updated yet either and GVFS returns the remote file's (old) mtime.

Quite possibly, same effect though, it doesn't agree with the time 30s later.

> GVFS doesn't "get" the mtime automatically - it happens in point (5) 30s later when we call stat() explicitly.

True it doesn't get it as part of the SFTP protocol, but if *I* was writing the client I would poll for the metadata when I got the write complete response. Having to poll for everything each time a stat happens makes things like file dialogs slow, there really needs to be a local cache. But again, either way, the time is now different from that returned by the previous stat.

> I tried sshfs with FUSE on a remote server with a different time zone and it worked fine (but with a new kernel and ext4, in the case of @tisdall it's a fairly old kernel with fairly old ext3). I just got the warnings from the comparison with local time. I haven't tried GVFS actually.

Yes, thats what I would expect, the comparison is only (marginally) useful for local filesystems, and wrong for remote filesystems, so it can go.  And maybe the newer kernel has improved the FUSE infrastructure (or maybe you are lucky :).

Where are you proposing to add the `fsync()`?  If it is in Geany it would only apply in the case of `use_gio_unsafe_file_saving` having been changed from the default to off (and `use_atomic_file_saving` also being off).  Its worth a try though. 

And as @b4n says there are now reports on other file systems showing the problem (NTFS was reported on IRC, which is also FUSE for writeable mounts IIUC).  Maybe 1.25.1 needs to revert the extra stat call so people can use Geany whilst a different solution is found to the problem it was supposed to fix.

**Comment by tisdall** [comment]
@techee, I have package `libglib2.0-dev` installed with version `2.40.2-0ubuntu1` being reported.

Tried `use_atomic_file_saving=false` with `use_gio_unsafe_file_saving=false` and it seems to work okay.  There seems to be a noticeable delay between when the 'cd' and the 'ut' timestamps when clicking "save"....  maybe 0.25 to 0.5 seconds.  Same as the `use_atomic_file_saving=true`.

**Comment by techee** [comment]
@tisdall Thanks. Would you please try the remote_mtime branch from

https://github.com/techee/geany.git

The fact that both the use_gio_unsafe_file_saving=false modes work leads me back to the idea that we shouldn't mix GIO and POSIX file system calls. GVFS uses separate backends for them and there may be races when one operation is made using GIO and other using POSIX call. I tried to use consistent API calls depending on the file saving method used.

**Comment by tisdall** [comment]
@techee - just tried out your branch and it seems to work with no issues

**Comment by elextr** [comment]
> The fact that both the use_gio_unsafe_file_saving=false modes work leads me back to the idea that we shouldn't mix GIO and POSIX file system calls. GVFS uses separate backends for them and there may be races when one operation is made using GIO and other using POSIX call. I tried to use consistent API calls depending on the file saving method used.

Makes sense.

[Looks good by inspection](https://github.com/techee/geany/commit/12899d1286113ac89b50e406354d7b51c236acbe)

@b4n, 1.25.1?

**Comment by techee** [comment]
@tisdall Great to hear!

@fordanov I think it could also fix the file reload issue you experienced (could you test?).

@elextr If there's going to be 1.25.1, one possibility is also to remove the extra file modification check and leave this patch for 1.26.

**Comment by elextr** [comment]
On 19 August 2015 at 09:20, Jiří Techet <notifications@github.com> wrote:

> @tisdall <https://github.com/tisdall> Great to hear!
>
> @fordanov <https://github.com/fordanov> I think it could also fix the
> file reload issue you experienced (could you test?).
>
> @elextr <https://github.com/elextr> If there's going to be 1.25.1, one
> possibility is also to remove the extra file modification check and leave
> this patch for 1.26.
>

​Yes, it seems that there are significant problems for some configurations
using 1.25 so a fix should be made ASAP.  Reverting the extra check will
probably be safer for a patch release and your fix can be better tested for
1.26 in a month or two (or three or ... :).​

**Comment by elextr** [comment]
On 19 August 2015 at 09:39, Lex Trotman <elextr@gmail.com> wrote:

>
>
> On 19 August 2015 at 09:20, Jiří Techet <notifications@github.com> wrote:
>
>> @tisdall <https://github.com/tisdall> Great to hear!
>>
>> @fordanov <https://github.com/fordanov> I think it could also fix the
>> file reload issue you experienced (could you test?).
>>
>> @elextr <https://github.com/elextr> If there's going to be 1.25.1, one
>> possibility is also to remove the extra file modification check and leave
>> this patch for 1.26.
>>
>
> ​Yes, it seems that there are significant problems for some configurations
> using 1.25 so a fix should be made ASAP.  Reverting the extra check will
> probably be safer for a patch release and your fix can be better tested for
> 1.26 in a month or two (or three or ... :).​
>
>
​Also there was a report on IRC of the same problem with an NTFS mount.
IIUC writable NTFS is a FUSE filesystem also, so that should be tested too,
for the revert and the fix.
​

**Comment by codebrainz** [comment]
+1 for a 1.25.1 release removing the regression, if @b4n doesn't mind. A lot of people seem to use Geany for web-development and similar stuff where editing remote files is quite common (judging by the bug reports and people asking on ML/IRC), and this makes Geany more or less unusable for such cases. If Windows doesn't use GVFS, it shouldn't need another binary release there.

**Comment by techee** [comment]
> ​Also there was a report on IRC of the same problem with an NTFS mount.
> IIUC writable NTFS is a FUSE filesystem also, so that should be tested too,
> for the revert and the fix.

@elextr I think it's always GVFS vs FUSE conflict. The thing is that if you call a POSIX IO method, FUSE is called directly:

POSIX call->FUSE->remote server

while with a GIO call

GIO call->GVFS->GVFS_FUSE_backend->FUSE->remote server

This happens when gvfsd-fuse daemon is running which is the case of Ubuntu by default (I've just noticed it now, maybe I'll even be able to reproduce the issue). GVFS either caches or calls IO asynchronously so POSIX calls made through FUSE directly may reach the server earlier than GIO calls made through GVFS.

**Comment by elextr** [comment]
On 19 August 2015 at 10:29, Jiří Techet <notifications@github.com> wrote:

> ​Also there was a report on IRC of the same problem with an NTFS mount.
> IIUC writable NTFS is a FUSE filesystem also, so that should be tested too,
> for the revert and the fix.
>
> @elextr <https://github.com/elextr> I think it's always GVFS vs FUSE
> conflict. The thing is that if you call a POSIX IO method, FUSE is called
> directly:
>
> POSIX call->FUSE->remote server
>
> while with a GIO call
>
> GIO call->GVFS->GVFS_FUSE_backend->FUSE->remote server
>
> This happens when gvfsd-fuse daemon is running which is the case of Ubuntu
> by default (I've just noticed it now, maybe I'll even be able to reproduce
> the issue). GVFS either caches or calls IO asynchronously so POSIX calls
> made through FUSE directly may reach the server earlier than GIO calls made
> through GVFS.
>

​Yeah, just that writable NTFS is a *local* filesystem but still uses FUSE
so it will probably have the same problem and solution, just needs to be
checked by someone who can reproduce the problem.​

**Comment by b4n** [comment]
@elextr @codebrainz @eht16 @frlan @ntrel What do you think about point release?  OK, it's been 2 months so we're not so far from next release, and a bit late for a hot fixup (sorry, my fault basically), but if it's that annoying for many people it might make sense.  Opinions?

**Comment by eht16** [comment]
I would vote to wait for the next release even though it seems to affect users.
Now we just have two more months until the next release.

**Comment by elextr** [comment]
Given that the next release has some big changes in it (sure most is in plugins not normal usage but still) maybe it would be better to have a stable release we can direct people back to in case of problems in the new release.  So I can see benefits of a point release even if its close to the next release.
