### ISSUE TITLE
Please bold the active tab

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#635]
![boldtab](https://cloud.githubusercontent.com/assets/7548378/9569400/fdd08280-4f61-11e5-874e-d97bb233170c.png)

It is not very easy to see which tab is the active one.  Please make it stand out more clearly perhaps by bolding the text or colouring the background - or optionally both.  Thanks!

**Comment by b4n** [comment]
it's the theme's responsibility to show this information in all applications, and we let it do it.  You can probably alter your theme to style the active tab differently.
I don't think it's something Geany itself should do, but a tweak of the GTK theme.

If it's not currently possible to theme the active tab (I doubt it), we probably could be convinced to provide a style selector for the current tab, but I doubt it's even needed, nor very elegant.

**Comment by shevegen** [comment]
While I concur that this should be handled through the theme, for sake of consistency alone, I think it is simple to change the active tab since this is also just a gtk widget or? I remember that I have done so myself in my ruby-gnome apps, being able to change in particular the colours. Perhaps it is not worth to invest time into it, but I think in principle this should be fairly simple to do - one could have an "advanced options widget" for these kind of preferences in the long run.

PS: The old bluefish 1.x editor does some slight intensification of the currently selected tab; it appears a bit as if it would have a shadow. Perhaps bolding the text and colouring the background e. g. with a colour, could be done in such an advanced user preferences setting, while also notifying the user that the theme should do so.

PSS: It would be nice if a screenshot could be added to show how this is done via a theme properly, in the screenshot gallery. Thanks! \o/

**Comment by elextr** [comment]
Closed since there seems to be agreement it should be theme
