### ISSUE TITLE
Loading temporary files from the last session at startup does not work after a server reboot

### ISSUE THREAD

**Issue by robert4os** [geany/geany#640]
Hello,

Unfortunately my linux distribution (Fedora 22) and gnome are not as stable as I would want them to be and every now and then gnome or the server crashes...

Then all the temporary files in "/tmp" are lost. When geany is started again after a relaunch it tries to open these recently open files automatically but of course it does not find them.

I know about the backup plugin in but it is not as convenient, because geany does not try reopen the temporary files from the backup location, if it does not find the files under /tmp anymore.

Thus my alternative suggestions:
1) Make the temporary file location configurable so that one can set it to e.g. /reboot-stable/tmp
2) Let geany fallback to look for recently open files in the backup location if they are not found in /tmp
anymore.

The objective is that: After a crash and a wiped tmp dir geany would still be able to continue where it was stopped: All recently open temporary files would be reopened and the user could simple continue to use it.

As it is now the promise suggested by the startup option "Load files from the last session", is not kept (when it is mosed needed). 

Thank you for this great program and all your efforts! - best, Robert

**Comment by elextr** [comment]
Not sure what you mean, Geany will only open files in /tmp if you tell it to, the only thing it creates there is the run script and that deletes itself.

If you create files in /tmp and tell Geany to open them, geany can't do anything about the fact that they disappear on restart.

**Comment by robert4os** [comment]
When I open geany, then it will automatically open a new empty document at the /tmp location:
e.g. The status log will say "12:38:33: New file "/tmp/gis_BHTO4X." opened."

If I write anything in the file and then close geany this information is saved in the temporary file. When I reopen geany it will automatically reopen the files from the last session... this is great user experience! 
(It allows me to not having to worry which temporary files I want to keep, name and save permanently; I can do this at a later time) 

However, if the server crashes these temporary files are lost. And reopening geany after restart will be a disappointing user experience because all the files are gone (or have to be claimed from the backup directory).

**Comment by elextr** [comment]
Thats not base Geany behaviour, what plugins do you have open?

**Comment by robert4os** [comment]
It is the "Save Actions" plugin, with "Instant Save" enabled.

**Comment by elextr** [comment]
Well, the feature is intended for temporary files, though perhaps not as temporary as your flakey system makes them.  Really it would be better if you saved the file with a sensible name somewhere permanent, "/tmp/gis_BHTO4X." is not exactly descriptive :)

If geany was to save them somewhere other than /tmp you would have to delete them since nothing indicates when their life is ended.

**Comment by b4n** [comment]
Yeah the problem with temporary files is that they are, well, temporary :)

However, I can indeed understand the issue here, and allowing to configure the temporary directory seems like an acceptable solution if someone want to do it.

**Comment by b4n** [comment]
BTW, the feature does honor the  `TMPDIR` environment variable, so you could set that when running Geany to alter where the temp files are saved.  But that will include more temp files than those alone -- although we *should* be removing unneeded ones.

**Comment by robert4os** [comment]
:) flakey indeed, it's the nvidia card most of the times.

Basically I try to achieve with geany what I got very used to with Textwrangler on OS X. 

Textwrangler maintains temporary files (it calls "untitled") and their information very safe, even in case of reboots, crashes, etc.
 
When the user tries to close a temporary file, he gets a chance to save it with a name. Otherwise the file is lost (I guess deleted).

**Comment by robert4os** [comment]
I have tried env vars TMP TEMP TMPDIR TEMPDIR... geany might respect them, but the "Save Actions" plugin does not.

**Comment by elextr** [comment]
`TMPDIR=/data geany` works for me, save actions instant saves in /data not /tmp

**Comment by robert4os** [comment]
You are right "TMPDIR=/data geany" does works! 

(I was confused because the previous recent file from /tmp was shown again, but actually opening a new file, shows it works!)

Thank you, this will help me as a workaround! :)

Of course, nice would be an improved "Save Actions" plugin...
so that the "Instant Save" panel would feature a "Directory to save.." field like the "Backup Copy" panel... just dreaming :)

-best Robert

**Comment by ftrebien** [comment]
I'm on Geany 1.33 on Debian Buster and I was looking for a way to save these files in `/var/tmp` so that they are preserved between reboots or system crashes. Defining `TMPDIR` really works, but setting it to anything other than '/tmp' for all applications is generally undesirable. The user would normally want to configure it only for Geany. This requires modifying the files that are managed by the system's package manager (the desktop shortcut or the executable, which must be replaced by a script that defines the variable and then calls the executable), which makes updating Geany and the entire system complicated and prone to errors. I would like to ask for these options in the Instant Save plug-in configuration panel: 

- Default system temporary directory
- Custom directory: `[input field]`

**Comment by elextr** [comment]
@ftrebien the "instant save" is intended for temporary files, if you want a file to be permanent it should be saved to a suitable location with a sensible name.  Also no matter where it is saved, if the system crashes or is rebooted with Geany open there is no guarantee that the file is saved.

The plugin uses a portable Glib function to create the unique filename in the system temporary directory, so it works on Windows and macos.  All this would have to be replicated in the plugin.  Pull requests are welcome.

Also if the files are saved in some non-temporary location then they will not be deleted and will continue to accumulate.  You would have to delete them manually, but since they have random names you won't know which ones to delete.

**Comment by eht16** [comment]
It was actually pretty easy to implement using `g_mkstemp()` as done in #2769.
The directory for instantly saved files can then be configured and if not configured, the default temporary directory is used, as before.

I added a note in the plugin's preferences that the user is responsible for cleaning up the created files.

**Comment by ftrebien** [comment]
> @ftrebien the "instant save" is intended for temporary files, if you want a file to be permanent it should be saved to a suitable location with a sensible name. Also no matter where it is saved, if the system crashes or is rebooted with Geany open there is no guarantee that the file is saved.

I often brainstorm and take research notes using plain text documents, and this is sometimes for complex problems that are not very high priority, so the brainstorm/research is not finished at once.

It would be best to have a feature such as LibreOffice's file recovery, which works even for unsaved new documents.

**Comment by Malbeth81** [comment]
Thank you @eht16 for this change! I just lost a bunch of note over the weekend because I enabled the automatic save, thinking it would preserve untitled files like Notepad++ and not knowing it was saving in the /tmp folder!

I've just updated to 1.38 and was able to change the folder in the plugin config to get the behavior I wanted when I first enabled the plugin.

We're talking about text files containing notes, I don't care if I end up with a thousand files, we're not in 1994 anymore, I have plenty of space, data preservation is much more important to users like me. ;)

**Comment by joomlafun** [comment]
Honestly, when you see that a file has been generated with a file name automatically by geany you don't think it will get deleted on reboot.


Why not change the default path to anything other than /tmp?

I've just lost some notes and it will happen to other users for sure

**Comment by elextr** [comment]
The `/tmp` directory is delibery cleared by the operating system when booting and in the case of some operating systems also every few days.   Geany cannot control the operating system behaviour, so files can disappear from `/tmp` in operating system removal.  That is what it is intended for so that all the temporary files will be removed and the directory will not grow unacceptable large.  

If your file isn't a temporary do not save it in the `/tmp` directory.  You can set it somewhere else by setting the `Plugin Manager->Save Actions->Instance Save->Directory to save files in`.  Note that the entry has a note that `/tmp` is the default and there is a note that if the files are saved elsewhere then the directory will continue to grow in size and you will have to manually clear it as the operating system won't clear it.

There is some alternative features in the save actions plugin #3911, but it is not merged, but you can try it.  And even if it is merged for the next Geany version so far there is no documents so nobody will know about it.

**Comment by joomlafun** [comment]
@elextr Thanks for the explanation elextr.
 I did not know that /tmp/ gets emptied and indeed the note that you mention could have give me a hint even though I would not think it would apply to the default directory which geany selects(tmp).

Lots of people who switch for geany come from notepadqq or notepadd++ and whenever you open a new note and don't save it and restart your pc, you can retrieve it, so many people are used to this default safe behavior.


+ Seeing a file with a filename created automatically by geany really implies for me that it must be saved somewhere where it won't be deleted.

I changed the default saving folder now of course
