### ISSUE TITLE
Suggestion: Migrate to GTK3

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#644]
Geany is still using GTK2 according to the official Geany.org homepage. Should Geany update to GTK3? I suggest this because occasionally I get odd (and non-reproducible) GUI-glitches in Geany.

**Comment by codebrainz** [comment]
Geany does support GTK+ 3 if it's built with the `--enable-gtk3` configure flag, I use it exclusively here without issues.

**Comment by DevynCJohnson** [comment]
Okay, thanks. Then perhaps my issues are related to something else. However, why does Geany's homepage state that Geany uses GTK2 (http://geany.org/)?

**Comment by elextr** [comment]
The official release is still GTK2.  All the GTK2 calls that have been
deprecated in GTK3 have not yet been replaced in Geany, so the GTK3 compile
isn't "clean".

Until recent GTK3s the performance was also noticably poorer than GTK2, and
LTS distros may not yet have upgraded to a performant version.

So for now the GTK3 Geany isn't quite suitable for being the default build.

There is nothing stopping distro packagers packaging the GTK3 version of
course, and I think some bleeding edge distros have done just that.

**Comment by b4n** [comment]
> I suggest this because occasionally I get odd (and non-reproducible) GUI-glitches in Geany.

This shouldn't have much to do with the GTK version itself, GTK2 is very stable and should work just fine pretty much everywhere.

> Then perhaps my issues are related to something else. 

Not necessarily either; if your Geany is built against GTK2 it'll use GTK2, not GTK3.  To get Geany to use GTK3 you need to build it against GTK3 :)

@elextr 
> All the GTK2 calls that have been deprecated in GTK3 have not yet been replaced in Geany, so the GTK3 compile isn't "clean".

…which doesn't matter much until GTK4 -- and even then, the GTK3 part should work fine.  There are things that are simply too much hassle to "port" for virtually no gain, so until we drop support for GTK2 they are highly likely to stay.

**Comment by elextr** [comment]
> …which doesn't matter much until GTK4 -- and even then, the GTK3 part should work fine. There are things that are simply too much hassle to "port" for virtually no gain, so until we drop support for GTK2 they are highly likely to stay.

Sure, but then the build system should default to not showing deprecations, otherwise build-bots can't be made to detect warnings using `--Werror`.

**Comment by sint** [comment]
A new version of Geany arrived on my Distro today (Gentoo) and they've added GTK3 as a new feature to Geany. Since its Gentoo you're free to choose what you want to compile but because of this i got aware of the situation that Geany might drop support of GTK2 in a near future. While its currently still possible to compile Geany with GTK2, i would really love to see this GTK2 version of Geany stay alive for quite some time. I am one of those users running a mostly GTK2 only desktop which is still possible if you're using XFCE. GTK2 is fast and rock solid stable. I just don't like GTK3 and it feels broken to me. I don't want to debate about GTK3 here but there is an example out there that made me feel bad about a possible change into a GTK3 only version of Geany.

While coding, i work with Gitg next to Geany. They also had a pretty good GTK2 version of their software out there. But they've decided to rewrite it to GTK3 only. The result was an unstable and slow program. Next to this, with almost every update of GTK3 the interface of Gitg changes. Sometimes better and sometimes worse.

I really love what you've done for Geany and it is a great tool to work with. Its rock solid, fast, it never crashed for me and that's what i love about it! I would love to keep it that way. Thanks!

**Comment by elextr** [comment]
@sint 

> Geany might drop support of GTK2 in a near future. 

Not sure where you got that from, but there are *no* plans for that.

> But they've decided to rewrite it to GTK3 only. The result was an unstable and slow program. 

So they wrote a bad program, thats not GTK's fault.  The GTK3 version of Geany works fine with modern GTK3 versions, even Luddite sceptic me uses it every day :smile: .

**Comment by sint** [comment]
> Not sure where you got that from, but there are no plans for that.

Thanks, good to hear that! One day i'll might use a GTK3 desktop since XFCE will most likely not stay with GTK2 forever. But right now i am happy with it.

**Comment by b4n** [comment]
@sint As @elextr said, there are no current plans to drop GTK2, and there most probably won't be unless supporting it becomes problematic (maybe with GTK4).
And even now, the GTK2 version of Geany is most probably used a lot more than GTK3 one, as most distros still build a GTK2 one and that we distribute a GTK2 version for Windows and OSX (for various reasons, including stability and laziness).

**Comment by b4n** [comment]
Closing as the actual issues mentioned here have been resolved (website mentioning GTK2, and even deprecation warnings), and we won't drop GTK2 support now.
