### ISSUE TITLE
Cannot add F# filetype

### ISSUE THREAD

**Issue by kameko** [geany/geany#659]
I'm assuming there's some kind of collision with Forth. Even if I add a custom filetype for Forth as well (removing the "fs" reference), nothing I do allows F# to become a language. I can add my own languages fine, if they don't end in .fs.

Interestingly, it sort of adds F#, but it puts it under it's own category, "Fs file"

![Problem](https://i.imgur.com/5wLw9Xy.png)

As you can see, I made up my own language "Hasklel" which gets categorized just fine, they're even the same config file, just renamed. But F# is still treated as "Fs file". It's under the Programming category, same with "Hasklel", but it's still like this.

**Comment by elextr** [comment]
Groups are defined in filetype_extensions.conf

**Comment by kameko** [comment]
I'm aware. I just demonstrated that I'm capable of doing that, but F# appears to be a special case, somehow.

**Comment by b4n** [comment]
Hum.  Could you show your F♯ filetype?  first thing that comes to mind would be that the `#` in F♯ would be misinterpreted as a comment start (as `#` is the comment start character).

**Comment by kameko** [comment]
I attempted to remove the # by renaming it both F Sharp and FS, but that had no effect. In addition, C# already exists, which probably means using # isn't the problem.

![Filetypes](https://i.imgur.com/EbKoM4Y.png)

The filetypes.Fs.config I'm using is just Haskell's for now, with the file extension changed to "fs".

**Comment by elextr** [comment]
Works for me, latest , Geany 1.26 (git >= 31325bb), en_AU.UTF-8, GTK 3.10.8, GLib 2.40.2.

What version of Geany and Glib on what platform are you using?

All I did was `filetypes.F#.conf` just copied unchanged from `filetypes.Cython.conf` in `config/filedefs`, `F#=*.fs;` added to `filetype_extensions.conf` in the `[Extensions]` section and `F#` added to the `Programming` list in the `[Groups]` section.  F# appears in the programming section of the document->filetypes menu.

It would be better if you paste the files on a gist so people can use the exact file you are having trouble with, rather than images.

**Comment by kameko** [comment]
Oh, I see, I should have named it filetypes.F#.conf and not filetypes.Fs.conf. See I assumed Fs would work because in Geany's program folder it has a "filetypes.cs" file so I thought the same rule applied. My bad.
