### ISSUE TITLE
About Malloc memory for each tag?

### ISSUE THREAD

**Issue by pfsun** [geany/geany#682]
Dear All,

I am always using geany, but now this is the first time I prepare to look at geany source code. I have one question about memory allocation. When we open one new file, there will be one new window in geany. How could I track all memory allocation(g_malloc) related with this window? Or would it be possible to track all related functions with this window?

Thank you very much!

Best Regards,
Pengfei

**Comment by elextr** [comment]
Unfortunately its not possible to track allocations related to one file, its not even possible to track all allocations since Geany uses g_malloc (IIUC you can track this, see Glib docs), libraries use libc malloc and Scintilla uses C++ new.

This sort of question is better asked on the mailing list, it is not an issue.  Will close and you can ask any follow up questions there.

**Comment by pfsun** [comment]
Thanks your suggestion.

g_malloc is one wrapper of malloc. If I track malloc, I think I can get all
memory allocations, right?
According to my observation, each tab for one file is related with one
thread, right? So if I can track all memory allocation of this thread, I
can get all memory allocation for this file, right?

Thank you very much!

**Comment by elextr** [comment]
Please continue the discussion on the [mailing list](
http://www.geany.org/Support/MailingList) as requested, this is not an
issue.
