### ISSUE TITLE
Bracket jumping failure

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#762]
In a <b>Java</b> file with the cursor positioned as shown:

(1) Bracket jumping with <b>ctrl-B</b> works:

![matchingbrackets1](https://cloud.githubusercontent.com/assets/7548378/11224906/30474f14-8d6f-11e5-85e6-301e47bd7f4d.png)

(2) Bracket jumping with <b>ctrl-B</b> does not work:

![matchingbrackets2](https://cloud.githubusercontent.com/assets/7548378/11224907/304a53c6-8d6f-11e5-8e59-fa83dcd97276.png)

(3) Bracket jumping with <b>ctrl-B</b> works again:

![matchingbrackets3](https://cloud.githubusercontent.com/assets/7548378/11224908/304b8110-8d6f-11e5-9616-46d0969b46b9.png)

**Comment by b4n** [comment]
Although it's already closed, the reason here is that jumping to the matching brace prefers the brace on the left that the one on the right.  As it can jump over `<>` pairs, on your 2nd example it tries to match the `>` on the left of the cursor rather than the `{` on its right.  If you had a matching `<` you'd see the cursor jumping to it.
