### ISSUE TITLE
Unflow paragraph

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#802]
Please consider adding an <b>Unflow paragraph</b> command - the opposite of
<b>Reflow Lines/Block</b>. The use case for this is to make it easy to type in
<b>Geany</b> and then paste the results into the Gmail or Github editor.

Incidentally, <b>Reflow Lines/Block</b> indicates that the conception of a
block of line is already endogenous to <b>Geany</b> and thus I believe that the
concept of extending the highlighting of lines to the line numbers columns
should be considered an extension of an existing capability.

**Comment by elextr** [comment]
The "Reflow Lines/Block" command uses the selection or, purely as a convenience, between the previous blank line and the next blank line if there is no selection, its only in that command and is not really an endogenous concept of a "block", which is something that would vary with the filetype being edited.

**Comment by kugel-** [comment]
What should the command do exactly? Transform a block of text into a single, very long line?

**Comment by elextr** [comment]
I assumed that was what was meant (for pasting into autowrapping things like github)

**Comment by dpl** [comment]
Adding a metoo in support of this feature request. In my opinion, it would/should remove all line breaks within a paragraph of continued text, but not those between paragraphs (i.e., replace anything that is {text}\n{text} with {text}one_space{text} (ideally also taking care of duplicate spaces if the next line was indented or the previous had a dangling spcae); but leave {text}\n\n{text} untouched.

Rationale: Often, I will draft text in Geany (that can be emails, documents, etc.) because it gives me my preferred writing environment. When done, I paste the drafted text into Word, Gmail, wherever it needs to go. The downside is that it will then have indents and line breaks from Geany. I know that I could draft on long lines (without using newlines) and make use of the long line wrap option. But the downside of that is that it deprives me of navigation through the text via home and end keys, and other minor nuisances.

**Comment by vikram-pudi** [comment]
This worked finally for me:

In the Replace dialog box (Ctrl-H):

1. Select: "Use regular expressions" and "Use multi-line matching"
2. Search for: ([^\n])\n(?!\n)
3. Replace with: \1 (put a space here)

And press Replace all -> In Document

**Comment by ntrel** [comment]
*Join Lines* actually already existed as a keybinding since 2012, Geany 1.22. I have made #3402 which adds a menu item to the Format menu.
