### ISSUE TITLE
"which $CXX" breaks if CXX consists of several items

### ISSUE THREAD

**Issue by rofl0r** [geany/geany#829]
https://github.com/geany/geany/blob/master/configure.ac#L35

this check is bogus and should be removed.
it breaks usage for example when CXX is set to ```arm-linux-musleabi-g++ -isystem /sysroot/foo```

```
$ which g++ -isystem foo
/bin/which: unrecognized option: i
BusyBox v1.20.2 (2015-04-23 14:57:49 CEST) multi-call binary.

Usage: which [COMMAND]...

Locate a COMMAND

```

**Comment by b4n** [comment]
Agreed it's broken, we should have a better fix for this -- I don't remember exactly, but IIRC it's something about `AC_PROG_CXX` setting `CXX` to `g++` if it didn't find no compiler at all, and us wanting to fail hard at configure time instead.

Anyway, as a workaround until it gets fixed, you can set `CXXFLAGS` to `-isystem /sysroot/foo` instead of having this in `CXX` itself.

**Comment by rofl0r** [comment]
that workaround is not really acceptable for my distro as it would force me to create some script thats splits CXX into its components and overrides the userprovided CFLAGS.
my workaround is ```sed -i 's@which \$CXX@true@' configure```

**Comment by elextr** [comment]
@b4n, yes it is due to `AC_PROG_CXX` being broken.  But autotools will not fix it now, too many projects will break.  We should just try the `CXX` and fail if it doesn't work.

**Comment by codebrainz** [comment]
Or we could change it to do a proper autoconf test like `AC_COMPILE_IFELSE` or one of those. It's a sure-fire way to tell if `$CXX` contains a working compiler and without any Bash-isms.

**Comment by elextr** [comment]
@codebrainz yep, thats what I was thinking of.

**Comment by rofl0r** [comment]
ping
