### ISSUE TITLE
Transporting bookmarks with moved lines

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#836]
![bookmark1](https://cloud.githubusercontent.com/assets/7548378/11919592/48a2d346-a74e-11e5-90bc-6d02c5f883a3.png)
![bookmark2](https://cloud.githubusercontent.com/assets/7548378/11919593/48a9bcce-a74e-11e5-8e24-feb04892751c.png)
![bookmark4](https://cloud.githubusercontent.com/assets/7548378/11919594/48ab3c70-a74e-11e5-9ef0-325b302d17c7.png)

Please consider transporting bookmarks with their lines when moved from one location to another.  <b>Thanks!</b>

**Comment by codebrainz** [comment]
How would that work? Maybe if moving a line up or down one something could be done, but if you cut a line, there's no info about bookmarks in the clipboard.

**Comment by elextr** [comment]
To expand on @codebrainz point, the clipboard is a system wide resource, not just a Geany internal thing.  Whilst some systems might allow ancilliary data on clipboard contents, some do not, so we can't store the bookmark in the clipboard.  

And it is not possible to keep a local copy of the bookmark because Geany is not informed if the clipboard changes, so for example if I cut a line with a bookmark then go to another application, select and copy some text, when I paste it into Geany it does not know that it is different text from that which had the bookmark.

This is not likely to be implemented, but feel free to ask for re-open if someone comes up with a simple way of doing it.
