### ISSUE TITLE
geany cannot save edited file from sftp and it cannot open a a remote file on remote computer by sftp

### ISSUE THREAD

**Issue by yoosofan** [geany/geany#838]
Ubuntu 15.10 is my current updated operating system. I use Ubuntu and geany for years but the following error seems new to me.
1. geany "Vee" (built on or after 2015-07-12) cannot directly open remote file from sftp by Menu -> File -> Open. It says:
    The folder contents could not be displayed
    The name :1.125 was not provided by any .service files
2. A remote file on sftp can be opened by right click on the file and select geany. geany open it well but when I want to save my edited file, it produces the following error:
      sftp://IP_OF_REMOTE_COMPTER/path/fileName.sh

     Error saving file.
     The name :1.125 was not provided by any .service files
     The file on disk may now be truncated!

**Comment by elextr** [comment]
Geany does not directly access remote files (and never has).  It relies on the system mounting the remote file in the Linux filesystem via a suitable (probably FUSE) filesystem driver.

Probably when you upgraded to 15.10 you didn't enable the right remote filesystem handlers, and thats also what the error message is tending to suggest.

When you say "right click the file" I assume you mean in the file manager.  That allows Geany to read the file because the file manager has mounted it locally, but it can't be saved because either the filemanager dismounts it when you close it, or it doesn't have the right drivers to support writing to the file.

**Comment by yoosofan** [comment]
You are right. The latest patch of Ubuntu 15.10 solved the problem.
Yes, I meant 'right click the file'  in the file manager, in this case  nautilus.
Thanks
