### ISSUE TITLE
Warnings with new Scintilla

### ISSUE THREAD

**Issue by elextr** [geany/geany#875]
Scintilla 3.6.3

```
(geany:3203): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(geany:3203): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(geany:3203): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
```

Suggestions where to look welcome.

**Comment by b4n** [comment]
I don't seem to get those, could you please run under gdb with `--g-fatala-warnings` and give a backtrace?  `gdb -ex run --args geany -v --g-fatal-warnings`

**Comment by elextr** [comment]
Havn't seen them since.

**Comment by b4n** [comment]
Maybe you could still run it like that so in case it happens again you can catch it? :)

**Comment by techee** [comment]
I actually don't think they come from Scintilla but rather from the file browser plugin (or anything displaying file names) - I see these when some files are in invalid encoding (e.g. locale is using UTF-8 but the file on the disk is in different encoding). 

The trouble is that utils_get_utf8_from_locale() fails to convert the invalid encoding to UTF-8 in which case this function just makes a copy of the original non-UTF-8 string. This string is then passed to Gtk which emits this error (when I was playing with locales I was even able to crash Geany because of this - Gtk expects all the strings it gets are valid UTF-8).

Maybe we should use something similar to g_filename_display_name () instead to make sure the output is always a valid UTF-8 string. The trouble might be this would make the conversion irreversible but with invalid encoding there will be other problems anyway.

**Comment by elextr** [comment]
@techee for me the browser says 

```
(firefox:3294): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(firefox:3294): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(firefox:3294): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(firefox:3294): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised
```

At least the browser tells you who is complaining :)

So its not the pango noise (unless the latest update fixed them and added the firefox hint).

**Comment by techee** [comment]
@elextr Notice the difference between "file browser plugin" (of Geany) and "browser" - no, I'm not talking about web browser ;-)

**Comment by elextr** [comment]
@techee ok, well, thats not my problem, only plugin is addons

**Comment by techee** [comment]
@elextr I mentioned the file browser plugin as the most probable cause but it can be anywhere in geany because utils_get_utf8_from_locale() is used everywhere to convert locale to UTF-8 and this function unfortunately doesn't guarantee the result is always UTF-8.

But of course even though I saw this message coming from Geany it doesn't mean it cannot originate in Scintilla in your case.

**Comment by elextr** [comment]
@techee since I am ASCII speaking running on a Linux UTF-8 locale machine its very unlikely for locale issues to happen.  Which may be why I havn't seen it since. :)

I only noticed the messages when shutting down for the night and parked them in the issue to remember them, whatever I did during that day that was unusual I havn't repeated.

Thanks for the suggestions anyway.

**Comment by xiota** [comment]
Is this still relevant?

**Comment by elextr** [comment]
Have not seen those messages again, and nobody else has reported, so closed
