### ISSUE TITLE
Geany often shows blank toolbar without buttons, menu (Lubuntu)

### ISSUE THREAD

**Issue by c4traz** [geany/geany#968]
I'm on Lubuntu 15.10 with Geany 1.25

It never happens on start and I can't reproduce it 'on-demand' but it happens regularly since a long time  when I bring Geany back to foreground. It loses all it's menu and instead of toolbar and buttons there is just a grey area. Moving the window does not bring it back, only resizing the window fixes it.
Reinstalling did not help and I do not have such problem with any other application, but since I cannot find anyone describing such behavior it still may be my setup. Any advice appreciated.

![geany](https://cloud.githubusercontent.com/assets/822081/13825306/44a42c42-ebb2-11e5-9c55-2b320df3c758.png)

**Comment by elextr** [comment]
The conventional wisdom is to suggest trying the current version of Geany, though I doubt it will make any difference.  The problem is like the desktop is not telling GTK its visible so it should re-draw.

I don't know Lubuntu at all, but if it has a setting for desktop acceleration, try turning it off.  I have seen very slow screen redraws on Cinnamon with acceleration on, though that only affected the edit window and needed full screen as well.

**Comment by c4traz** [comment]
Thank you @elextr, I couldn't find a way to activate desktop acceleration so far. Gonna close this.
