### ISSUE TITLE
libgcc_s_dw2-1.dll not found

### ISSUE THREAD

**Issue by NTICompass** [geany/geany#976]
I upgraded from Geany 1.26 to 1.27 and I get an error saying that "libgcc_s_dw2-1.dll" cannot be found.

I'm using the "nogtk" installer on Windows 10 (via chocolatey, actually).  Chocolatey also installed GTK for me (from http://downloads.sourceforge.net/gtk-win/gtk2-runtime-2.24.10-2012-10-10-ash.exe?download).

I reverted back to 1.26 and everything works just fine.

**Comment by codebrainz** [comment]
I can confirm the _nogtk installer misses needed non-GTK runtime libs, like the exception handling lib mentioned and libstdc++.

@NTICompass I have no idea what Chocolatey is but if you want to use the latest Geany release, the one with GTK+ included works great. Otherwise you'll probably have to use msys2 and either run Geany from the msys2 shell or else put the msys2 `bin` directory into your `%PATH%` environment variable.

**Comment by NTICompass** [comment]
[Chocolatey](https://chocolatey.org/) is a package manager for Windows.  It downloads and installs programs (in silent mode).

**Comment by elextr** [comment]
> Chocolatey is a package manager for Windows. It downloads and installs programs (in silent mode).

If something is missing from the package its probably better to notify the packagers, the Geany project does not generate packages.

**Comment by NTICompass** [comment]
@elextr Chocolatey actually just downloads the exe installer and runs it.

**Comment by codebrainz** [comment]
@eht16 maybe we should just stop providing the nogtk installer?

**Comment by elextr** [comment]
On 26 March 2016 at 08:48, Matthew Brush <notifications@github.com> wrote:

> @eht16 <https://github.com/eht16> maybe we should just stop providing the
> nogtk installer?
>

​Or rename it nogtkoranyotherdll installer :)​

**Comment by techee** [comment]
> @eht16 maybe we should just stop providing the nogtk installer?

+1. It's better to know exactly what gtk version and other dependencies are used instead of hunting strange incompatibility problems. Nobody really cares about installer sizes or disk sizes these days (and tens of megabytes is considered "small").

**Comment by eht16** [comment]
Yes, if nobody will complain I will remove _nogtk installer from the website and stop to produce new ones for the future.

The alternative would be to include non-GTK dependencies in the _nogtk installer like gcc libraries and alike but this might get messy. Or we need to clearly list which libraries are necessary and where/how to get them, which might also get quite difficult.

**Comment by codebrainz** [comment]
@eht16 also now that there is no official GTK+ binaries, I'm not sure we can still assume that any old GTK+ .dlls will "just work" with the one compiled from msys2. +1 for dropping it.

**Comment by kugel-** [comment]
What if I maintain my GTK through msys2 (so that I get  lattest gtk quickly)? I probably wouldn't want geany to ship its own dependency stack. -1 for me, but one could probably advertise the full installer more or declare the naked installer for advanced users only.

**Comment by elextr** [comment]
@kugel- but you are not the target of the bundles, they are for Windows *users* so the experience is somewhat similar to other windows software.  

If you are maintaining your own msys2 you are hardly a typical windows user, and you can build from tarball (or git of course :).

**Comment by kugel-** [comment]
Building from source doesn't integrate well with windows (you run make install into some subdir of the msys2 rootfs; no start menu entry, no other goodies the installer offers), so an installer can be preferable.

**Comment by techee** [comment]
What about having one installer containing GTK and having GTK installation optional (enabled by default)?

**Comment by codebrainz** [comment]
> What about having one installer containing GTK and having GTK installation optional (enabled by default)?

This sounds reasonable, but it doesn't help @kugel- if we would still need to install `libgcc_s_dw2-1.dll` and other binaries, it would override the up-to-date ones in his msys2 install. Also, if it's made optional in the installer, IMO it should have some big warning like "do not disable this unless you really know what you're doing" since it would produce a completely borked install if the user didn't manually add a msys2 bin directory containing GTK+ and friends to `%PATH%` variable.

**Comment by techee** [comment]
Actually I've just tried the installer and in "Choose options" there already is the option "GTK X.X Environment" so you can disable its installation already even with the full installer. This should probably include other dependencies like libgcc_s_dw2-1.dll.

**Comment by eht16** [comment]
We could do that.
I personally doubt it is worth the hassle, one has to find the correct set of non-GTK dependencies and keep them up2date across releases and MSYS2 updates.

So we would support the case where (power) Windows users can install a precompiled Geany from the installer with some dependency libraries, in an arbitary version, but without a GTK runtime environment. Those users would have to provide the GTK runtime themselves, and are to ensure this GTK runtime is compatible with the installer provided C runtime libraries and whatever else might be necessary.
To be honest, I doubt this is useful for anyone.

Since we have instructions in the wiki, it should be reasonable easy for such users to compile Geany from source completely using MSYS2.

**Comment by kugel-** [comment]
I think the options are to provide a full geany (including gtk) and naked geany (without anything, not gtk nor C runtime). I see the usefulness in the latter case but we should make it targets expert users who know what they do.

I definitely do not want Geany to install its own gtk when I have a msys2 envorinment running and use other gtk apps as well.

**Comment by eht16** [comment]
We already have what you describe by the mentioned option in the installer called "GTK X.X Environment". Maybe we could rename it to make it more clear this actually refers to dependencies in general, not just GTK.

**Comment by techee** [comment]
> We already have what you describe by the mentioned option in the installer called "GTK X.X Environment". Maybe we could rename it to make it more clear this actually refers to dependencies in general, not just GTK.

Yes, this is what I had in my mind. I just wasn't sure if "GTK X.X Environment" involves other dependencies or not. If this is the case then the current full installer already does what @kugel- needs.

**Comment by eht16** [comment]
> Yes, if nobody will complain I will remove _nogtk installer from the website and stop to produce new ones for the future.

Done.
