### ISSUE TITLE
Windows Defender identifies http://download.geany.org/geany-1.27_setup.exe as malware

### ISSUE THREAD

**Issue by gharris999** [geany/geany#990]
Windows 10, Windows Defender
Definitions from 4/8/2016 8:45 AM
Virus definition version: 1.217.970.0
Spyware definition version: 1.217.970.0

Geany setup downloaded from: http://download.geany.org/geany-1.27_setup.exe

Windows Defender says that this contains:

Detected Item
Trojan:Win32/Fethar.A!cl

Alert Level
Severe

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\Users\...\Downloads\geany-1.27_setup.exe
webfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{4BC9919C-4174-4B43-A5DC-B5BE907D1B01}-geany-1.27_setup.exe|chrome.exe
webfile:C:\Users...\Downloads\geany-1.27_setup.exe|http://download.geany.org/geany-1.27_setup.exe|chrome.exe

Get more information about this item online:
http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFethar.A!cl&threatid=2147708974&enterprise=0

**Comment by codebrainz** [comment]
@gharris999 did you happen to see #978?

**Comment by codebrainz** [comment]
Maybe someone can submit to [Microsoft](https://www.microsoft.com/en-us/security/portal/submission/submit.aspx) and have them take a look? It might get the false positive removed from their definitions, or at least provide us more information than the none that is on the link Defender gives.

**Comment by codebrainz** [comment]
@eht16 After a quick search online, I'm betting the false positive is caused by NSIS, assuming a different/newer version was used this time than from the previous release. Apparently, it's somewhat common for NSIS installers to be wrongly detected.

**Comment by gharris999** [comment]
Sorry, no, I didn't see #978 before I submitted this issue.  Anyway, #978's submitter isn't the only one seeing this problem.  And yes, I am assuming this is a false positive.  I should have stated that in the submission.

**Comment by eht16** [comment]
> @eht16 After a quick search online, I'm betting the false positive is caused by NSIS, assuming a different/newer version was used this time than from the previous release. Apparently, it's somewhat common for NSIS installers to be wrongly detected.
I used the same NSIS as in previous releases.
But maybe the change in
https://github.com/geany/geany/commit/52f5b88873c44486157cfb6127598e92f909172e
is related to this issue.
That change increases startup speed of the installer because it doesn't
have to extract the embedded data prior to starting up at all but only
first when the real installation takes places. In other words, this
eliminates the little "Extracting ... %" dialog at the beginning.
To test this assumption, I created a new installer without the
ReserveFile statements.

http://uvena.de/tmp/geany-1.28nightly_setup_test_defender.exe

@gharris999, @psccox: could you test this installer? Maybe just download
and execute it but do not finish the installer as it contains a build of
Geany from GIT master and against GTK3, which is quite different from
the released version. The test installer is just about to check whether
Windows Defender will report it or not.

**Comment by psccox** [comment]
2 issues:
(1) Chrome blocks the download saying the file is not commonly downloaded (presumably your uvena host) linking to a [support page](https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1)
(2) Downloading the file with Firefox reports no problems scanning with Defender. BUT - launching the .exe popups up a

**Comment by eht16** [comment]
Thanks for testing, though it seems there is end of the last sentence missing :).

**Comment by psccox** [comment]
Sorry @eht16, the web interface truncated my comment. Please see where I edited it.

**Comment by eht16** [comment]
Thanks.
Regarding (1): yes, this is probably related to uvena.de, Google tends to think the server is sending spam. But Google refuses to tell me why they think so.
Regarding (2): so you couldn't start the installer at all due to this dialog?

**Comment by gharris999** [comment]
OK, I just tried to download eht16's file.  Chrome is complaining about the file, but allows me to "keep" the file.  A subsequent scan of the file with Windows Defender says:

Scan completed on 6049 items. No threats were detected on your PC during this scan.

On the other hand, downloading http://download.geany.org/geany-1.27_setup.exe raises no complaints from Chrome and now, not a peep from Windows Defender.  

So problem solved by Microsoft with a definitions update, probably.

This is what Chrome had to say about eht16's file:

Google Chrome blocks downloads

Chrome automatically blocks harmful downloads that try to cause problems on your computer, like:

Giving you viruses
Leaking your private data
Changing your browser and computer settings
Adding unwanted extensions or toolbars to your browser
Why the download was blocked

Your file download may have been blocked for one of two reasons:

We think it might be a malicious, unwanted, or uncommon file.
Malicious: You tried downloading malware.
Unwanted: You tried downloading a deceptive piece of software. This program, disguised as a helpful download, may actually make unexpected changes to your computer.
Uncommon: You tried downloading an unfamiliar and potentially dangerous piece of software.
We've found that the website you tried to download the file from has been known to distribute malware.

**Comment by eht16** [comment]
Thanks for the feedback.
So about the Windows Defender issue: fine, let's hope this won't happen again in the future.

And thanks for the Chrome message. After a quick search for getting more information about this, I noticed there is some "Security Center" or something for webmasters to identify and solve such issues but only available with a Google account. Since I don't have one, I'll probably need to contact them in some other way. Will do later.
But it's not relevant here for Geany.
