### ISSUE TITLE
Nasty messages from splitwindow plugin

### ISSUE THREAD

**Issue by elextr** [geany/geany#993]
Geany 1.28 from git 24f91981c057a7e212c09da66fb974c3ccc85bd6, normal splitwindow plugin, neither @b4n or @kugel- specials,  GTK 3.10.8, GLib 2.40.2

When selecting a different buffer for display on the second window using the dropdown list gets the following each time:

```
(geany:9145): Gtk-CRITICAL **: gtk_widget_unmap: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:9145): Gtk-CRITICAL **: gtk_widget_unmap: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:9145): Gtk-CRITICAL **: gtk_widget_unrealize: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:9145): Gtk-CRITICAL **: gtk_widget_unrealize: assertion 'GTK_IS_WIDGET (widget)' failed

```

**Comment by elextr** [comment]
Update: happens when the file is changed in the split window (using the dropdown list on the split window).

**Comment by elextr** [comment]
Did a gdb backtrace on the first message, the only two non-gtk things in it are:

splitwindow.c:172
gtk/ScintillaGTK.cxx:614

@b4n, Note also happens on gtk2, should be fixed before 1.28 if possible, added millstone.

**Comment by codebrainz** [comment]
Started between 1.25 and 1.26

**Comment by codebrainz** [comment]
Most likely not the correct fix, but the warnings can be silenced [with these changes](https://gist.github.com/codebrainz/8ea8534a3dc72b5de1944168ef92dfbd).

**Comment by b4n** [comment]
See https://github.com/geany/geany/pull/1272#issuecomment-255576509

@codebrainz actually your proposed fix is almost correct, but the `GTK_IS_WIDGET()` part is unnecessary -- and suggests it might be something else.  The problem is simply that the scrollbars will be `NULL` if `Dispose()` has already run, which will happen if destroying a still displayed widget (I think it's as easy as that, but I didn't triple check).

**Comment by codebrainz** [comment]
@b4n yeah, it was just a quick patch to stop the warnings, a dynamic cast (if they're enabled) is indeed overkill.
